-- Accounting (7707) - Cambridge O Level outline with objectives, loaded into O1 + O2.

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O1)' AND name='Accounting' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Accounting O Level (O1) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2027-2029','7707','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2027-2029', cambridge_code='7707', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','The fundamentals of accounting',0),
    (v_org,v_tpl,'2','Sources and recording of data',1),
    (v_org,v_tpl,'3','Verification of accounting records',2),
    (v_org,v_tpl,'4','Accounting procedures',3),
    (v_org,v_tpl,'5','Preparation of financial statements',4),
    (v_org,v_tpl,'6','Analysis and interpretation',5),
    (v_org,v_tpl,'7','Accounting concepts and modern practice',6);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','The purpose of accounting','["the difference between book-keeping and accounting", "the purposes of measuring business profit and loss", "the role of accounting in providing information for monitoring progress and decision-making"]'::jsonb,0),
    ('1','1.2','The accounting equation','["assets, liabilities and owner''s equity", "the accounting equation", "how to apply the accounting equation"]'::jsonb,1),
    ('2','2.1','The double entry system of book-keeping','["the double entry system of book-keeping", "how to prepare ledger accounts", "how to post transactions to the ledger accounts", "how to calculate ledger account balances and make transfers to financial statements", "how to interpret ledger accounts and their balances", "ledger accounts that may be presented using a three-column running balance format", "the division of the ledger into the sales ledger, the purchases ledger and the nominal (general) ledger", "how ledger accounts can be kept digitally Note: Candidates do not need to explain or use folio columns."]'::jsonb,0),
    ('2','2.2','Business documents','["business documents: invoice, debit note, credit note, cheque counterfoil, paying-in slip, receipt, bank statement, statement of account", "how these business documents are used as sources of information", "these business documents being produced and recorded manually or digitally"]'::jsonb,1),
    ('2','2.3','Books of prime entry','["how to process accounting data in the books of prime entry: cash book, petty cash book, sales journal, purchases journal, sales returns journal, purchases returns journal and the general journal", "how to post the ledger entries from the books of prime entry", "trade discount and cash discount and how these are treated", "the dual function of the cash book as a book of prime entry and as a ledger account for bank and cash", "how to record receipts and payments made by cash, cheques, debit and credit cards, online and bank transfers", "the purpose of the imprest system of petty cash", "how to apply the imprest system", "the benefits and limitations of keeping cash at the business property", "the benefits and limitations of using manual methods for the original entry of business transactions", "the benefits and limitations of using digital methods for the original entry of business transactions"]'::jsonb,2),
    ('3','3.1','The trial balance','["the purposes and limitations of a trial balance", "how to prepare a trial balance from a given list of balances and amend a trial balance which contains errors", "the types of errors which do not affect the trial balance: commission, compensating, complete reversal, omission, original entry, principle"]'::jsonb,0),
    ('3','3.2','Corrections of errors','["how to correct errors using journal entries", "the use of a suspense account as a temporary measure to balance the trial balance", "how to correct errors using a suspense account", "how to adjust a profit or loss for an accounting period after the correction of errors", "the effect of correction of errors on a statement of financial position"]'::jsonb,1),
    ('3','3.3','Bank reconciliation','["the use and purpose of a bank statement", "how to update the cash book for bank charges, bank interest paid and received, correction of errors, credit transfers, direct debits, and standing orders", "the purpose and preparation of a bank reconciliation statement to include bank errors, uncredited deposits and unpresented cheques", "the impact of digital business transactions on the bank reconciliation process"]'::jsonb,2),
    ('3','3.4','Control accounts','["the purposes of purchases ledger and sales ledger control accounts", "the books of prime entry as sources of information for the control account entries", "how to prepare purchases ledger and sales ledger control accounts to include credit purchases and sales, receipts and payments, cash discounts, returns, irrecoverable debts, dishonoured cheques, interest on overdue accounts, contra entries, refunds, opening and closing balances (debit and credit within each account)", "the impact of digital recording of business transactions on the preparation and use of control accounts Note: Candidates do not need to reconcile control account balances with the sales and purchases ledger balances."]'::jsonb,3),
    ('4','4.1','Capital and revenue expenditure and receipts','["the distinction between capital expenditure and revenue expenditure", "how to account for capital expenditure and revenue expenditure", "the distinction between capital receipts and revenue receipts", "how to account for capital receipts and revenue receipts", "how to identify and calculate the effect on profit of incorrect treatment", "how to identify and calculate the effect on asset valuations of incorrect treatment"]'::jsonb,0),
    ('4','4.2','Accounting for depreciation and disposal of non-current assets','["the meaning of depreciation", "the need to account for depreciation", "how to calculate depreciation using the straight-line, reducing balance and revaluation methods", "the appropriate methods of depreciation that can be applied to different types of non-current assets", "how to prepare journal entries and ledger accounts to record depreciation", "how to prepare journal entries to record the purchase and sale of non-current assets", "how to prepare ledger accounts to record the purchase and sale of non-current assets: non-current asset account, provision for depreciation account, and disposal of non-current asset account", "how to calculate profit or loss on disposal of a non-current asset"]'::jsonb,1),
    ('4','4.3','Other payables and other receivables','["the importance of matching costs and revenues", "how to apply the matching / accruals concepts by using accruals and pre-payments", "how to prepare journal entries and ledger accounts to record accrued and prepaid expenses", "how to prepare journal entries and ledger accounts to record accrued and prepaid incomes"]'::jsonb,2),
    ('4','4.4','Irrecoverable debts and allowance for irrecoverable debts','["the meaning of irrecoverable debts and irrecoverable debts recovered", "how to prepare journal entries and ledger accounts to record irrecoverable debts", "how to prepare journal entries and ledger accounts to record irrecoverable debts recovered", "the need for maintaining an allowance for irrecoverable debts", "how to prepare journal entries and ledger accounts to record the creation of, and adjustments to, an allowance for irrecoverable debts"]'::jsonb,3),
    ('4','4.5','Valuation of inventory','["the valuation of inventory at the lower of cost and net realisable value", "how to calculate the value of inventory", "the effect of an incorrect valuation of inventory on gross profit, profit for the year, equity and asset valuation"]'::jsonb,4),
    ('5','5.1','Sole traders','["the advantages and disadvantages of operating as a sole trader", "how a sole trader can be a trading, service, manufacturing business or a combination of these", "the importance of preparing statements of profit or loss and statements of financial position", "how to prepare statements of profit or loss for trading, service, manufacturing businesses, or businesses which are a combination of these", "the importance of producing statements of financial position to record assets and liabilities on a specified date", "how to define the content of a statement of financial position: non-current assets, intangible assets, current assets, current liabilities, non-current liabilities and capital", "the effect of a change in an account balance on other account balances in the financial statements", "how to prepare statements of financial position for trading, service, manufacturing businesses, or businesses which are a combination of these", "how to make adjustments for accumulated depreciation using the straight line, reducing balance and revaluation methods", "how to make adjustments for accrued and prepaid expenses and accrued and prepaid income", "how to make adjustments for irrecoverable debts and allowance for irrecoverable debts", "how to make adjustments for drawings: goods and other assets taken by the owner, owner''s private expenses paid by the business"]'::jsonb,0),
    ('5','5.2','Partnerships','["how a partnership can be a trading, service, manufacturing business or a combination of these", "the advantages and disadvantages of forming a partnership", "the importance and contents of a partnership agreement", "the purpose of an appropriation account", "how to prepare statements of profit or loss, appropriation accounts and statements of financial position", "how to record interest on partners'' loans, interest on capital, interest on drawings, partners'' salaries and the division of the balance of profit or loss", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "the uses of and differences between partners'' capital and current accounts", "how to prepare partners'' capital and current accounts in ledger account form and as part of a statement of financial position Note: Candidates will not be required to answer questions on the dissolution of a partnership, changes to a profit-sharing ratio or a limited liability partnership. Candidates will not be required to prepare financial statements on the admission/departure of a partner."]'::jsonb,1),
    ('5','5.3','Limited companies','["how a limited company can be a trading, service, manufacturing business or a combination of these", "the advantages and disadvantages of operating as a limited company", "the term ''limited liability''", "the term ''equity''", "the capital structure of a limited company comprising preference share capital, ordinary share capital, general reserve and retained earnings", "the features of ordinary share capital and loan capital (debentures)", "share capital: issued, called-up, and paid-up", "how to prepare statements of profit or loss, statements of changes in equity and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)"]'::jsonb,2),
    ('5','5.4','Manufacturing accounts','["direct and indirect costs", "direct material, direct labour, prime cost and factory overheads", "how to make adjustments for work in progress", "how to calculate factory cost of production", "how to prepare manufacturing accounts, statements of profit or loss and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)"]'::jsonb,3),
    ('5','5.5','Clubs and societies','["receipts and payments accounts and income and expenditure accounts", "how to prepare receipts and payments accounts", "how to prepare accounts for revenue-generating activities, e.g. refreshments, subscriptions", "how to prepare income and expenditure accounts and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "how to define and calculate the accumulated fund"]'::jsonb,4),
    ('5','5.6','Incomplete records','["why businesses keep different types of accounting records rather than using the full double entry system", "the advantages and disadvantages of not maintaining a full set of accounting records", "how to prepare opening and closing statements of affairs", "how to calculate profit or loss for the year from changes in capital over time", "how to calculate sales, purchases, gross profit, trade receivables and trade payables and other figures from incomplete information", "how to prepare statements of profit or loss and statements of financial position from incomplete records", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "how to apply the techniques of mark-up, margin and inventory turnover to arrive at missing figures Note: Candidates will only be asked questions on incomplete records in relation to sole trader businesses. Candidates will not be asked questions on incomplete records for service or manufacturing businesses."]'::jsonb,5),
    ('6','6.1','Calculation and understanding of accounting ratios','["gross profit margin", "mark-up", "profit margin", "return on capital employed (ROCE)", "current (working capital) ratio", "acid test (liquid) ratio", "rate of inventory turnover (times)", "inventory turnover (days)", "trade receivables turnover (days)", "trade payables turnover (days) Note: Candidates must use the formulas given in the Accounting ratios included at the end of this section. These are the only formulas accepted in candidate responses."]'::jsonb,0),
    ('6','6.2','Interpretation of accounting ratios','["how to prepare and comment on statements showing comparison of results for different years", "how to interpret the ratios calculated in 6.1", "make suggestions and recommendations for improving profitability, liquidity and working capital", "the gross profit margin and the profit margin as indicators of a business''s profitability", "how gross profit for the year can be affected by the valuation of inventory, sales quantity and changes in selling and purchasing prices", "how profit for the year can be affected by changes in gross profit, other income and expenses", "the reasons for the difference between cash and profit"]'::jsonb,1),
    ('6','6.3','Inter-business comparison','["the factors that may affect the ratios of two businesses", "the problems of inter-business comparison"]'::jsonb,2),
    ('6','6.4','Interested parties','["by the following interested parties:", "owners", "managers", "employees", "banks", "investors and lenders", "suppliers", "customers", "governments / tax authorities", "club members", "other interested parties, e.g. public and environmental bodies"]'::jsonb,3),
    ('6','6.5','Limitations of accounting statements','["factors:", "historic cost", "application of accounting policies", "non-financial aspects for example, skill of the workforce, location of the business, economic climate"]'::jsonb,4),
    ('7','7.1','Accounting concepts','["business entity", "consistency", "duality", "going concern", "historic cost", "matching / accruals", "materiality", "money measurement", "prudence", "realisation"]'::jsonb,0),
    ('7','7.2','Ethical considerations','["the need for an ethical framework in accounting", "the fundamental principles of: - integrity - objectivity - professional competence and due care - confidentiality - professional behaviour", "the significance to stakeholders and society of applying an ethical framework"]'::jsonb,1),
    ('7','7.3','Technology and sustainability','["the use of digital applications for all or part of the accounting records", "the need to store accounting data safely and sustainably", "the risks associated with not storing accounting data safely and sustainably", "the different types of storage systems: manual, data storage devices, cloud services, other digital services", "the advantages and disadvantages of the different types of storage systems Note: Candidates do not need to have knowledge of or access to specific accounting software packages or programs. Accounting ratios Profitability ratios Gross profit margin (%) Gross profit Revenue Mark-up (%) Gross profit Cost of sales × 100 Profit margin (%) Profit for the year Revenue Return on capital employed (ROCE) (%) Profit for the year before interest Capital employed Capital employed = issued shares + reserves + non-current liabilities Liquidity ratios Current (working capital) ratio Current assets Current liabilities Answer presented as a ratio Acid test (liquid) ratio Current assets - inventory Current liabilities Answer presented as a ratio Efficiency ratios Rate of inventory turnover (times) Cost of sales Average inventory Inventory turnover (days) Average inventory Cost of sales Trade receivables turnover (days) Trade receivables Credit sales Trade payables turnover (days) Trade payables Credit purchases Faculty feedback: ''Understanding how and why our climate is changing and providing the knowledge and skills to explore the challenges plays a key role in every student''s education.'' Feedback from: Dr Amy Munro-Faure, Head of Education and Student Engagement of Cambridge Zero"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Accounting O Level (O1)';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O2)' AND name='Accounting' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Accounting O Level (O2) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2027-2029','7707','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2027-2029', cambridge_code='7707', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','The fundamentals of accounting',0),
    (v_org,v_tpl,'2','Sources and recording of data',1),
    (v_org,v_tpl,'3','Verification of accounting records',2),
    (v_org,v_tpl,'4','Accounting procedures',3),
    (v_org,v_tpl,'5','Preparation of financial statements',4),
    (v_org,v_tpl,'6','Analysis and interpretation',5),
    (v_org,v_tpl,'7','Accounting concepts and modern practice',6);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','The purpose of accounting','["the difference between book-keeping and accounting", "the purposes of measuring business profit and loss", "the role of accounting in providing information for monitoring progress and decision-making"]'::jsonb,0),
    ('1','1.2','The accounting equation','["assets, liabilities and owner''s equity", "the accounting equation", "how to apply the accounting equation"]'::jsonb,1),
    ('2','2.1','The double entry system of book-keeping','["the double entry system of book-keeping", "how to prepare ledger accounts", "how to post transactions to the ledger accounts", "how to calculate ledger account balances and make transfers to financial statements", "how to interpret ledger accounts and their balances", "ledger accounts that may be presented using a three-column running balance format", "the division of the ledger into the sales ledger, the purchases ledger and the nominal (general) ledger", "how ledger accounts can be kept digitally Note: Candidates do not need to explain or use folio columns."]'::jsonb,0),
    ('2','2.2','Business documents','["business documents: invoice, debit note, credit note, cheque counterfoil, paying-in slip, receipt, bank statement, statement of account", "how these business documents are used as sources of information", "these business documents being produced and recorded manually or digitally"]'::jsonb,1),
    ('2','2.3','Books of prime entry','["how to process accounting data in the books of prime entry: cash book, petty cash book, sales journal, purchases journal, sales returns journal, purchases returns journal and the general journal", "how to post the ledger entries from the books of prime entry", "trade discount and cash discount and how these are treated", "the dual function of the cash book as a book of prime entry and as a ledger account for bank and cash", "how to record receipts and payments made by cash, cheques, debit and credit cards, online and bank transfers", "the purpose of the imprest system of petty cash", "how to apply the imprest system", "the benefits and limitations of keeping cash at the business property", "the benefits and limitations of using manual methods for the original entry of business transactions", "the benefits and limitations of using digital methods for the original entry of business transactions"]'::jsonb,2),
    ('3','3.1','The trial balance','["the purposes and limitations of a trial balance", "how to prepare a trial balance from a given list of balances and amend a trial balance which contains errors", "the types of errors which do not affect the trial balance: commission, compensating, complete reversal, omission, original entry, principle"]'::jsonb,0),
    ('3','3.2','Corrections of errors','["how to correct errors using journal entries", "the use of a suspense account as a temporary measure to balance the trial balance", "how to correct errors using a suspense account", "how to adjust a profit or loss for an accounting period after the correction of errors", "the effect of correction of errors on a statement of financial position"]'::jsonb,1),
    ('3','3.3','Bank reconciliation','["the use and purpose of a bank statement", "how to update the cash book for bank charges, bank interest paid and received, correction of errors, credit transfers, direct debits, and standing orders", "the purpose and preparation of a bank reconciliation statement to include bank errors, uncredited deposits and unpresented cheques", "the impact of digital business transactions on the bank reconciliation process"]'::jsonb,2),
    ('3','3.4','Control accounts','["the purposes of purchases ledger and sales ledger control accounts", "the books of prime entry as sources of information for the control account entries", "how to prepare purchases ledger and sales ledger control accounts to include credit purchases and sales, receipts and payments, cash discounts, returns, irrecoverable debts, dishonoured cheques, interest on overdue accounts, contra entries, refunds, opening and closing balances (debit and credit within each account)", "the impact of digital recording of business transactions on the preparation and use of control accounts Note: Candidates do not need to reconcile control account balances with the sales and purchases ledger balances."]'::jsonb,3),
    ('4','4.1','Capital and revenue expenditure and receipts','["the distinction between capital expenditure and revenue expenditure", "how to account for capital expenditure and revenue expenditure", "the distinction between capital receipts and revenue receipts", "how to account for capital receipts and revenue receipts", "how to identify and calculate the effect on profit of incorrect treatment", "how to identify and calculate the effect on asset valuations of incorrect treatment"]'::jsonb,0),
    ('4','4.2','Accounting for depreciation and disposal of non-current assets','["the meaning of depreciation", "the need to account for depreciation", "how to calculate depreciation using the straight-line, reducing balance and revaluation methods", "the appropriate methods of depreciation that can be applied to different types of non-current assets", "how to prepare journal entries and ledger accounts to record depreciation", "how to prepare journal entries to record the purchase and sale of non-current assets", "how to prepare ledger accounts to record the purchase and sale of non-current assets: non-current asset account, provision for depreciation account, and disposal of non-current asset account", "how to calculate profit or loss on disposal of a non-current asset"]'::jsonb,1),
    ('4','4.3','Other payables and other receivables','["the importance of matching costs and revenues", "how to apply the matching / accruals concepts by using accruals and pre-payments", "how to prepare journal entries and ledger accounts to record accrued and prepaid expenses", "how to prepare journal entries and ledger accounts to record accrued and prepaid incomes"]'::jsonb,2),
    ('4','4.4','Irrecoverable debts and allowance for irrecoverable debts','["the meaning of irrecoverable debts and irrecoverable debts recovered", "how to prepare journal entries and ledger accounts to record irrecoverable debts", "how to prepare journal entries and ledger accounts to record irrecoverable debts recovered", "the need for maintaining an allowance for irrecoverable debts", "how to prepare journal entries and ledger accounts to record the creation of, and adjustments to, an allowance for irrecoverable debts"]'::jsonb,3),
    ('4','4.5','Valuation of inventory','["the valuation of inventory at the lower of cost and net realisable value", "how to calculate the value of inventory", "the effect of an incorrect valuation of inventory on gross profit, profit for the year, equity and asset valuation"]'::jsonb,4),
    ('5','5.1','Sole traders','["the advantages and disadvantages of operating as a sole trader", "how a sole trader can be a trading, service, manufacturing business or a combination of these", "the importance of preparing statements of profit or loss and statements of financial position", "how to prepare statements of profit or loss for trading, service, manufacturing businesses, or businesses which are a combination of these", "the importance of producing statements of financial position to record assets and liabilities on a specified date", "how to define the content of a statement of financial position: non-current assets, intangible assets, current assets, current liabilities, non-current liabilities and capital", "the effect of a change in an account balance on other account balances in the financial statements", "how to prepare statements of financial position for trading, service, manufacturing businesses, or businesses which are a combination of these", "how to make adjustments for accumulated depreciation using the straight line, reducing balance and revaluation methods", "how to make adjustments for accrued and prepaid expenses and accrued and prepaid income", "how to make adjustments for irrecoverable debts and allowance for irrecoverable debts", "how to make adjustments for drawings: goods and other assets taken by the owner, owner''s private expenses paid by the business"]'::jsonb,0),
    ('5','5.2','Partnerships','["how a partnership can be a trading, service, manufacturing business or a combination of these", "the advantages and disadvantages of forming a partnership", "the importance and contents of a partnership agreement", "the purpose of an appropriation account", "how to prepare statements of profit or loss, appropriation accounts and statements of financial position", "how to record interest on partners'' loans, interest on capital, interest on drawings, partners'' salaries and the division of the balance of profit or loss", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "the uses of and differences between partners'' capital and current accounts", "how to prepare partners'' capital and current accounts in ledger account form and as part of a statement of financial position Note: Candidates will not be required to answer questions on the dissolution of a partnership, changes to a profit-sharing ratio or a limited liability partnership. Candidates will not be required to prepare financial statements on the admission/departure of a partner."]'::jsonb,1),
    ('5','5.3','Limited companies','["how a limited company can be a trading, service, manufacturing business or a combination of these", "the advantages and disadvantages of operating as a limited company", "the term ''limited liability''", "the term ''equity''", "the capital structure of a limited company comprising preference share capital, ordinary share capital, general reserve and retained earnings", "the features of ordinary share capital and loan capital (debentures)", "share capital: issued, called-up, and paid-up", "how to prepare statements of profit or loss, statements of changes in equity and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)"]'::jsonb,2),
    ('5','5.4','Manufacturing accounts','["direct and indirect costs", "direct material, direct labour, prime cost and factory overheads", "how to make adjustments for work in progress", "how to calculate factory cost of production", "how to prepare manufacturing accounts, statements of profit or loss and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)"]'::jsonb,3),
    ('5','5.5','Clubs and societies','["receipts and payments accounts and income and expenditure accounts", "how to prepare receipts and payments accounts", "how to prepare accounts for revenue-generating activities, e.g. refreshments, subscriptions", "how to prepare income and expenditure accounts and statements of financial position", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "how to define and calculate the accumulated fund"]'::jsonb,4),
    ('5','5.6','Incomplete records','["why businesses keep different types of accounting records rather than using the full double entry system", "the advantages and disadvantages of not maintaining a full set of accounting records", "how to prepare opening and closing statements of affairs", "how to calculate profit or loss for the year from changes in capital over time", "how to calculate sales, purchases, gross profit, trade receivables and trade payables and other figures from incomplete information", "how to prepare statements of profit or loss and statements of financial position from incomplete records", "how to make adjustments to financial statements as detailed in 5.1 (sole traders)", "how to apply the techniques of mark-up, margin and inventory turnover to arrive at missing figures Note: Candidates will only be asked questions on incomplete records in relation to sole trader businesses. Candidates will not be asked questions on incomplete records for service or manufacturing businesses."]'::jsonb,5),
    ('6','6.1','Calculation and understanding of accounting ratios','["gross profit margin", "mark-up", "profit margin", "return on capital employed (ROCE)", "current (working capital) ratio", "acid test (liquid) ratio", "rate of inventory turnover (times)", "inventory turnover (days)", "trade receivables turnover (days)", "trade payables turnover (days) Note: Candidates must use the formulas given in the Accounting ratios included at the end of this section. These are the only formulas accepted in candidate responses."]'::jsonb,0),
    ('6','6.2','Interpretation of accounting ratios','["how to prepare and comment on statements showing comparison of results for different years", "how to interpret the ratios calculated in 6.1", "make suggestions and recommendations for improving profitability, liquidity and working capital", "the gross profit margin and the profit margin as indicators of a business''s profitability", "how gross profit for the year can be affected by the valuation of inventory, sales quantity and changes in selling and purchasing prices", "how profit for the year can be affected by changes in gross profit, other income and expenses", "the reasons for the difference between cash and profit"]'::jsonb,1),
    ('6','6.3','Inter-business comparison','["the factors that may affect the ratios of two businesses", "the problems of inter-business comparison"]'::jsonb,2),
    ('6','6.4','Interested parties','["by the following interested parties:", "owners", "managers", "employees", "banks", "investors and lenders", "suppliers", "customers", "governments / tax authorities", "club members", "other interested parties, e.g. public and environmental bodies"]'::jsonb,3),
    ('6','6.5','Limitations of accounting statements','["factors:", "historic cost", "application of accounting policies", "non-financial aspects for example, skill of the workforce, location of the business, economic climate"]'::jsonb,4),
    ('7','7.1','Accounting concepts','["business entity", "consistency", "duality", "going concern", "historic cost", "matching / accruals", "materiality", "money measurement", "prudence", "realisation"]'::jsonb,0),
    ('7','7.2','Ethical considerations','["the need for an ethical framework in accounting", "the fundamental principles of: - integrity - objectivity - professional competence and due care - confidentiality - professional behaviour", "the significance to stakeholders and society of applying an ethical framework"]'::jsonb,1),
    ('7','7.3','Technology and sustainability','["the use of digital applications for all or part of the accounting records", "the need to store accounting data safely and sustainably", "the risks associated with not storing accounting data safely and sustainably", "the different types of storage systems: manual, data storage devices, cloud services, other digital services", "the advantages and disadvantages of the different types of storage systems Note: Candidates do not need to have knowledge of or access to specific accounting software packages or programs. Accounting ratios Profitability ratios Gross profit margin (%) Gross profit Revenue Mark-up (%) Gross profit Cost of sales × 100 Profit margin (%) Profit for the year Revenue Return on capital employed (ROCE) (%) Profit for the year before interest Capital employed Capital employed = issued shares + reserves + non-current liabilities Liquidity ratios Current (working capital) ratio Current assets Current liabilities Answer presented as a ratio Acid test (liquid) ratio Current assets - inventory Current liabilities Answer presented as a ratio Efficiency ratios Rate of inventory turnover (times) Cost of sales Average inventory Inventory turnover (days) Average inventory Cost of sales Trade receivables turnover (days) Trade receivables Credit sales Trade payables turnover (days) Trade payables Credit purchases Faculty feedback: ''Understanding how and why our climate is changing and providing the knowledge and skills to explore the challenges plays a key role in every student''s education.'' Feedback from: Dr Amy Munro-Faure, Head of Education and Student Engagement of Cambridge Zero"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Accounting O Level (O2)';
END $$;
