-- Computer Science (2210) - Cambridge O Level outline with objectives, loaded into O1 + O2.

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O1)' AND name='Computer Science' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Computer Science O Level (O1) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','2210','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='2210', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Data representation',0),
    (v_org,v_tpl,'2','Data transmission',1),
    (v_org,v_tpl,'3','Hardware',2),
    (v_org,v_tpl,'4','Software',3),
    (v_org,v_tpl,'5','The internet and its uses',4),
    (v_org,v_tpl,'6','Automated and emerging technologies',5),
    (v_org,v_tpl,'8','Programming',6);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Number systems','["1 Understand how and why computers use binary to represent all forms of data", "2 (a) Understand the denary, binary and hexadecimal number systems", "(b) Convert between (i) positive denary and positive binary (ii) positive denary and positive hexadecimal (iii) positive hexadecimal and positive binary 3 Understand how and why hexadecimal is used as a beneficial method of data representation", "4 (a) Add two positive 8-bit binary integers (b) Understand the concept of overflow and why it occurs in binary addition", "5 Perform a logical binary shift on a positive 8-bit binary integer and understand the effect this has on the positive binary integer", "6 Use the two''s complement number system to represent positive and negative 8-bit binary integers"]'::jsonb,0),
    ('1','1.2','Text, sound and images','["1 Understand how and why a computer represents text and the use of character sets, including American standard code for information interchange (ASCII) and Unicode", "2 Understand how and why a computer represents sound, including the effects of the sample rate and sample resolution", "3 Understand how and why a computer represents an image, including the effects of the resolution and colour depth"]'::jsonb,1),
    ('1','1.3','Data storage and compression','["1 Understand how data storage is measured", "2 Calculate the file size of an image file and a sound file, using information given", "3 Understand the purpose of and need for data compression", "4 Understand how files are compressed using lossy and lossless compression methods"]'::jsonb,2),
    ('2','2.1','Types and methods of data transmission','["1 (a) Understand that data is broken down into packets to be transmitted (b) Describe the structure of a packet", "(c) Describe the process of packet switching", "2 (a) Describe how data is transmitted from one device to another using different methods of data transmission", "(b) Explain the suitability of each method of data transmission, for a given scenario 3 Understand the universal serial bus (USB) interface and explain how it is used to transmit data"]'::jsonb,0),
    ('2','2.2','Methods of error detection','["1 Understand the need to check for errors after data transmission and how these errors can occur 2 Describe the processes involved in each of the following error detection methods for detecting errors in data after transmission: parity check (odd and even), checksum and echo check 3 Describe how a check digit is used to detect errors in data entry and identify examples of when a check digit is used, including international standard book numbers (ISBN) and bar codes 4 Describe how an automatic repeat query (ARQ) can be used to establish that data is received without error"]'::jsonb,1),
    ('2','2.3','Encryption','["1 Understand the need for and purpose of encryption when transmitting data 2 Understand how data is encrypted using symmetric and asymmetric encryption"]'::jsonb,2),
    ('3','3.1','Computer architecture','["1 (a) Understand the role of the central processing unit (CPU) in a computer", "(b) Understand what is meant by a microprocessor 2 (a) Understand the purpose of the components in a CPU, in a computer that has a Von Neumann architecture", "(b) Describe the process of the fetch-decode-execute (FDE) cycle, including the role of each component in the process", "3 Understand what is meant by a core, cache and clock in a CPU and explain how they can affect the performance of a CPU 4 Understand the purpose and use of an instruction set for a CPU", "5 Describe the purpose and characteristics of an embedded system and identify devices in which they are commonly used"]'::jsonb,0),
    ('3','3.2','Input and output devices','["1 Understand what is meant by an input device and why it is required", "2 Understand what is meant by an output device and why it is required", "3 (a) Understand what is meant by a sensor and the purposes of sensors", "(b) Identify the type of data captured by each sensor and understand when each sensor would be used, including selecting the most suitable sensor for a given context"]'::jsonb,1),
    ('3','3.3','Data storage','["1 Understand what is meant by primary storage", "2 Understand what is meant by secondary storage", "3 Describe the operation of magnetic, optical and solid-state (flash memory) storage and give examples of each", "4 Describe what is meant by virtual memory, how it is created and used and why it is necessary 5 Understand what is meant by cloud storage", "6 Explain the advantages and disadvantages of storing data on the cloud in comparison to storing it locally"]'::jsonb,2),
    ('3','3.4','Network hardware','["1 Understand that a computer needs a network interface card (NIC) to access a network 2 Understand what is meant by, and the purpose of, a media access control (MAC) address, including its structure", "3 (a) Understand what is meant by, and the purpose of, an internet protocol (IP) address (b) Understand that there are different types of IP address 4 Describe the role of a router in a network"]'::jsonb,3),
    ('4','4.1','Types of software and interrupts','["1 Describe the difference between system software and application software and provide examples of each", "2 Describe the role and basic functions of an operating system", "3 Understand how hardware, firmware and an operating system are required to run applications software", "4 Describe the role and operation of interrupts"]'::jsonb,0),
    ('4','4.2','Types of programming language, translators and integrated development environments','["(IDEs)", "1 Explain what is meant by a high-level language and a low-level language, including the advantages and disadvantages of each", "2 Understand that assembly language is a form of low-level language that uses mnemonics, and that an assembler is needed to translate an assembly language program into machine code 3 Describe the operation of a compiler and an interpreter, including how high-level language is translated by each and how errors are reported", "(IDEs) continued", "4 Explain the advantages and disadvantages of a compiler and an interpreter", "5 Explain the role of an IDE in writing program code and the common functions IDEs provide"]'::jsonb,1),
    ('5','5.1','The internet and the world wide web','["1 Understand the difference between the internet and the world wide web", "2 Understand what is meant by a uniform resource locator (URL)", "3 Describe the purpose and operation of hypertext transfer protocol (HTTP) and hypertext transfer protocol secure (HTTPS) 4 Explain the purpose and functions of a web browser", "5 Describe how web pages are located, retrieved and displayed on a device when a user enters a URL", "6 Explain what is meant by cookies and how they are used, including session cookies and persistent cookies"]'::jsonb,0),
    ('5','5.2','Digital currency','["1 Understand the concept of a digital currency and how digital currencies are used 2 Understand the process of blockchain and how it is used to track digital currency transactions"]'::jsonb,1),
    ('5','5.3','Cyber security','["1 Describe the processes involved in, and the aim of carrying out, a range of cyber security threats", "2 Explain how a range of solutions are used to help keep data safe from security threats"]'::jsonb,2),
    ('6','6.1','Automated systems','["1 Describe how sensors, microprocessors and actuators can be used in collaboration to create automated systems 2 Describe the advantages and disadvantages of an automated system used for a given scenario"]'::jsonb,0),
    ('6','6.2','Robotics','["1 Understand what is meant by robotics", "2 Describe the characteristics of a robot", "3 Understand the roles that robots can perform and describe the advantages and disadvantages of their use"]'::jsonb,1),
    ('6','6.3','Artificial intelligence','["1 Understand what is meant by artificial intelligence (AI)", "2 Describe the main characteristics of AI as the collection of data and the rules for using that data, the ability to reason, and it can include the ability to learn and adapt 3 Explain the basic operation and components of AI systems to simulate intelligent behaviour", "Algorithms, programming and logic", "See section 4 for the:", "standard flowchart symbols that must be used by students when drawing flowcharts", "logic gate symbols that must be used by students when drawing logic circuits", "format in which pseudocode will appear in examinations. In Paper 2, candidates are expected to write solutions to given problems using the methods and concepts listed in topics 7 to 10. Where the solution to a problem involves coding, candidates are required to write solutions in pseudocode. Solutions written in programming code will not be awarded marks. The exception is the 15-mark scenario question. In the 15-mark scenario question, candidates are required to write solutions to the given problem using pseudocode or their choice of one of the following programming languages: Python, Visual Basic or Java. Solutions written in other programming languages will not be awarded marks."]'::jsonb,2),
    ('8','8.1','Programming concepts','["1 Declare and use variables and constants 2 Understand and use basic data types", "3 Understand and use input and output 4 (a) Understand and use the concept of sequence (b) Understand and use the concept of selection", "(c) Understand and use the concept of iteration", "(d) Understand and use the concepts of totalling and counting", "(e) Understand and use the concept of string handling", "(f) Understand and use arithmetic, relational and logical operators", "5 Understand and use nested statements", "6 (a) Understand what is meant by procedures, functions and parameters (b) Define and use procedures and functions, with or without parameters (c) Understand and use local and global variables 7 Understand and use library routines", "8 Understand how to create a maintainable program"]'::jsonb,0),
    ('8','8.2','Arrays','["1 Declare and use one-dimensional (1D) and two-dimensional (2D) arrays 2 Understand the use of arrays", "3 Write values into, and read values from, an array using iteration"]'::jsonb,1),
    ('8','8.3','File handling','["1 Understand the purpose of storing data in a file to be used by a program 2 Open, close and use a file for reading and writing"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Computer Science O Level (O1)';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O2)' AND name='Computer Science' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Computer Science O Level (O2) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','2210','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='2210', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Data representation',0),
    (v_org,v_tpl,'2','Data transmission',1),
    (v_org,v_tpl,'3','Hardware',2),
    (v_org,v_tpl,'4','Software',3),
    (v_org,v_tpl,'5','The internet and its uses',4),
    (v_org,v_tpl,'6','Automated and emerging technologies',5),
    (v_org,v_tpl,'8','Programming',6);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Number systems','["1 Understand how and why computers use binary to represent all forms of data", "2 (a) Understand the denary, binary and hexadecimal number systems", "(b) Convert between (i) positive denary and positive binary (ii) positive denary and positive hexadecimal (iii) positive hexadecimal and positive binary 3 Understand how and why hexadecimal is used as a beneficial method of data representation", "4 (a) Add two positive 8-bit binary integers (b) Understand the concept of overflow and why it occurs in binary addition", "5 Perform a logical binary shift on a positive 8-bit binary integer and understand the effect this has on the positive binary integer", "6 Use the two''s complement number system to represent positive and negative 8-bit binary integers"]'::jsonb,0),
    ('1','1.2','Text, sound and images','["1 Understand how and why a computer represents text and the use of character sets, including American standard code for information interchange (ASCII) and Unicode", "2 Understand how and why a computer represents sound, including the effects of the sample rate and sample resolution", "3 Understand how and why a computer represents an image, including the effects of the resolution and colour depth"]'::jsonb,1),
    ('1','1.3','Data storage and compression','["1 Understand how data storage is measured", "2 Calculate the file size of an image file and a sound file, using information given", "3 Understand the purpose of and need for data compression", "4 Understand how files are compressed using lossy and lossless compression methods"]'::jsonb,2),
    ('2','2.1','Types and methods of data transmission','["1 (a) Understand that data is broken down into packets to be transmitted (b) Describe the structure of a packet", "(c) Describe the process of packet switching", "2 (a) Describe how data is transmitted from one device to another using different methods of data transmission", "(b) Explain the suitability of each method of data transmission, for a given scenario 3 Understand the universal serial bus (USB) interface and explain how it is used to transmit data"]'::jsonb,0),
    ('2','2.2','Methods of error detection','["1 Understand the need to check for errors after data transmission and how these errors can occur 2 Describe the processes involved in each of the following error detection methods for detecting errors in data after transmission: parity check (odd and even), checksum and echo check 3 Describe how a check digit is used to detect errors in data entry and identify examples of when a check digit is used, including international standard book numbers (ISBN) and bar codes 4 Describe how an automatic repeat query (ARQ) can be used to establish that data is received without error"]'::jsonb,1),
    ('2','2.3','Encryption','["1 Understand the need for and purpose of encryption when transmitting data 2 Understand how data is encrypted using symmetric and asymmetric encryption"]'::jsonb,2),
    ('3','3.1','Computer architecture','["1 (a) Understand the role of the central processing unit (CPU) in a computer", "(b) Understand what is meant by a microprocessor 2 (a) Understand the purpose of the components in a CPU, in a computer that has a Von Neumann architecture", "(b) Describe the process of the fetch-decode-execute (FDE) cycle, including the role of each component in the process", "3 Understand what is meant by a core, cache and clock in a CPU and explain how they can affect the performance of a CPU 4 Understand the purpose and use of an instruction set for a CPU", "5 Describe the purpose and characteristics of an embedded system and identify devices in which they are commonly used"]'::jsonb,0),
    ('3','3.2','Input and output devices','["1 Understand what is meant by an input device and why it is required", "2 Understand what is meant by an output device and why it is required", "3 (a) Understand what is meant by a sensor and the purposes of sensors", "(b) Identify the type of data captured by each sensor and understand when each sensor would be used, including selecting the most suitable sensor for a given context"]'::jsonb,1),
    ('3','3.3','Data storage','["1 Understand what is meant by primary storage", "2 Understand what is meant by secondary storage", "3 Describe the operation of magnetic, optical and solid-state (flash memory) storage and give examples of each", "4 Describe what is meant by virtual memory, how it is created and used and why it is necessary 5 Understand what is meant by cloud storage", "6 Explain the advantages and disadvantages of storing data on the cloud in comparison to storing it locally"]'::jsonb,2),
    ('3','3.4','Network hardware','["1 Understand that a computer needs a network interface card (NIC) to access a network 2 Understand what is meant by, and the purpose of, a media access control (MAC) address, including its structure", "3 (a) Understand what is meant by, and the purpose of, an internet protocol (IP) address (b) Understand that there are different types of IP address 4 Describe the role of a router in a network"]'::jsonb,3),
    ('4','4.1','Types of software and interrupts','["1 Describe the difference between system software and application software and provide examples of each", "2 Describe the role and basic functions of an operating system", "3 Understand how hardware, firmware and an operating system are required to run applications software", "4 Describe the role and operation of interrupts"]'::jsonb,0),
    ('4','4.2','Types of programming language, translators and integrated development environments','["(IDEs)", "1 Explain what is meant by a high-level language and a low-level language, including the advantages and disadvantages of each", "2 Understand that assembly language is a form of low-level language that uses mnemonics, and that an assembler is needed to translate an assembly language program into machine code 3 Describe the operation of a compiler and an interpreter, including how high-level language is translated by each and how errors are reported", "(IDEs) continued", "4 Explain the advantages and disadvantages of a compiler and an interpreter", "5 Explain the role of an IDE in writing program code and the common functions IDEs provide"]'::jsonb,1),
    ('5','5.1','The internet and the world wide web','["1 Understand the difference between the internet and the world wide web", "2 Understand what is meant by a uniform resource locator (URL)", "3 Describe the purpose and operation of hypertext transfer protocol (HTTP) and hypertext transfer protocol secure (HTTPS) 4 Explain the purpose and functions of a web browser", "5 Describe how web pages are located, retrieved and displayed on a device when a user enters a URL", "6 Explain what is meant by cookies and how they are used, including session cookies and persistent cookies"]'::jsonb,0),
    ('5','5.2','Digital currency','["1 Understand the concept of a digital currency and how digital currencies are used 2 Understand the process of blockchain and how it is used to track digital currency transactions"]'::jsonb,1),
    ('5','5.3','Cyber security','["1 Describe the processes involved in, and the aim of carrying out, a range of cyber security threats", "2 Explain how a range of solutions are used to help keep data safe from security threats"]'::jsonb,2),
    ('6','6.1','Automated systems','["1 Describe how sensors, microprocessors and actuators can be used in collaboration to create automated systems 2 Describe the advantages and disadvantages of an automated system used for a given scenario"]'::jsonb,0),
    ('6','6.2','Robotics','["1 Understand what is meant by robotics", "2 Describe the characteristics of a robot", "3 Understand the roles that robots can perform and describe the advantages and disadvantages of their use"]'::jsonb,1),
    ('6','6.3','Artificial intelligence','["1 Understand what is meant by artificial intelligence (AI)", "2 Describe the main characteristics of AI as the collection of data and the rules for using that data, the ability to reason, and it can include the ability to learn and adapt 3 Explain the basic operation and components of AI systems to simulate intelligent behaviour", "Algorithms, programming and logic", "See section 4 for the:", "standard flowchart symbols that must be used by students when drawing flowcharts", "logic gate symbols that must be used by students when drawing logic circuits", "format in which pseudocode will appear in examinations. In Paper 2, candidates are expected to write solutions to given problems using the methods and concepts listed in topics 7 to 10. Where the solution to a problem involves coding, candidates are required to write solutions in pseudocode. Solutions written in programming code will not be awarded marks. The exception is the 15-mark scenario question. In the 15-mark scenario question, candidates are required to write solutions to the given problem using pseudocode or their choice of one of the following programming languages: Python, Visual Basic or Java. Solutions written in other programming languages will not be awarded marks."]'::jsonb,2),
    ('8','8.1','Programming concepts','["1 Declare and use variables and constants 2 Understand and use basic data types", "3 Understand and use input and output 4 (a) Understand and use the concept of sequence (b) Understand and use the concept of selection", "(c) Understand and use the concept of iteration", "(d) Understand and use the concepts of totalling and counting", "(e) Understand and use the concept of string handling", "(f) Understand and use arithmetic, relational and logical operators", "5 Understand and use nested statements", "6 (a) Understand what is meant by procedures, functions and parameters (b) Define and use procedures and functions, with or without parameters (c) Understand and use local and global variables 7 Understand and use library routines", "8 Understand how to create a maintainable program"]'::jsonb,0),
    ('8','8.2','Arrays','["1 Declare and use one-dimensional (1D) and two-dimensional (2D) arrays 2 Understand the use of arrays", "3 Write values into, and read values from, an array using iteration"]'::jsonb,1),
    ('8','8.3','File handling','["1 Understand the purpose of storing data in a file to be used by a program 2 Open, close and use a file for reading and writing"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Computer Science O Level (O2)';
END $$;
