-- Commerce (7100) - Cambridge O Level outline with objectives, loaded into O1 + O2.

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O1)' AND name='Commerce' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Commerce O Level (O1) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','7100','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='7100', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Commerce and production',0),
    (v_org,v_tpl,'2','Commercial operations',1),
    (v_org,v_tpl,'3','Globalisation of trade',2),
    (v_org,v_tpl,'4','Logistics in commerce',3),
    (v_org,v_tpl,'5','Aids to trade that support commerce',4),
    (v_org,v_tpl,'6','Sustainability and ethics',5);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Trade and commerce','["1.1.1 Trade", "the meaning of the terms trade and commerce, showing the differences between the two terms", "the meaning of home trade (retail and wholesale)", "the meaning of international trade (exports and imports) 1.1.2 Aids to trade and logistics", "the meaning of aids to trade", "the types of aids to trade: communications, transport, warehousing, advertising, banking and insurance", "the meaning of logistics", "the elements of logistics in a supply chain: transport, freight forwarders and warehousing 1.1.3 Types of commerce", "the meaning of traditional commerce: buying and selling goods and/or services at a physical location", "the meaning of ecommerce (electronic commerce): buying and selling goods and/or services via the internet/websites", "the meaning of mcommerce (mobile commerce): buying and selling goods and/or services via a mobile device, such as a smartphone or tablet", "the meaning of scommerce (social commerce): buying and selling goods and/or services via social media channels 1.1.4 The relationship between production, trade and commerce", "understand how production, trade and commerce are interdependent"]'::jsonb,0),
    ('1','1.2','Production','["1.2.1 Sectors of production and specialisation", "the features of primary (extractive) industries, secondary (manufacturing and construction) industries, tertiary activities (commercial services and direct services) and quaternary activities (digital technology)", "the meaning of specialisation", "the advantages and disadvantages of specialisation for an individual, factory and country 1.2.2 In-house production and outsourced production", "the meaning of in-house production and outsourced production", "the benefits of in-house production over outsourced production, including control on quality and information", "the benefits of outsourced production over in-house production, including accessing expertise and cost savings 1.2.3 Global supply chains", "the meaning of a global supply chain and a domestic supply chain 1.2.4 Intermediaries in a supply chain", "the role of home trade intermediaries in a supply chain: wholesaler and retailer", "the role of international trade intermediaries in a supply chain: agent and factor 1.2.5 Effects of digital technology on production", "the impact of automation, e.g. using robotics in production", "the impact on production of digital communication with suppliers, e.g. using electronic data interchange (EDI) 1.2.6 Costs involved in trade, commerce and production", "identifying the different types of costs used in trade, commerce and production: advertising, bank charges, commission, customs duties, inventory, labour, packaging, transport, utilities and warehousing", "complete simple calculations of costs in given situations"]'::jsonb,1),
    ('2','2.1','Commercial enterprises','["2.1.1 Private and public sector enterprises", "the difference between private and public sector enterprises 2.1.2 Types of private and public sector enterprises", "the features of private sector enterprises: sole trader, cooperative, partnership, private limited company and public limited company", "the features of public corporations", "the reasons for public corporations", "the appropriateness of different types of ownership in given situations 2.1.3 Multinational companies (MNCs) in the global economy", "the features of multinational companies", "the reasons for the existence of multinational companies in the global economy", "the positive and negative impacts on a country of multinational companies locating in the country 2.1.4 Franchises", "the features of franchises", "the advantages and disadvantages of franchises 2.1.5 Physical and ecommerce location factors", "the physical location factors: labour, markets, transport, power, raw materials, competition, suppliers, communication and government influence", "the ecommerce location factors: wi-fi, warehousing, technology specialists, and logistics", "the appropriateness of physical and ecommerce location factors in given situations"]'::jsonb,0),
    ('2','2.2','Outsourcing','["2.2.1 Growth of outsourcing", "the growth of outsourcing: contract manufacturing and logistics"]'::jsonb,1),
    ('2','2.3','Retailing','["2.3.1 Types of retailers", "the different types of small-scale and large-scale retailers: itinerant retailers, vending machines, independent retailers, street markets, speciality shops, online retailers, multiple chain stores, supermarkets, hypermarkets and department stores", "the features of each type of retailer", "the advantages and disadvantages of each type of retailer", "reasons why the small-scale retailer often survives, e.g. personal service, flexible opening hours and additional services provided 2.3.2 Retail selling techniques", "the different types of retail selling techniques: branding, own brands, logos, packaging, self service, after-sales service, barcoding, direct mail, loyalty programmes, informal credit and cash on delivery 2.3.3 Digital retail trends", "the different types of digital retail trends: omnichannel retailing, cashless stores, Electronic Point of Sale (EPoS), click and collect, self-service checkouts, subscription commerce, QR codes, Virtual Reality (VR) showrooms, dropshipping, mobile phone/smartphone apps and multi-channel retailing 2.3.4 Effects of ecommerce on traditional commerce", "the positive impacts of ecommerce on traditional commerce, e.g. 24/7 selling opportunities, more potential customers, increased revenue, targeted marketing and reduced operating store costs", "the negative impacts of ecommerce on traditional commerce, e.g. increased costs (delivery, staff training and larger warehousing space) and website maintenance"]'::jsonb,2),
    ('2','2.4','Wholesaling','["2.4.1 Functions and importance of the wholesaler", "the functions and services provided by the wholesaler", "the importance of the wholesaler to the manufacturer and retailer", "reasons why the independent wholesaler survives: cash and carry and voluntary chains"]'::jsonb,3),
    ('2','2.5','Trading documents','["2.5.1 Documents of home trade", "different types of documents used in home trade: enquiry, quotation, order, invoice, delivery note, credit note, statement of account and receipt", "2.5.2 Documents of international trade", "different types of documents used in international trade: certificate of origin, bill of lading, air waybill and documentary credit (letters of credit) 2.5.3 Digital use of trading documents", "the stages of the online ordering process: from buyer browsing website to receiving order", "identifying digital technology in trading documents, e.g. digital signatures, secure access, cloud-based storage, electronic receipts and etickets"]'::jsonb,4),
    ('2','2.6','Communication','["2.6.1 Types of communication", "the distinction between different types of communication: written, oral, electronic and visual communication 2.6.2 Methods of communication", "the different methods of communication: letter, telephone, face to face, videoconferencing, email, web-based chat (including chatbots), social media and posters 2.6.3 Factors that affect communication", "the appropriateness of factors affecting choice of method of communication in given situations: urgency, cost, security, distance, availability of networks and importance of the message"]'::jsonb,5),
    ('3','3.1','International trade','["3.1.1 Benefits of international trade to a country", "the benefits of international trade to a country: wider choice of goods, higher standard of living, lower cost of imports, more investment and creation of jobs 3.1.2 Challenges of international trade to exporters and importers", "the challenges of international trade to exporters and importers: distance, language, methods of payment, documentation, transport, customs duties, non-payment, currencies, foreign exchange rates, competition and different legal systems", "3.1.3 Balance of Trade and Balance of Payments", "the difference between Balance of Trade and Balance of Payments", "calculation and interpretation of Balance of Trade and Balance of Payments from given figures", "how commercial activities affect the Balance of Trade and Balance of Payments 3.1.4 Free trade, trading blocs, trade restrictions and sources of support for exporters", "the meaning of free trade", "the features of a trading bloc", "the advantages and disadvantages of joining a trading bloc", "the types of trade restrictions: tariffs, quotas and embargoes", "the potential effects of trade restrictions on commercial activities", "the sources of support for exporters: international trade fairs, cheaper bank loans and insurance guarantees"]'::jsonb,0),
    ('3','3.2','Global supply chain management','["3.2.1 Global supply chains", "the different types of global supply chains: simple supply chain (supplier to manufacturer to consumer) and complex supply chains (supplier to agent to wholesaler to retailer to consumer)", "the features of global supply chain management: upstream, the enterprise and downstream", "the importance of suppliers in the global supply chain", "the benefits of global supply chain management: lower cost of production, lower labour costs, lower cost of purchasing, advancement in logistics and communication 3.2.2 Global supply chain risks", "the risks to global supply chains: environmental (e.g. pollution, deforestation), natural disasters, financial, ethical, technological and political risks", "the importance of risk assessment in the global supply chain"]'::jsonb,1),
    ('4','4.1','Transport','["the three functions of transport in the supply chain: time, place and quantity", "the types and methods of transport: - road: delivery vans, trucks, couriers - rail: freight trains - air: freight planes - sea: ferry, tanker, container ship, cargo liner - pipeline", "the advantages and disadvantages of different methods of transport", "the appropriateness of factors affecting choice of method of transport in given situations: nature of goods, urgency, cost, security, distance and reliability of transporter", "the features of containerisation, including transshipment", "the advantages and disadvantages of containerisation"]'::jsonb,0),
    ('4','4.2','Warehousing','["the functions of warehousing in the supply chain: links with seasonal production, demand, protecting supply and price stability and logistics postponement", "the different types of warehouse: bonded, cold storage, cash and carry and regional distribution centres (RDCs)", "the uses of automation in warehousing: robotics, automated sorting and voice picking", "the benefits of warehouse automation: lower labour costs, less human error, improved picking accuracy, improved inventory control and improved customer service"]'::jsonb,1),
    ('5','5.1','Advertising','["5.1.1 Types of advertising", "the purposes of advertising", "the types of advertising: informative, persuasive, collective (generic) and competitive", "the advantages and disadvantages of the different types of advertising", "5.1.2 Methods of traditional and digital advertising media", "the methods of traditional advertising media: television, radio, cinema, newspapers (local and national), magazines/trade journals, leaflets/flyers, packaging, direct mail, sponsorship, catalogues/brochures, posters, transport vehicles, window displays, point of sale displays, signboards and word of mouth", "the methods of digital advertising media: social media advertising and other internet advertising (including websites, search engines), display advertisements, video advertisements, email marketing, digital billboards and social media influencers", "the advantages and disadvantages of different methods of traditional and digital media for advertising campaigns", "the appropriateness of the factors affecting choice of method of advertising in given situations: audience, cost, cultural and legal considerations, flexibility to change, local and international market coverage, multi-channel advertising, timing and type of product 5.1.3 Methods of appeal used in advertising", "the different types of methods of appeal used in advertising: emotion, fear, humour, rational, ambition, social acceptance, romantic, adventure, music, endorsement by celebrities and social media influencers", "the appropriateness of methods of appeal used in advertising in given situations 5.1.4 Sales promotion", "the meaning of sales promotion", "the methods of sales promotion: point of sale, special offers, sponsorship, displays, competitions, coupons, sales periods, loss leaders, free gifts and free samples", "the factors affecting choice of sales promotion methods in given situations: business type, competitors, cost, nature of product, new/old product and timing"]'::jsonb,0),
    ('5','5.2','Banking','["5.2.1 Banking services", "the different types of banking services: - accounts: current and deposit/savings - customer services: ATM, night safe, foreign currency, financial advice and telephone banking - payments: cash, cheque, credit card, debit card, store card, credit transfer, standing order, direct debit, electronic transfer and documentary credit (letter of credit) - sources of finance: loan, overdraft, mortgage and hire purchase", "the appropriateness of choosing banking services in given situations 5.2.2 Digital technology in banking", "the different types of digital banking: internet banking and mobile banking", "the advantages and disadvantages of digital banking", "the impact of digital banking: closure of bank branches, more digital-only banks and less use of cash (cashless society)"]'::jsonb,1),
    ('5','5.3','Insurance','["5.3.1 Purposes of insurance", "the purposes of insurance: risk reduction, compensation, financial protection, business confidence and investment 5.3.2 Types of insurance risk", "the different types of insurance risk: consequential loss, employer''s liability, fire, motor, premises, public liability and theft 5.3.3 How enterprises make use of insurance", "the use of pooling of insurance risk", "the calculation of insurance premiums", "the use of insurance documents: proposal form, cover note and policy", "the role of an insurance broker"]'::jsonb,2),
    ('5','5.4','Sources of finance and commercial performance','["5.4.1 Ways in which entrepreneurs and commercial enterprises raise finance", "the meaning of entrepreneurship", "the sources of short-term finance: trade credit, debt factoring, hire purchase, leasing, sale and leaseback, overdraft, selling assets, owner''s savings and retained profit", "the sources of long-term finance: ordinary and preference shares, loans, debentures, venture capital and crowdfunding", "the advantages and disadvantages of each source of finance", "the appropriateness of choice of source of finance in given situations", "the meaning and use of financial terms: sales, revenue, profit, working capital, assets and liabilities, interest, capital, cash discounts and trade discounts", "5.4.2 Commercial calculations", "the calculation of revenue, gross profit, gross profit margin, profit for the year (net profit), working capital and mark-up percentage = Selling price per unit × Number of units sold 1 Revenue (Sales or Turnover) 2 Gross profit = Revenue - Cost of Sales (the cost of purchasing inventory) = Gross profit ÷ Revenue × 100 3 Gross profit margin (%) 4 Net profit/net loss for the year = Gross profit - Expenses 5 Working capital Current assets - Current liabilities = (Average Selling Price - Unit Cost) ÷ Unit Cost 6 Mark-up percentage 5.4.3 Improving commercial performance", "the methods to improve sales turnover, profit, mark-up and working capital, e.g. reducing expenses, increasing mark-up, changing prices, improving advertising, introducing new products in given situations"]'::jsonb,3),
    ('6','6.1','Sustainability','["6.1.1 Purpose of sustainability in the supply chain", "the purpose of sustainability in the supply chain: making commercial processes eco-friendly and environmentally responsible for future generations 6.1.2 Actions to improve sustainability", "actions to improve sustainability: using sustainable materials in the production process, implementing sustainable logistics, reducing packaging, selling eco-friendly products, recycling and reducing waste, reducing the need for returns and exchanges, offering digital resale marketplaces, offering free repair services and water stewardship"]'::jsonb,0),
    ('6','6.2','Ethics','["6.2.1 Ethics and ethical issues in commerce", "the meaning of ethics", "the role of fair trade in commerce", "ethical issues in commerce: misleading advertising and harmful disposal of products"]'::jsonb,1),
    ('6','6.3','Consumer protection','["the reasons for consumer protection", "the actions taken by buyers and sellers to resolve consumer protection complaints"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Commerce O Level (O1)';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O2)' AND name='Commerce' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Commerce O Level (O2) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','7100','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='7100', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Commerce and production',0),
    (v_org,v_tpl,'2','Commercial operations',1),
    (v_org,v_tpl,'3','Globalisation of trade',2),
    (v_org,v_tpl,'4','Logistics in commerce',3),
    (v_org,v_tpl,'5','Aids to trade that support commerce',4),
    (v_org,v_tpl,'6','Sustainability and ethics',5);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Trade and commerce','["1.1.1 Trade", "the meaning of the terms trade and commerce, showing the differences between the two terms", "the meaning of home trade (retail and wholesale)", "the meaning of international trade (exports and imports) 1.1.2 Aids to trade and logistics", "the meaning of aids to trade", "the types of aids to trade: communications, transport, warehousing, advertising, banking and insurance", "the meaning of logistics", "the elements of logistics in a supply chain: transport, freight forwarders and warehousing 1.1.3 Types of commerce", "the meaning of traditional commerce: buying and selling goods and/or services at a physical location", "the meaning of ecommerce (electronic commerce): buying and selling goods and/or services via the internet/websites", "the meaning of mcommerce (mobile commerce): buying and selling goods and/or services via a mobile device, such as a smartphone or tablet", "the meaning of scommerce (social commerce): buying and selling goods and/or services via social media channels 1.1.4 The relationship between production, trade and commerce", "understand how production, trade and commerce are interdependent"]'::jsonb,0),
    ('1','1.2','Production','["1.2.1 Sectors of production and specialisation", "the features of primary (extractive) industries, secondary (manufacturing and construction) industries, tertiary activities (commercial services and direct services) and quaternary activities (digital technology)", "the meaning of specialisation", "the advantages and disadvantages of specialisation for an individual, factory and country 1.2.2 In-house production and outsourced production", "the meaning of in-house production and outsourced production", "the benefits of in-house production over outsourced production, including control on quality and information", "the benefits of outsourced production over in-house production, including accessing expertise and cost savings 1.2.3 Global supply chains", "the meaning of a global supply chain and a domestic supply chain 1.2.4 Intermediaries in a supply chain", "the role of home trade intermediaries in a supply chain: wholesaler and retailer", "the role of international trade intermediaries in a supply chain: agent and factor 1.2.5 Effects of digital technology on production", "the impact of automation, e.g. using robotics in production", "the impact on production of digital communication with suppliers, e.g. using electronic data interchange (EDI) 1.2.6 Costs involved in trade, commerce and production", "identifying the different types of costs used in trade, commerce and production: advertising, bank charges, commission, customs duties, inventory, labour, packaging, transport, utilities and warehousing", "complete simple calculations of costs in given situations"]'::jsonb,1),
    ('2','2.1','Commercial enterprises','["2.1.1 Private and public sector enterprises", "the difference between private and public sector enterprises 2.1.2 Types of private and public sector enterprises", "the features of private sector enterprises: sole trader, cooperative, partnership, private limited company and public limited company", "the features of public corporations", "the reasons for public corporations", "the appropriateness of different types of ownership in given situations 2.1.3 Multinational companies (MNCs) in the global economy", "the features of multinational companies", "the reasons for the existence of multinational companies in the global economy", "the positive and negative impacts on a country of multinational companies locating in the country 2.1.4 Franchises", "the features of franchises", "the advantages and disadvantages of franchises 2.1.5 Physical and ecommerce location factors", "the physical location factors: labour, markets, transport, power, raw materials, competition, suppliers, communication and government influence", "the ecommerce location factors: wi-fi, warehousing, technology specialists, and logistics", "the appropriateness of physical and ecommerce location factors in given situations"]'::jsonb,0),
    ('2','2.2','Outsourcing','["2.2.1 Growth of outsourcing", "the growth of outsourcing: contract manufacturing and logistics"]'::jsonb,1),
    ('2','2.3','Retailing','["2.3.1 Types of retailers", "the different types of small-scale and large-scale retailers: itinerant retailers, vending machines, independent retailers, street markets, speciality shops, online retailers, multiple chain stores, supermarkets, hypermarkets and department stores", "the features of each type of retailer", "the advantages and disadvantages of each type of retailer", "reasons why the small-scale retailer often survives, e.g. personal service, flexible opening hours and additional services provided 2.3.2 Retail selling techniques", "the different types of retail selling techniques: branding, own brands, logos, packaging, self service, after-sales service, barcoding, direct mail, loyalty programmes, informal credit and cash on delivery 2.3.3 Digital retail trends", "the different types of digital retail trends: omnichannel retailing, cashless stores, Electronic Point of Sale (EPoS), click and collect, self-service checkouts, subscription commerce, QR codes, Virtual Reality (VR) showrooms, dropshipping, mobile phone/smartphone apps and multi-channel retailing 2.3.4 Effects of ecommerce on traditional commerce", "the positive impacts of ecommerce on traditional commerce, e.g. 24/7 selling opportunities, more potential customers, increased revenue, targeted marketing and reduced operating store costs", "the negative impacts of ecommerce on traditional commerce, e.g. increased costs (delivery, staff training and larger warehousing space) and website maintenance"]'::jsonb,2),
    ('2','2.4','Wholesaling','["2.4.1 Functions and importance of the wholesaler", "the functions and services provided by the wholesaler", "the importance of the wholesaler to the manufacturer and retailer", "reasons why the independent wholesaler survives: cash and carry and voluntary chains"]'::jsonb,3),
    ('2','2.5','Trading documents','["2.5.1 Documents of home trade", "different types of documents used in home trade: enquiry, quotation, order, invoice, delivery note, credit note, statement of account and receipt", "2.5.2 Documents of international trade", "different types of documents used in international trade: certificate of origin, bill of lading, air waybill and documentary credit (letters of credit) 2.5.3 Digital use of trading documents", "the stages of the online ordering process: from buyer browsing website to receiving order", "identifying digital technology in trading documents, e.g. digital signatures, secure access, cloud-based storage, electronic receipts and etickets"]'::jsonb,4),
    ('2','2.6','Communication','["2.6.1 Types of communication", "the distinction between different types of communication: written, oral, electronic and visual communication 2.6.2 Methods of communication", "the different methods of communication: letter, telephone, face to face, videoconferencing, email, web-based chat (including chatbots), social media and posters 2.6.3 Factors that affect communication", "the appropriateness of factors affecting choice of method of communication in given situations: urgency, cost, security, distance, availability of networks and importance of the message"]'::jsonb,5),
    ('3','3.1','International trade','["3.1.1 Benefits of international trade to a country", "the benefits of international trade to a country: wider choice of goods, higher standard of living, lower cost of imports, more investment and creation of jobs 3.1.2 Challenges of international trade to exporters and importers", "the challenges of international trade to exporters and importers: distance, language, methods of payment, documentation, transport, customs duties, non-payment, currencies, foreign exchange rates, competition and different legal systems", "3.1.3 Balance of Trade and Balance of Payments", "the difference between Balance of Trade and Balance of Payments", "calculation and interpretation of Balance of Trade and Balance of Payments from given figures", "how commercial activities affect the Balance of Trade and Balance of Payments 3.1.4 Free trade, trading blocs, trade restrictions and sources of support for exporters", "the meaning of free trade", "the features of a trading bloc", "the advantages and disadvantages of joining a trading bloc", "the types of trade restrictions: tariffs, quotas and embargoes", "the potential effects of trade restrictions on commercial activities", "the sources of support for exporters: international trade fairs, cheaper bank loans and insurance guarantees"]'::jsonb,0),
    ('3','3.2','Global supply chain management','["3.2.1 Global supply chains", "the different types of global supply chains: simple supply chain (supplier to manufacturer to consumer) and complex supply chains (supplier to agent to wholesaler to retailer to consumer)", "the features of global supply chain management: upstream, the enterprise and downstream", "the importance of suppliers in the global supply chain", "the benefits of global supply chain management: lower cost of production, lower labour costs, lower cost of purchasing, advancement in logistics and communication 3.2.2 Global supply chain risks", "the risks to global supply chains: environmental (e.g. pollution, deforestation), natural disasters, financial, ethical, technological and political risks", "the importance of risk assessment in the global supply chain"]'::jsonb,1),
    ('4','4.1','Transport','["the three functions of transport in the supply chain: time, place and quantity", "the types and methods of transport: - road: delivery vans, trucks, couriers - rail: freight trains - air: freight planes - sea: ferry, tanker, container ship, cargo liner - pipeline", "the advantages and disadvantages of different methods of transport", "the appropriateness of factors affecting choice of method of transport in given situations: nature of goods, urgency, cost, security, distance and reliability of transporter", "the features of containerisation, including transshipment", "the advantages and disadvantages of containerisation"]'::jsonb,0),
    ('4','4.2','Warehousing','["the functions of warehousing in the supply chain: links with seasonal production, demand, protecting supply and price stability and logistics postponement", "the different types of warehouse: bonded, cold storage, cash and carry and regional distribution centres (RDCs)", "the uses of automation in warehousing: robotics, automated sorting and voice picking", "the benefits of warehouse automation: lower labour costs, less human error, improved picking accuracy, improved inventory control and improved customer service"]'::jsonb,1),
    ('5','5.1','Advertising','["5.1.1 Types of advertising", "the purposes of advertising", "the types of advertising: informative, persuasive, collective (generic) and competitive", "the advantages and disadvantages of the different types of advertising", "5.1.2 Methods of traditional and digital advertising media", "the methods of traditional advertising media: television, radio, cinema, newspapers (local and national), magazines/trade journals, leaflets/flyers, packaging, direct mail, sponsorship, catalogues/brochures, posters, transport vehicles, window displays, point of sale displays, signboards and word of mouth", "the methods of digital advertising media: social media advertising and other internet advertising (including websites, search engines), display advertisements, video advertisements, email marketing, digital billboards and social media influencers", "the advantages and disadvantages of different methods of traditional and digital media for advertising campaigns", "the appropriateness of the factors affecting choice of method of advertising in given situations: audience, cost, cultural and legal considerations, flexibility to change, local and international market coverage, multi-channel advertising, timing and type of product 5.1.3 Methods of appeal used in advertising", "the different types of methods of appeal used in advertising: emotion, fear, humour, rational, ambition, social acceptance, romantic, adventure, music, endorsement by celebrities and social media influencers", "the appropriateness of methods of appeal used in advertising in given situations 5.1.4 Sales promotion", "the meaning of sales promotion", "the methods of sales promotion: point of sale, special offers, sponsorship, displays, competitions, coupons, sales periods, loss leaders, free gifts and free samples", "the factors affecting choice of sales promotion methods in given situations: business type, competitors, cost, nature of product, new/old product and timing"]'::jsonb,0),
    ('5','5.2','Banking','["5.2.1 Banking services", "the different types of banking services: - accounts: current and deposit/savings - customer services: ATM, night safe, foreign currency, financial advice and telephone banking - payments: cash, cheque, credit card, debit card, store card, credit transfer, standing order, direct debit, electronic transfer and documentary credit (letter of credit) - sources of finance: loan, overdraft, mortgage and hire purchase", "the appropriateness of choosing banking services in given situations 5.2.2 Digital technology in banking", "the different types of digital banking: internet banking and mobile banking", "the advantages and disadvantages of digital banking", "the impact of digital banking: closure of bank branches, more digital-only banks and less use of cash (cashless society)"]'::jsonb,1),
    ('5','5.3','Insurance','["5.3.1 Purposes of insurance", "the purposes of insurance: risk reduction, compensation, financial protection, business confidence and investment 5.3.2 Types of insurance risk", "the different types of insurance risk: consequential loss, employer''s liability, fire, motor, premises, public liability and theft 5.3.3 How enterprises make use of insurance", "the use of pooling of insurance risk", "the calculation of insurance premiums", "the use of insurance documents: proposal form, cover note and policy", "the role of an insurance broker"]'::jsonb,2),
    ('5','5.4','Sources of finance and commercial performance','["5.4.1 Ways in which entrepreneurs and commercial enterprises raise finance", "the meaning of entrepreneurship", "the sources of short-term finance: trade credit, debt factoring, hire purchase, leasing, sale and leaseback, overdraft, selling assets, owner''s savings and retained profit", "the sources of long-term finance: ordinary and preference shares, loans, debentures, venture capital and crowdfunding", "the advantages and disadvantages of each source of finance", "the appropriateness of choice of source of finance in given situations", "the meaning and use of financial terms: sales, revenue, profit, working capital, assets and liabilities, interest, capital, cash discounts and trade discounts", "5.4.2 Commercial calculations", "the calculation of revenue, gross profit, gross profit margin, profit for the year (net profit), working capital and mark-up percentage = Selling price per unit × Number of units sold 1 Revenue (Sales or Turnover) 2 Gross profit = Revenue - Cost of Sales (the cost of purchasing inventory) = Gross profit ÷ Revenue × 100 3 Gross profit margin (%) 4 Net profit/net loss for the year = Gross profit - Expenses 5 Working capital Current assets - Current liabilities = (Average Selling Price - Unit Cost) ÷ Unit Cost 6 Mark-up percentage 5.4.3 Improving commercial performance", "the methods to improve sales turnover, profit, mark-up and working capital, e.g. reducing expenses, increasing mark-up, changing prices, improving advertising, introducing new products in given situations"]'::jsonb,3),
    ('6','6.1','Sustainability','["6.1.1 Purpose of sustainability in the supply chain", "the purpose of sustainability in the supply chain: making commercial processes eco-friendly and environmentally responsible for future generations 6.1.2 Actions to improve sustainability", "actions to improve sustainability: using sustainable materials in the production process, implementing sustainable logistics, reducing packaging, selling eco-friendly products, recycling and reducing waste, reducing the need for returns and exchanges, offering digital resale marketplaces, offering free repair services and water stewardship"]'::jsonb,0),
    ('6','6.2','Ethics','["6.2.1 Ethics and ethical issues in commerce", "the meaning of ethics", "the role of fair trade in commerce", "ethical issues in commerce: misleading advertising and harmful disposal of products"]'::jsonb,1),
    ('6','6.3','Consumer protection','["the reasons for consumer protection", "the actions taken by buyers and sellers to resolve consumer protection complaints"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Commerce O Level (O2)';
END $$;
