-- Geography (2217) - Cambridge O Level outline with objectives, loaded into O1 + O2.

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O1)' AND name='Geography' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Geography O Level (O1) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026','2217','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026', cambridge_code='2217', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Population and settlement',0),
    (v_org,v_tpl,'2','The natural environment',1),
    (v_org,v_tpl,'3','Economic development',2);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Population dynamics','["Describe and give reasons for the rapid increase in the world''s population Show an understanding of over-population and under-population Understand the main causes of a change in population size Give reasons for contrasting rates of natural population change Describe and evaluate population policies", "Case Studies required for 1.1", "A country which is over-populated", "A country which is under-populated", "A country with a high rate of natural population growth", "A country with a low rate of population growth (or population decline)"]'::jsonb,0),
    ('1','1.2','Migration','["Explain and give reasons for population migration", "Demonstrate an understanding of the impacts of migration", "Case Study required for 1.2", "An international migration"]'::jsonb,1),
    ('1','1.3','Population structure','["Identify and give reasons for and implications of different types of population structure", "Case Study required for 1.3", "A country with a high dependent population"]'::jsonb,2),
    ('1','1.4','Population density and distribution','["Describe the factors influencing the density and distribution of population", "Case Studies required for 1.4", "A densely populated country or area (at any scale from local to regional)", "A sparsely populated country or area (at any scale from local to regional)"]'::jsonb,3),
    ('1','1.5','Settlements (rural and urban) and service provision','["Explain the patterns of settlement Describe and explain the factors which may influence the sites, growth and functions of settlements Give reasons for the hierarchy of settlements and services", "Case Study required for 1.5", "Settlement and service provision in an area"]'::jsonb,4),
    ('1','1.6','Urban settlements','["Describe and give reasons for the characteristics of, and changes in, land use in urban areas", "Explain the problems of urban areas, their causes and possible solutions", "Case Study required for 1.6", "An urban area or urban areas"]'::jsonb,5),
    ('1','1.7','Urbanisation','["Identify and suggest reasons for rapid urban growth", "Describe the impacts of urban growth on both rural and urban areas, along with possible solutions to reduce the negative impacts", "Case Study required for 1.7", "A rapidly growing urban area in a developing country and migration to it"]'::jsonb,6),
    ('2','2.1','Earthquakes and volcanoes','["Describe the main types and features of volcanoes and earthquakes", "Describe and explain the distribution of earthquakes and volcanoes", "Describe the causes of earthquakes and volcanic eruptions and their effects on people and the environment Demonstrate an understanding that volcanoes present hazards and offer opportunities for people Explain what can be done to reduce the impacts of earthquakes and volcanoes", "Case Studies required for 2.1", "An earthquake.", "A volcano."]'::jsonb,0),
    ('2','2.2','Rivers','["Explain the main hydrological characteristics and processes which operate in rivers and drainage basins", "Demonstrate an understanding of the work of a river in eroding, transporting and depositing Describe and explain the formation of the landforms associated with these processes", "Demonstrate an understanding that rivers present hazards and offer opportunities for people", "Explain what can be done to manage the impacts of river flooding", "Case Study required for 2.2", "The opportunities presented by a river or rivers, the associated hazards and their management"]'::jsonb,1),
    ('2','2.3','Coasts','["Demonstrate an understanding of the work of the sea and wind in eroding, transporting and depositing Describe and explain the formation of the landforms associated with these processes", "Describe coral reefs and mangrove swamps and the conditions required for their development Demonstrate an understanding that coasts present hazards and offer opportunities for people Explain what can be done to manage the impacts of coastal erosion", "Case Study required for 2.3", "The opportunities presented by an area or areas of coastline, the associated hazards and their management"]'::jsonb,2),
    ('2','2.4','Weather','["Describe how weather data are collected", "Make calculations using information from weather instruments Use and interpret graphs and other diagrams showing weather and climate data"]'::jsonb,3),
    ('2','2.5','Climate and natural vegetation','["Describe and explain the characteristics of two climates:", "equatorial", "hot desert Describe and explain the characteristics of tropical rainforest and hot desert ecosystems Describe the causes and effects of deforestation of tropical rainforest Case Study required for 2.5", "An area of tropical rainforest", "An area of hot desert"]'::jsonb,4),
    ('3','3.1','Development','["Use a variety of indicators to assess the level of development of a country", "Identify and explain inequalities between and within countries Classify production into different sectors and give illustrations of each Describe and explain how the proportions employed in each sector vary according to the level of development Describe and explain the process of globalisation, and consider its impacts", "Case Study required for 3.1", "A transnational corporation and its global links"]'::jsonb,0),
    ('3','3.2','Food production','["Describe and explain the main features of an agricultural system: inputs, processes and outputs", "Recognise the causes and effects of food shortages and describe possible solutions to this problem", "Case Studies required for 3.2", "A farm or agricultural system", "A country or region suffering from food shortages."]'::jsonb,1),
    ('3','3.3','Industry','["Demonstrate an understanding of an industrial system: inputs, processes and outputs (products and waste) Describe and explain the factors influencing the distribution and location of factories and industrial zones", "Case Study required for 3.3", "An industrial zone or factory"]'::jsonb,2),
    ('3','3.4','Tourism','["Describe and explain the growth of tourism in relation to the main attractions of the physical and human landscape Evaluate the benefits and disadvantages of tourism to receiving areas Demonstrate an understanding that careful management of tourism is required in order for it to be sustainable", "Case Study required for 3.4", "An area where tourism is important."]'::jsonb,3),
    ('3','3.5','Energy','["Describe the importance of non-renewable fossil fuels, renewable energy supplies, nuclear power and fuelwood; globally and in different countries at different levels of development Evaluate the benefits and disadvantages of nuclear power and renewable energy sources", "Case Study required for 3.5", "Energy supply in a country or area"]'::jsonb,4),
    ('3','3.6','Water','["Describe methods of water supply and the proportions of water used for agriculture, domestic and industrial purposes in countries at different levels of economic development Explain why there are water shortages in some areas and demonstrate that careful management is required to ensure future supplies", "Case Study required for 3.6", "Water supply in a country or area."]'::jsonb,5),
    ('3','3.7','Environmental risks of economic development','["Describe how economic activities may pose threats to the natural environment and people, locally and globally Demonstrate the need for sustainable development and management Understand the importance of resource conservation", "Case Study required for 3.7", "An area where economic development is taking place and causing the environment to be at risk Using mathematical skills in geography", "add, subtract, multiply and divide", "understand map scale and the use of the scale line and representative fractions", "understand the terms mean and range", "use averages, decimals, fractions, percentages and ratios", "use standard notation, including both positive and negative indices.", "understand significant figures and use them appropriately", "recognise positive and negative relationships shown by scatter graphs", "draw and interpret graphs from given data for the types of graph listed in the syllabus", "select suitable scales and axes for graphs", "use a ruler and protractor. Calculators may be used in all examinations."]'::jsonb,6)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Geography O Level (O1)';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='O Level (O2)' AND name='Geography' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Geography O Level (O2) not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026','2217','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026', cambridge_code='2217', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Population and settlement',0),
    (v_org,v_tpl,'2','The natural environment',1),
    (v_org,v_tpl,'3','Economic development',2);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Population dynamics','["Describe and give reasons for the rapid increase in the world''s population Show an understanding of over-population and under-population Understand the main causes of a change in population size Give reasons for contrasting rates of natural population change Describe and evaluate population policies", "Case Studies required for 1.1", "A country which is over-populated", "A country which is under-populated", "A country with a high rate of natural population growth", "A country with a low rate of population growth (or population decline)"]'::jsonb,0),
    ('1','1.2','Migration','["Explain and give reasons for population migration", "Demonstrate an understanding of the impacts of migration", "Case Study required for 1.2", "An international migration"]'::jsonb,1),
    ('1','1.3','Population structure','["Identify and give reasons for and implications of different types of population structure", "Case Study required for 1.3", "A country with a high dependent population"]'::jsonb,2),
    ('1','1.4','Population density and distribution','["Describe the factors influencing the density and distribution of population", "Case Studies required for 1.4", "A densely populated country or area (at any scale from local to regional)", "A sparsely populated country or area (at any scale from local to regional)"]'::jsonb,3),
    ('1','1.5','Settlements (rural and urban) and service provision','["Explain the patterns of settlement Describe and explain the factors which may influence the sites, growth and functions of settlements Give reasons for the hierarchy of settlements and services", "Case Study required for 1.5", "Settlement and service provision in an area"]'::jsonb,4),
    ('1','1.6','Urban settlements','["Describe and give reasons for the characteristics of, and changes in, land use in urban areas", "Explain the problems of urban areas, their causes and possible solutions", "Case Study required for 1.6", "An urban area or urban areas"]'::jsonb,5),
    ('1','1.7','Urbanisation','["Identify and suggest reasons for rapid urban growth", "Describe the impacts of urban growth on both rural and urban areas, along with possible solutions to reduce the negative impacts", "Case Study required for 1.7", "A rapidly growing urban area in a developing country and migration to it"]'::jsonb,6),
    ('2','2.1','Earthquakes and volcanoes','["Describe the main types and features of volcanoes and earthquakes", "Describe and explain the distribution of earthquakes and volcanoes", "Describe the causes of earthquakes and volcanic eruptions and their effects on people and the environment Demonstrate an understanding that volcanoes present hazards and offer opportunities for people Explain what can be done to reduce the impacts of earthquakes and volcanoes", "Case Studies required for 2.1", "An earthquake.", "A volcano."]'::jsonb,0),
    ('2','2.2','Rivers','["Explain the main hydrological characteristics and processes which operate in rivers and drainage basins", "Demonstrate an understanding of the work of a river in eroding, transporting and depositing Describe and explain the formation of the landforms associated with these processes", "Demonstrate an understanding that rivers present hazards and offer opportunities for people", "Explain what can be done to manage the impacts of river flooding", "Case Study required for 2.2", "The opportunities presented by a river or rivers, the associated hazards and their management"]'::jsonb,1),
    ('2','2.3','Coasts','["Demonstrate an understanding of the work of the sea and wind in eroding, transporting and depositing Describe and explain the formation of the landforms associated with these processes", "Describe coral reefs and mangrove swamps and the conditions required for their development Demonstrate an understanding that coasts present hazards and offer opportunities for people Explain what can be done to manage the impacts of coastal erosion", "Case Study required for 2.3", "The opportunities presented by an area or areas of coastline, the associated hazards and their management"]'::jsonb,2),
    ('2','2.4','Weather','["Describe how weather data are collected", "Make calculations using information from weather instruments Use and interpret graphs and other diagrams showing weather and climate data"]'::jsonb,3),
    ('2','2.5','Climate and natural vegetation','["Describe and explain the characteristics of two climates:", "equatorial", "hot desert Describe and explain the characteristics of tropical rainforest and hot desert ecosystems Describe the causes and effects of deforestation of tropical rainforest Case Study required for 2.5", "An area of tropical rainforest", "An area of hot desert"]'::jsonb,4),
    ('3','3.1','Development','["Use a variety of indicators to assess the level of development of a country", "Identify and explain inequalities between and within countries Classify production into different sectors and give illustrations of each Describe and explain how the proportions employed in each sector vary according to the level of development Describe and explain the process of globalisation, and consider its impacts", "Case Study required for 3.1", "A transnational corporation and its global links"]'::jsonb,0),
    ('3','3.2','Food production','["Describe and explain the main features of an agricultural system: inputs, processes and outputs", "Recognise the causes and effects of food shortages and describe possible solutions to this problem", "Case Studies required for 3.2", "A farm or agricultural system", "A country or region suffering from food shortages."]'::jsonb,1),
    ('3','3.3','Industry','["Demonstrate an understanding of an industrial system: inputs, processes and outputs (products and waste) Describe and explain the factors influencing the distribution and location of factories and industrial zones", "Case Study required for 3.3", "An industrial zone or factory"]'::jsonb,2),
    ('3','3.4','Tourism','["Describe and explain the growth of tourism in relation to the main attractions of the physical and human landscape Evaluate the benefits and disadvantages of tourism to receiving areas Demonstrate an understanding that careful management of tourism is required in order for it to be sustainable", "Case Study required for 3.4", "An area where tourism is important."]'::jsonb,3),
    ('3','3.5','Energy','["Describe the importance of non-renewable fossil fuels, renewable energy supplies, nuclear power and fuelwood; globally and in different countries at different levels of development Evaluate the benefits and disadvantages of nuclear power and renewable energy sources", "Case Study required for 3.5", "Energy supply in a country or area"]'::jsonb,4),
    ('3','3.6','Water','["Describe methods of water supply and the proportions of water used for agriculture, domestic and industrial purposes in countries at different levels of economic development Explain why there are water shortages in some areas and demonstrate that careful management is required to ensure future supplies", "Case Study required for 3.6", "Water supply in a country or area."]'::jsonb,5),
    ('3','3.7','Environmental risks of economic development','["Describe how economic activities may pose threats to the natural environment and people, locally and globally Demonstrate the need for sustainable development and management Understand the importance of resource conservation", "Case Study required for 3.7", "An area where economic development is taking place and causing the environment to be at risk Using mathematical skills in geography", "add, subtract, multiply and divide", "understand map scale and the use of the scale line and representative fractions", "understand the terms mean and range", "use averages, decimals, fractions, percentages and ratios", "use standard notation, including both positive and negative indices.", "understand significant figures and use them appropriately", "recognise positive and negative relationships shown by scatter graphs", "draw and interpret graphs from given data for the types of graph listed in the syllabus", "select suitable scales and axes for graphs", "use a ruler and protractor. Calculators may be used in all examinations."]'::jsonb,6)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Geography O Level (O2)';
END $$;
