-- Business (9609) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Business' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Business AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','9609','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='9609', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1.1','Enterprise',0),
    (v_org,v_tpl,'1.2','Business structure',1),
    (v_org,v_tpl,'1.3','Size of business',2),
    (v_org,v_tpl,'1.4','Business objectives',3),
    (v_org,v_tpl,'1.5','Stakeholders in a business',4),
    (v_org,v_tpl,'2.1','Human resource management (HRM)',5),
    (v_org,v_tpl,'2.2','Motivation',6),
    (v_org,v_tpl,'2.3','Management',7),
    (v_org,v_tpl,'3.1','The nature of marketing',8),
    (v_org,v_tpl,'3.2','Market research',9),
    (v_org,v_tpl,'3.3','The marketing mix',10),
    (v_org,v_tpl,'4.1','The nature of operations',11),
    (v_org,v_tpl,'4.2','Inventory management',12),
    (v_org,v_tpl,'4.3','Capacity utilisation and outsourcing',13),
    (v_org,v_tpl,'5.1','Business finance',14),
    (v_org,v_tpl,'5.2','Sources of finance',15),
    (v_org,v_tpl,'5.3','Forecasting and managing cash flows',16),
    (v_org,v_tpl,'5.4','Costs',17),
    (v_org,v_tpl,'5.5','Budgets',18);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1.1','1.1.1','The nature of business activity','["the purpose of business activity", "the factors of production needed for business activity: land, labour, capital and enterprise", "the concept of adding value", "the nature of economic activity, the problem of choice and opportunity cost", "the dynamic business environment", "why businesses succeed or fail", "differences between local, national, international and multinational businesses"]'::jsonb,0),
    ('1.1','1.1.2','The role of entrepreneurs and intrapreneurs','["the qualities entrepreneurs and intrapreneurs need for success", "the role of entrepreneurship in creating and starting up a business", "the role of intrapreneurship in the ongoing success of a business", "barriers to entrepreneurship", "business risk and uncertainty", "the role of business enterprise in the development of a country Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 14 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('1.1','1.1.3','Business plans','["the meaning and purpose of business plans", "the key elements of business plans", "the benefits and limitations of business plans"]'::jsonb,2),
    ('1.2','1.2.1','Economic sectors','["the primary, secondary, tertiary and quaternary sectors and businesses within those sectors", "the public and private sectors and businesses within those sectors", "the reasons for and consequences of the changing relative importance of these sectors"]'::jsonb,0),
    ('1.2','1.2.2','Business ownership','["the main features of different types of business ownership: sole traders, partnerships, private limited companies, public limited companies, franchises, co-operatives, joint ventures and social enterprises", "the appropriateness of different types of business ownership", "the concepts of unlimited liability and limited liability and their importance", "the advantages and disadvantages of changing from one type of business ownership to another"]'::jsonb,1),
    ('1.3','1.3.1','Measurements of business size','["the appropriateness of different methods of measuring the size of a business"]'::jsonb,0),
    ('1.3','1.3.2','Significance of small businesses','["the advantages and disadvantages of being a small business", "the strengths and weaknesses of family businesses", "the importance of small businesses and their role in the economy", "the role of small businesses as part of the industrial structure in some industries"]'::jsonb,1),
    ('1.3','1.3.3','Business growth','["why and how a business might grow internally (organic growth)", "the different types of external growth through merger and takeover: horizontal, vertical (backward and forward), conglomerate diversification, friendly merger, hostile takeover", "the impact of a merger/takeover on stakeholders", "why a merger/takeover may or may not achieve objectives", "the importance of joint ventures and strategic alliances as methods of external growth Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 15 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('1.4','1.4.1','Business objectives in the private sector and public sector','["the objectives of businesses - private sector, public sector, and social enterprises", "the importance of business objectives", "corporate social responsibility (CSR) and the triple bottom line - economic (financial), social and environmental objectives", "the relationship between mission statement, aims, objectives, strategy and tactics"]'::jsonb,0),
    ('1.4','1.4.2','Objectives and business decisions','["the different stages of business decision-making and the role of objectives in the stages of business decision-making", "how objectives might change over time", "the translation of objectives into targets and budgets", "the need for communication of objectives and their likely impact on the workforce", "SMART (specific, measurable, achievable, realistic, time-limited) objectives", "how ethics may influence business objectives and activities"]'::jsonb,1),
    ('1.5','1.5.1','Business stakeholders','["individuals or groups with an interest in the activities of a business", "internal stakeholders and external stakeholders", "the roles, rights and responsibilities of stakeholders"]'::jsonb,0),
    ('1.5','1.5.2','The relative importance and infuence of stakeholders on business activities','["the impact of business decisions on stakeholders, and their reactions", "the impact of stakeholder aims on business decisions", "how and why a business needs to be accountable to its stakeholders", "how conflict might arise from stakeholders having different aims and objectives", "how changing business objectives might affect its stakeholders Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 16 www.cambridgeinternational.org/alevel Back to contents page Human resource management (AS Level) The focus of this topic is on how a business can effectively manage its workforce to achieve its objectives. Candidates will develop an understanding of the human resource management process from planning and recruiting workers through to their dismissal. Candidates will learn about motivation in management. They will learn about the theory behind motivation as well as how to implement it in practice."]'::jsonb,1),
    ('2.1','2.1.1','Purpose and roles of HRM','["the role of HRM in meeting organisational objectives"]'::jsonb,0),
    ('2.1','2.1.2','Workforce planning','["the reasons for and role of a workforce plan", "measurement of labour turnover", "the implications of high and low labour turnover for a business"]'::jsonb,1),
    ('2.1','2.1.3','Recruitment and selection','["recruitment of employees: process (job descriptions and person specifications) and recruitment methods (job advertisements, employment agencies, online recruitment)", "internal and external recruitment", "selection methods: curriculum vitae, résumé, application forms, interviews, references, testing, assessment centres", "employment contracts"]'::jsonb,2),
    ('2.1','2.1.4','Redundancy and dismissal','["the difference between redundancy (voluntary and involuntary) and dismissal (fair, unfair)"]'::jsonb,3),
    ('2.1','2.1.5','Morale and welfare','["the relationship between HRM, employee morale and welfare in a business including the concept of work-life balance", "the impact of diversity and equality in the workplace on a business"]'::jsonb,4),
    ('2.1','2.1.6','Training and development','["different types of training: induction, on-the-job, off-the-job", "the impact of training and development on a business", "employee development to encourage intrapreneurship", "employee development to encourage multi-skilling and flexibility Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 17 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,5),
    ('2.1','2.1.7','Management and workforce relations','["how cooperation between management and the workforce can be of benefit to both", "the impact on employers and employees of trade union involvement in the workplace including their role in collective bargaining"]'::jsonb,6),
    ('2.2','2.2.1','Motivation as a tool of management and leadership','["the need to motivate employees to achieve the objectives of a business"]'::jsonb,0),
    ('2.2','2.2.2','Human needs','["a simple explanation of human need", "how human needs may or may not be satisfied at work"]'::jsonb,1),
    ('2.2','2.2.3','Motivation theories','["the ideas of the main content theories (Taylor, Mayo, Maslow, Herzberg and McClelland) and process theory (Vroom)"]'::jsonb,2),
    ('2.2','2.2.4','Motivation methods in practice: financial motivators, non-financial motivators','["the theories in practical situations", "different payment methods: time based, salary, piece rates, commission, bonuses, profit sharing, performance-related pay, fringe benefits", "different types of non-financial motivators: training, opportunities for promotion, development, status, job re-design, team working, empowerment, participation, job enrichment", "ways in which employees can participate in the management and control of business activity"]'::jsonb,3),
    ('2.3','2.3.1','Management and managers','["traditional manager functions: planning, organising, directing, controlling", "the role of managers: Fayol, Mintzberg", "the contribution of managers to business performance", "management styles: autocratic, democratic, laissez-faire, paternalistic", "McGregor''s Theory X and Theory Y managers Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 18 www.cambridgeinternational.org/alevel Back to contents page Marketing (AS Level) The focus of this topic is on how a business finds out the needs of potential customers, and provides for their needs. Candidates will develop an understanding of the marketing mix. Candidates will have the opportunity to study in further depth one or more of the elements of the marketing mix, and to develop the skills to be able to recommend a suitable marketing mix for a business in a specific context."]'::jsonb,0),
    ('3.1','3.1.1','The role of marketing and its relationship with other business activities','["marketing objectives", "the link between marketing objectives and corporate objectives"]'::jsonb,0),
    ('3.1','3.1.2','Demand and supply','["the factors influencing the demand for and supply of the products of a business", "interactions between demand, supply and price"]'::jsonb,1),
    ('3.1','3.1.3','Markets','["how markets may differ: consumer and industrial markets; local, national and international markets", "the difference between product orientation and customer (market) orientation", "measurement of market share and market growth", "the implications of changes in market share and market growth"]'::jsonb,2),
    ('3.1','3.1.4','Consumer and industrial marketing','["the classification of products", "how marketing might differ for consumer products (B2C - business to consumer) and industrial products (B2B - business to business)"]'::jsonb,3),
    ('3.1','3.1.5','Mass marketing and niche marketing','["the features of mass and niche markets", "the advantages and disadvantages of mass marketing and niche marketing"]'::jsonb,4),
    ('3.1','3.1.6','Market segmentation','["methods of market segmentation: geographic, demographic and psychographic", "the advantages and disadvantages of market segmentation"]'::jsonb,5),
    ('3.1','3.1.7','Customer relationship marketing (CRM)','["the aims of CRM", "the costs and benefits of CRM Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 19 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,6),
    ('3.2','3.2.1','The purposes of market research','["identification of main features of a market: size, growth, competitors", "identification of customer and consumer characteristics, profiles, wants and needs"]'::jsonb,0),
    ('3.2','3.2.2','Primary research and secondary research','["the distinction between primary research and secondary research, and the main features of each", "usefulness of data collected using primary research methods", "usefulness of data collected from secondary research sources"]'::jsonb,1),
    ('3.2','3.2.3','Sampling','["the need for and limitations of sampling"]'::jsonb,2),
    ('3.2','3.2.4','Market research data','["the reliability of the data collected", "analysis of quantitative and qualitative data", "interpretation of information presented in tables, charts and graphs"]'::jsonb,3),
    ('3.3','3.3.1','The elements of the marketing mix (the 4Ps)','["the 4Ps: Product, Price, Promotion, Place (distribution channels)"]'::jsonb,0),
    ('3.3','3.3.2','Product','["the difference between goods and services", "tangible and intangible attributes of products", "the importance of product development", "product differentiation and unique selling point (USP)"]'::jsonb,1),
    ('3.3','3.3.3','Product portfolio analysis','["product life cycle and decisions about extension strategies", "Boston Matrix analysis and its uses", "impact of product portfolio analysis on marketing decisions Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 20 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('3.3','3.3.4','Pricing methods','["objectives and usefulness of different pricing methods: competitive, penetration, skimming, price discrimination, dynamic, cost-based and psychological"]'::jsonb,3),
    ('3.3','3.3.5','Promotion methods','["the objectives and usefulness of different promotion methods", "advertising promotion", "sales promotion", "direct promotion", "developments in digital promotion", "the role of packaging in promotion", "the role of branding in promotion"]'::jsonb,4),
    ('3.3','3.3.6','Place (channels of distribution)','["the objectives and usefulness of different channels of distribution", "digital and physical distribution Operations management (AS Level) The focus of this topic is on operations management from the production of physical products to managing the process of creating services. There are different ways a business can produce a product, with a range of aspects to consider in its production. Candidates are provided with the opportunity to apply their understanding of production methods in a variety of business contexts."]'::jsonb,5),
    ('4.1','4.1.1','The transformational process','["the use of factors of production: land, labour, capital and enterprise", "the stages of the transformational process: inputs to outputs", "the contribution of operations to added value"]'::jsonb,0),
    ('4.1','4.1.2','Efficiency, effectiveness, productivity and sustainability','["the importance of efficiency, effectiveness, productivity and sustainability", "measurement of labour productivity", "the impact on a business of measures to improve sustainability of operations Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 21 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('4.1','4.1.3','Capital intensive and labour intensive operations','["the benefits and limitations of capital intensive operations", "the benefits and limitations of labour intensive operations"]'::jsonb,2),
    ('4.1','4.1.4','Operations methods: job, batch, flow, mass customisation','["differences between methods - advantages and disadvantages of each method", "the problems of changing from one method to another"]'::jsonb,3),
    ('4.2','4.2.1','Managing inventory','["the purpose of inventory within a business (raw materials, work in progress, finished products)", "the costs and benefits of holding inventory", "buffer inventory, re-order level and lead time", "interpretation of simple inventory control charts", "the importance of Supply Chain Management"]'::jsonb,0),
    ('4.2','4.2.2','Just in Time (JIT)','["the purpose of JIT and JIC (Just in Case) inventory management", "the impact of adopting a JIT approach on a business"]'::jsonb,1),
    ('4.3','4.3.1','Significance and measurement of capacity utilisation','["the measurement of capacity utilisation", "the impact of operating under or over maximum capacity on a business", "methods of improving capacity utilisation"]'::jsonb,0),
    ('4.3','4.3.2','Outsourcing','["the impact of outsourcing on a business Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 22 www.cambridgeinternational.org/alevel Back to contents page Finance and accounting (AS Level) The focus of this topic is on the areas more traditionally associated with finance such as how a business can fund itself and where that money goes. Candidates will learn why a business requires finance to operate, and the importance for businesses to successfully manage their finance."]'::jsonb,1),
    ('5.1','5.1.1','The need for business finance','["reasons why businesses need finance to start up, to grow and to survive", "the distinction between short and long term need for finance", "the difference between cash and profits", "business failure as a consequence of lack of finance: bankruptcy, liquidation and administration"]'::jsonb,0),
    ('5.1','5.1.2','Working capital','["the meaning and importance of working capital", "managing trade receivables and trade payables", "the distinction between capital expenditure and revenue expenditure"]'::jsonb,1),
    ('5.2','5.2.1','Business ownership and sources of finance','["the relationship between the form of business ownership and availability of sources of finance"]'::jsonb,0),
    ('5.2','5.2.2','Internal and external sources of finance','["internal sources of finance: owners investment, retained earnings, sale of unwanted assets, sale and leaseback of non-current assets, working capital", "external sources of finance: share capital, debentures, new partners, venture capital, bank overdrafts, leasing, hire purchase, bank loans, mortgages, debt factoring, trade credit, micro-finance, crowd funding and government grants"]'::jsonb,1),
    ('5.2','5.2.3','Factors affecting the sources of finance','["the factors influencing the choice of sources of finance in a given situation: cost, flexibility, need to retain control, the use to which it is put, level of existing debt"]'::jsonb,2),
    ('5.2','5.2.4','Selecting the source of finance','["the appropriateness of each possible source in a given situation Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 23 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('5.3','5.3.1','Cash flow forecasts','["the meaning and purpose of cash flow forecasts", "the interpretation and amendment of simple cash flow forecasts: calculating opening and closing balances", "different methods of improving cash flow"]'::jsonb,0),
    ('5.4','5.4.1','Cost information','["the need for accurate cost information", "different types of costs: fixed, variable, direct and indirect"]'::jsonb,0),
    ('5.4','5.4.2','Approaches to costing: full, contribution','["the differences between full and contribution costing", "the uses and limitations of the full costing method", "the nature of the technique of contribution costing", "the difference between contribution and profit", "the limitations of contribution costing", "situations in which contribution costing would be and would not be used"]'::jsonb,1),
    ('5.4','5.4.3','Uses of cost information','["cost information for decision-making purposes, e.g. average, marginal, total costs", "how costs can be used for pricing decisions", "how costs can be used to monitor and improve business performance, including using cost information to calculate profits", "contribution costing as a means to help make special order decisions"]'::jsonb,2),
    ('5.4','5.4.4','Break-even analysis','["the meaning and importance of break-even analysis", "calculation and interpretation of break-even level of output, contribution, margin of safety and level of profit (in numeric and graphic form)", "the uses and limitations of break-even analysis Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 24 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('5.5','5.5.1','The meaning and purpose of budgets','["the measurement of performance", "the benefits and drawbacks from the use of budgets", "the meaning and use of incremental budgets, flexible budgets and zero budgeting", "the uses of budgets for measuring performance, allocating resources, controlling and monitoring a business"]'::jsonb,0),
    ('5.5','5.5.2','Variances','["the meaning of adverse variances and favourable variances", "the calculation and interpretation of variances"]'::jsonb,1)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Business AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Business' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Business A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','9609','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='9609', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'6.1','External influences on business activity',0),
    (v_org,v_tpl,'6.2','Business strategy',1),
    (v_org,v_tpl,'7.1','Organisational structure',2),
    (v_org,v_tpl,'7.2','Business communication',3),
    (v_org,v_tpl,'7.3','Leadership',4),
    (v_org,v_tpl,'7.4','Human resource management (HRM) strategy',5),
    (v_org,v_tpl,'8.1','Marketing analysis',6),
    (v_org,v_tpl,'8.2','Marketing strategy',7),
    (v_org,v_tpl,'9.1','Location and scale',8),
    (v_org,v_tpl,'9.2','Quality management',9),
    (v_org,v_tpl,'9.3','Operations strategy',10),
    (v_org,v_tpl,'10.1','Financial statements',11),
    (v_org,v_tpl,'10.2','Analysis of published accounts',12),
    (v_org,v_tpl,'10.3','Investment appraisal',13),
    (v_org,v_tpl,'10.4','Finance and accounting strategy',14);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('6.1','6.1.1','Political and legal','["the advantages and disadvantages of privatisation in a given situation", "the advantages and disadvantages of nationalisation in a given situation", "how a government might use the law to seek to control: employment practices, conditions of work (including health and safety), wage levels, marketing behaviour, competition, location decisions, particular goods and services", "the impact of changes in political and legal factors on business and business decisions Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 25 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('6.1','6.1.2','Economic','["how government might intervene to help businesses and encourage enterprise", "how government might intervene to constrain business activity", "how government might deal with market failure", "the key macroeconomic objectives of governments: low unemployment, low inflation, economic growth", "how macroeconomic objectives and performance of an economy can have an impact on business activity", "government policies used to achieve macroeconomic objectives: monetary, fiscal, supply-side and exchange rate policies", "the impact of changes in these government policies on business and business decisions"]'::jsonb,1),
    ('6.1','6.1.3','Social and demographic','["the impact of and issues associated with corporate social responsibility (CSR), e.g. accounting practices, paying incentives for the award of contracts, social auditing", "why businesses need to consider the needs of the community including pressure groups", "demographic changes at a local, national and global level", "the impact of social and demographic change on business and business decisions"]'::jsonb,2),
    ('6.1','6.1.4','Technological','["the impact of technological change on business and business decisions"]'::jsonb,3),
    ('6.1','6.1.5','Competitors and suppliers','["the impact of competitors and suppliers on business and business decisions"]'::jsonb,4),
    ('6.1','6.1.6','International','["the importance of international trading links and their impact on business and business decisions", "how international trade agreements might have an impact on businesses", "the role of technology in international trade", "the advantages and disadvantages that a multinational might bring to a country", "relationships between multinationals and governments"]'::jsonb,5),
    ('6.1','6.1.7','Environmental','["how physical environmental issues might influence business behaviour", "how a business and its stakeholders may use an environmental audit", "the impact of the growing importance of sustainability on business and business decisions Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 26 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,6),
    ('6.2','6.2.1','Developing business strategy','["the meaning and purpose of business strategy", "the meaning and purpose of strategic management: analysis, choice and implementation", "approaches to develop business strategy, including: - blue ocean strategy - scenario planning - SWOT analysis - PEST analysis - Porter''s five forces - core competence framework - Ansoff matrix - force field analysis - decision trees"]'::jsonb,0),
    ('6.2','6.2.2','Corporate planning and implementation','["the meaning and importance of corporate planning", "the meaning of corporate culture and its impact on business decision-making", "the meaning and importance of transformational leadership", "the management and control of strategic change", "the meaning and importance of contingency planning and crisis management"]'::jsonb,1),
    ('7.1','7.1.1','The relationship between business objectives and organisational structure','["the purpose and attributes of an organisational structure such as flexibility, meeting the needs of the business, allowing for growth and development and encouraging intrapreneurship Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 27 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('7.1','7.1.2','Types of structure: functional, hierarchical (flat and narrow), matrix','["the advantages and disadvantages of the different types of structure", "why some organisations are structured by product and others by function or geographical area", "the reasons and ways structures change e.g. due to growth or delayering", "the features of a formal structure: levels of hierarchy, chain of command, span of control, responsibility, authority, delegation, accountability, centralised, decentralised"]'::jsonb,1),
    ('7.1','7.1.3','Delegation and accountability','["the relationship between delegation and accountability", "the processes of accountability in a business", "the impact of delegation on a business"]'::jsonb,2),
    ('7.1','7.1.4','Control, authority and trust','["the relationship between span of control and levels of hierarchy", "the difference between authority and responsibility", "the conflicts between control and trust that might arise when delegating"]'::jsonb,3),
    ('7.1','7.1.5','Centralisation and decentralisation','["the impact of centralisation and decentralisation on a business"]'::jsonb,4),
    ('7.1','7.1.6','Line and staff','["examples of and distinctions between line and staff functions and the conflicts between them"]'::jsonb,5),
    ('7.2','7.2.1','Purposes of communication','["situations in which communication is essential"]'::jsonb,0),
    ('7.2','7.2.2','Methods of communication','["the standard methods of communication used in business: spoken, written, electronic, visual", "the strengths and weaknesses of the different methods of communication Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 28 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('7.2','7.2.3','Channels of communication','["how communication works within a business", "the difference between one- and two-way communication; the difference between vertical and horizontal communication", "problems associated with different channels of communication"]'::jsonb,2),
    ('7.2','7.2.4','Barriers to communication','["barriers to communication and how to overcome them"]'::jsonb,3),
    ('7.2','7.2.5','The role of management in facilitating communication','["the role of informal communications within a business", "ways in which communication can influence the efficiency of a business", "ways of improving communication in a given situation"]'::jsonb,4),
    ('7.3','7.3.1','Leadership','["the purpose of leadership", "leadership roles in business (directors, managers, supervisors, worker representatives)", "the qualities of a good leader"]'::jsonb,0),
    ('7.3','7.3.2','Theories of leadership','["key leadership theories: trait, behavioural, contingency, power and influence and transformational"]'::jsonb,1),
    ('7.3','7.3.3','Emotional intelligence/emotional quotient (EQ)','["Goleman''s four competencies of emotional intelligence: self-awareness, social awareness, self- management and social skills"]'::jsonb,2),
    ('7.4','7.4.1','Approaches to human resource management (HRM)','["the difference between ''hard'' and ''soft'' HRM", "flexible working contracts: advantages and disadvantages of temporary contracts or flexible contracts including zero hours contracts, part-time, full-time, annualised hours, flexi-time, home working, shift working, job sharing, compressed working hours, the gig economy", "the measurement, causes and consequences of poor employee performance", "strategies for improving employee performance", "Management by Objectives (MBO) - implementation and usefulness", "the changing role of Information Technology (IT) and Artificial Intelligence (AI) in HRM Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 29 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('8.1','8.1.1','Elasticity','["the concept of elasticity of demand: price, income and promotional", "calculation of price, income and promotional elasticity of demand", "interpretation of elasticity results", "the impact of elasticity measures on business decisions", "the limitations of the concept of elasticity in its various forms"]'::jsonb,0),
    ('8.1','8.1.2','Product development','["the process of product development", "sources of new ideas for product development", "the importance of Research and Development (R&D)"]'::jsonb,1),
    ('8.1','8.1.3','Sales forecasting','["the need to forecast sales", "time series analysis: calculation and use of four period centred moving average method to forecast sales", "qualitative sales forecasting", "the impact of sales forecasting on business decisions"]'::jsonb,2),
    ('8.2','8.2.1','Planning the marketing strategy','["the contents of a marketing plan: objectives, resources, research, marketing mix", "the benefits and limitations of marketing planning"]'::jsonb,0),
    ('8.2','8.2.2','Approaches to marketing strategy','["the need for the marketing strategy to be consistent with the business, the product and the market", "the need for and development of a coordinated marketing strategy", "the development of marketing strategies that are focused towards achieving specific marketing objectives", "the changing role of Information Technology (IT) and Artificial Intelligence (AI) in marketing Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 30 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('8.2','8.2.3','Strategies for international marketing','["the implications for marketing of increased globalisation and economic collaboration", "the importance of international marketing for a business", "international markets - identification, selection and entry", "whether a business in a given situation should develop an international market through pan-global marketing or maintain local differences", "choosing a strategy, in a given situation, to develop a global market", "the factors influencing the method of entry into international markets"]'::jsonb,2),
    ('9.1','9.1.1','Location','["the factors that determine location and relocation", "the differences between local, national and international location decisions", "the reasons for and impact of offshoring and reshoring", "the impact of globalisation on location and relocation decisions"]'::jsonb,0),
    ('9.1','9.1.2','Scale of operations','["the factors that influence the scale of a business", "causes and examples of internal and external economies and diseconomies of scale", "the links between economies and diseconomies of scale and unit costs Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 31 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('9.2','9.2.1','Quality control and quality assurance','["quality in terms of meeting customer expectations", "the importance of quality", "the impact of methods of quality control on a business", "the impact of methods of quality assurance on a business", "the impact of Total Quality Management (TQM) on a business"]'::jsonb,0),
    ('9.2','9.2.2','Benchmarking','["the importance of benchmarking in quality management"]'::jsonb,1),
    ('9.3','9.3.1','Operational decisions','["the influence of human, marketing and finance resource availability on operations decisions", "the changing role of Information Technology (IT) and Artificial Intelligence (AI) in operations management"]'::jsonb,0),
    ('9.3','9.3.2','Flexibility and innovation','["the need for flexibility with regard to volume, delivery time and specification", "process innovation: changing current processes or adopting new ways of producing products or delivering services"]'::jsonb,1),
    ('9.3','9.3.3','Enterprise resource planning (ERP)','["the main features of an ERP programme", "how ERP can improve a business'' efficiency in relation to: inventory control, costing and pricing, capacity utilisation, responses to change, workforce flexibility, management information"]'::jsonb,2),
    ('9.3','9.3.4','Lean production','["the aims and purposes of lean production", "Kaizen, quality circles, simultaneous engineering, cell production, JIT manufacturing and waste management as operational strategies to achieve lean production", "the limitations of operational strategies to achieve lean production", "the links between lean production and inventory control, quality, employees roles, capacity management and efficiency Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 32 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('9.3','9.3.5','Operations planning','["the need for planning operations", "network diagrams as tools to plan operations", "the main elements of a network diagram: activities, dummy activities, nodes", "network diagrams as means of performing Critical Path Analysis (CPA), including identification of the minimum project duration and the critical path, calculation of total and free float, interpretation of the results of the analysis of a network, how minimum duration and floats might be used in project management", "the benefits and limitations of CPA as a management tool"]'::jsonb,4),
    ('10.1','10.1.1','Statement of profit or loss','["the meaning and purpose of the statement of profit or loss", "the contents of a statement of profit or loss: revenue, cost of sales, gross profit, expenses, profit from operations (operating profit), taxation, profit for the year, dividends, retained earnings", "amendment of a statement of profit or loss", "the impact on the statement of profit or loss of a given change"]'::jsonb,0),
    ('10.1','10.1.2','Statement of financial position','["the meaning and purpose of statement of financial position", "the contents of a statement of financial position including non-current assets, current assets, current liabilities, net current assets, net assets, non-current liabilities, reserves and equity", "amendment of a statement of financial position", "the relationships between items in the statement of profit or loss and the statement of financial position"]'::jsonb,1),
    ('10.1','10.1.3','Inventory valuation','["the difficulties of valuing inventory", "the net realisable value method Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 33 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('10.1','10.1.4','Depreciation','["the role of depreciation in the accounts", "the impact of depreciation (straight-line method only) on the statement of financial position and the statement of profit or loss"]'::jsonb,3),
    ('10.2','10.2.1','Liquidity ratios','["the meaning and importance of liquidity", "current ratio: calculation and interpretation", "acid test ratio: calculation and interpretation", "methods of improving liquidity"]'::jsonb,0),
    ('10.2','10.2.2','Profitability ratios','["the meaning and importance of profitability", "return on capital employed: calculation and interpretation", "gross profit margin: calculation and interpretation", "profit margin: calculation and interpretation", "methods of improving profitability"]'::jsonb,1),
    ('10.2','10.2.3','Financial efficiency ratios','["the meaning and importance of financial efficiency", "rate of inventory turnover: calculation and interpretation", "trade receivables turnover (days): calculation and interpretation", "trade payables turnover (days): calculation and interpretation", "methods of improving financial efficiency"]'::jsonb,2),
    ('10.2','10.2.4','Gearing ratio','["the meaning and importance of gearing", "gearing ratio: calculation and interpretation", "methods of improving gearing"]'::jsonb,3),
    ('10.2','10.2.5','Investment ratios','["the meaning and importance of return to investors", "dividend yield: calculation and interpretation", "dividend cover: calculation and interpretation", "price/earnings ratio: calculation and interpretation", "methods of improving investor return Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 34 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,4),
    ('10.3','10.3.1','The concept of investment appraisal','["the need for investment appraisal"]'::jsonb,0),
    ('10.3','10.3.2','Basic methods: payback, accounting rate of return (ARR)','["the meaning, calculation and interpretation of payback and ARR (ARR = (average profit / average investment) × 100)"]'::jsonb,1),
    ('10.3','10.3.3','Discounted cash flow method: net present value (NPV)','["the meaning, calculation and interpretation of NPV"]'::jsonb,2),
    ('10.3','10.3.4','Investment appraisal decisions','["quantitative results and their impact on investment decisions", "qualitative factors and their impact on investment decisions", "comparison of investment appraisal methods, including their limitations"]'::jsonb,3),
    ('10.4','10.4.1','The use of accounting data to enable strategic decision-making','["the use of financial statements in developing strategies", "the contents of an annual report and their usefulness to business and other stakeholders"]'::jsonb,0),
    ('10.4','10.4.2','The use of accounting data and ratio analysis in strategic decision-making','["assessment of business performance over time and against competitors", "the impact of accounting data including ratio results on business strategy", "the impact of debt or equity decisions on ratio results", "the impact of changes in dividend strategy on ratio results", "the impact of business growth on ratio results", "the impact of other business strategies on ratio results", "the limitations of using published accounts and ratio analyses Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 35 www.cambridgeinternational.org/alevel Back to contents page Ratios to support analysis of published accounts Liquidity ratios Current ratio Current assets Current liabilities Answer presented as a ratio Acid test ratio Current assets - inventory Current liabilities Answer presented as a ratio Profitability ratios Gross profit margin (%) Gross profit Revenue × 100 Operating profit margin (%) Profit from operations Revenue × 100 Return on capital employed (%) Profit from operations Capital employed × 100 Capital employed = issued shares + reserves + non-current liabilities Financial efficiency ratios Trade receivables turnover (days) Trade receivables Credit sales × 365 days Trade payables turnover (days) Trade payables Credit purchases × 365 days Rate of inventory turnover (times) Cost of sales Average inventory Gearing ratio Gearing (%) Non-current liabilities Capital employed × 100 Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. Subject content 36 www.cambridgeinternational.org/alevel Back to contents page Investment ratios Price/earnings ratio Market price per share Earnings per share Dividend yield (%) Dividend per share Market price per share × 100 Dividend cover Profit for the year Annual dividend Cambridge International AS & A Level Business 9609 syllabus for 2026, 2027 and 2028. 37 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Business A2';
END $$;
