-- Chemistry (9701) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Chemistry' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Chemistry AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2025-2027','9701','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2025-2027', cambridge_code='9701', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Atomic structure',0),
    (v_org,v_tpl,'2','Atoms, molecules and stoichiometry',1),
    (v_org,v_tpl,'3','Chemical bonding',2),
    (v_org,v_tpl,'4','States of matter',3),
    (v_org,v_tpl,'5','Chemical energetics',4),
    (v_org,v_tpl,'6','Electrochemistry',5),
    (v_org,v_tpl,'7','Equilibria',6),
    (v_org,v_tpl,'8','Reaction kinetics',7),
    (v_org,v_tpl,'9','The Periodic Table: chemical periodicity',8),
    (v_org,v_tpl,'10','Group 2',9),
    (v_org,v_tpl,'11','Group 17',10),
    (v_org,v_tpl,'12','Nitrogen and sulfur',11),
    (v_org,v_tpl,'13','An introduction to AS Level organic chemistry',12),
    (v_org,v_tpl,'14','Hydrocarbons',13),
    (v_org,v_tpl,'15','Halogen compounds',14),
    (v_org,v_tpl,'16','Hydroxy compounds',15),
    (v_org,v_tpl,'17','Carbonyl compounds',16),
    (v_org,v_tpl,'18','Carboxylic acids and derivatives',17),
    (v_org,v_tpl,'19','Nitrogen compounds',18),
    (v_org,v_tpl,'20','Polymerisation',19),
    (v_org,v_tpl,'21','Organic synthesis',20),
    (v_org,v_tpl,'22','Analytical techniques',21);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Particles in the atom and atomic radius','["understand that atoms are mostly empty space surrounding a very small, dense nucleus that contains protons and neutrons; electrons are found in shells in the empty space around the nucleus", "identify and describe protons, neutrons and electrons in terms of their relative charges and relative masses", "understand the terms atomic and proton number; mass and nucleon number", "describe the distribution of mass and charge within an atom", "describe the behaviour of beams of protons, neutrons and electrons moving at the same velocity in an electric field", "determine the numbers of protons, neutrons and electrons present in both atoms and ions given atomic or proton number, mass or nucleon number and charge", "state and explain qualitatively the variations in atomic radius and ionic radius across a period and down a group"]'::jsonb,0),
    ('1','1.2','Isotopes','["define the term isotope in terms of numbers of protons and neutrons", "understand the notation x y A for isotopes, where x is the mass or nucleon number and y is the atomic or proton number", "state that and explain why isotopes of the same element have the same chemical properties", "state that and explain why isotopes of the same element have different physical properties, limited to mass and density Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('1','1.3','Electrons, energy levels and atomic orbitals','["understand the terms: • shells, sub-shells and orbitals • principal quantum number (n) • ground state, limited to electronic configuration", "describe the number of orbitals making up s, p and d sub-shells, and the number of electrons that can fill s, p and d sub-shells", "describe the order of increasing energy of the sub-shells within the first three shells and the 4s and 4p sub-shells", "describe the electronic configurations to include the number of electrons in each shell, sub-shell and orbital", "explain the electronic configurations in terms of energy of the electrons and inter-electron repulsion", "determine the electronic configuration of atoms and ions given the atomic or proton number and charge, using either of the following conventions: e.g. for Fe: 1s 2 2s 2 2p 6 3s 2 3p 6 3d 6 4s 2 (full electronic configuration) or [Ar] 3d 6 4s 2 (shorthand electronic configuration)", "understand and use the electrons in boxes notation e.g. for Fe: [Ar]", "describe and sketch the shapes of s and p orbitals", "describe a free radical as a species with one or more unpaired electrons"]'::jsonb,2),
    ('1','1.4','Ionisation energy','["define and use the term first ionisation energy, IE", "construct equations to represent first, second and subsequent ionisation energies", "identify and explain the trends in ionisation energies across a period and down a group of the Periodic Table", "identify and explain the variation in successive ionisation energies of an element", "understand that ionisation energies are due to the attraction between the nucleus and the outer electron", "explain the factors influencing the ionisation energies of elements in terms of nuclear charge, atomic/ionic radius, shielding by inner shells and sub-shells and spin-pair repulsion", "deduce the electronic configurations of elements using successive ionisation energy data", "deduce the position of an element in the Periodic Table using successive ionisation energy data Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('2','2.1','Relative masses of atoms and molecules','["define the unified atomic mass unit as one twelfth of the mass of a carbon-12 atom", "define relative atomic mass, A r , relative isotopic mass, relative molecular mass, M r , and relative formula mass in terms of the unified atomic mass unit"]'::jsonb,0),
    ('2','2.2','The mole and the Avogadro constant','["define and use the term mole in terms of the Avogadro constant"]'::jsonb,1),
    ('2','2.3','Formulas','["write formulas of ionic compounds from ionic charges and oxidation numbers (shown by a Roman numeral), including: (a) the prediction of ionic charge from the position of an element in the Periodic Table (b) recall of the names and formulas for the following ions: NO 3 - , CO 3 2- , SO 4 2- , OH - , NH 4 + , Zn 2+ , Ag + , HCO 3 - , PO 4 3-", "(a) write and construct equations (which should be balanced), including ionic equations (which should not include spectator ions) (b) use appropriate state symbols in equations", "define and use the terms empirical and molecular formula", "understand and use the terms anhydrous, hydrated and water of crystallisation", "calculate empirical and molecular formulas, using given data Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('2','2.4','Reacting masses and volumes (of solutions and gases)','["perform calculations including use of the mole concept, involving: (a) reacting masses (from formulas and equations) including percentage yield calculations (b) volumes of gases (e.g. in the burning of hydrocarbons) (c) volumes and concentrations of solutions (d) limiting reagent and excess reagent (When performing calculations, candidates'' answers should reflect the number of significant figures given or asked for in the question. When rounding up or down, candidates should ensure that significant figures are neither lost unnecessarily nor used beyond what is justified (see also Mathematical requirements section).) (e) deduce stoichiometric relationships from calculations such as those in 2.4.1(a)-(d)"]'::jsonb,3),
    ('3','3.1','Electronegativity and bonding','["define electronegativity as the power of an atom to attract electrons to itself", "explain the factors influencing the electronegativities of the elements in terms of nuclear charge, atomic radius and shielding by inner shells and sub-shells", "state and explain the trends in electronegativity across a period and down a group of the Periodic Table", "use the differences in Pauling electronegativity values to predict the formation of ionic and covalent bonds (the presence of covalent character in some ionic compounds will not be assessed) (Pauling electronegativity values will be given where necessary)"]'::jsonb,0),
    ('3','3.2','Ionic bonding','["define ionic bonding as the electrostatic attraction between oppositely charged ions (positively charged cations and negatively charged anions)", "describe ionic bonding including the examples of sodium chloride, magnesium oxide and calcium fluoride Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('3','3.3','Metallic bonding','["define metallic bonding as the electrostatic attraction between positive metal ions and delocalised electrons"]'::jsonb,2),
    ('3','3.4','Covalent bonding and coordinate (dative covalent) bonding','["define covalent bonding as electrostatic attraction between the nuclei of two atoms and a shared pair of electrons (a) describe covalent bonding in molecules including: • hydrogen, H 2 • oxygen, O 2 • nitrogen, N 2 • chlorine, C l 2 • hydrogen chloride, HC l • carbon dioxide, CO 2 • ammonia, NH 3 • methane, CH 4 • ethane, C 2 H 6 • ethene, C 2 H 4 (b) understand that elements in period 3 can expand their octet including in the compounds sulfur dioxide, SO 2 , phosphorus pentachloride, PC l 5 , and sulfur hexafluoride, SF 6 (c) describe coordinate (dative covalent) bonding, including in the reaction between ammonia and hydrogen chloride gases to form the ammonium ion, NH 4 + , and in the A l 2 C l 6 molecule", "(a) describe covalent bonds in terms of orbital overlap giving σ and π bonds: • σ bonds are formed by direct overlap of orbitals between the bonding atoms • π bonds are formed by the sideways overlap of adjacent p orbitals above and below the σ bond (b) describe how the σ and π bonds form in molecules including H₂, C₂H₆, C₂H₄, HCN and N₂ (c) use the concept of hybridisation to describe sp, sp² and sp³ orbitals", "(a) define the terms: • bond energy as the energy required to break one mole of a particular covalent bond in the gaseous state • bond length as the internuclear distance of two covalently bonded atoms (b) use bond energy values and the concept of bond length to compare the reactivity of covalent molecules Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('3','3.5','Shapes of molecules','["state and explain the shapes of, and bond angles in, molecules by using VSEPR theory, including as simple examples: • BF 3 (trigonal planar, 120°) • CO 2 (linear, 180°) • CH 4 (tetrahedral, 109.5°) • NH 3 (pyramidal, 107°) • H 2 O (non-linear, 104.5°) • SF 6 (octahedral, 90°) • PF 5 (trigonal bipyramidal, 120° and 90°)", "predict the shapes of, and bond angles in, molecules and ions analogous to those specified in 3.5.1"]'::jsonb,4),
    ('3','3.6','Intermolecular forces, electronegativity and bond properties','["(a) describe hydrogen bonding, limited to molecules containing N-H and O-H groups, including ammonia and water as simple examples (b) use the concept of hydrogen bonding to explain the anomalous properties of H₂O (ice and water): • its relatively high melting and boiling points • its relatively high surface tension • the density of the solid ice compared with the liquid water", "use the concept of electronegativity to explain bond polarity and dipole moments of molecules", "(a) describe van der Waals'' forces as the intermolecular forces between molecular entities other than those due to bond formation, and use the term van der Waals'' forces as a generic term to describe all intermolecular forces (b) describe the types of van der Waals'' forces: • instantaneous dipole-induced dipole (id-id) forces, also called London dispersion forces • permanent dipole-permanent dipole (pd-pd) forces, including hydrogen bonding (c) \t describe hydrogen bonding and understand that hydrogen bonding is a special case of permanent dipole-permanent dipole forces between molecules where hydrogen is bonded to a highly electronegative atom", "state that, in general, ionic, covalent and metallic bonding are stronger than intermolecular forces Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,5),
    ('3','3.7','Dot-and-cross diagrams','["use dot-and-cross diagrams to illustrate ionic, covalent and coordinate bonding including the representation of any compounds stated in 3.4 and 3.5 (dot-and-cross diagrams may include species with atoms which have an expanded octet or species with an odd number of electrons)"]'::jsonb,6),
    ('4','4.1','The gaseous state: ideal and real gases and pV = nRT','["explain the origin of pressure in a gas in terms of collisions between gas molecules and the wall of the container", "understand that ideal gases have zero particle volume and no intermolecular forces of attraction", "state and use the ideal gas equation pV = nRT in calculations, including in the determination of M r"]'::jsonb,0),
    ('4','4.2','Bonding and structure','["describe, in simple terms, the lattice structure of a crystalline solid which is: (a) giant ionic, including sodium chloride and magnesium oxide (b) simple molecular, including iodine, buckminsterfullerene C 60 and ice (c) giant molecular, including silicon( IV ) oxide, graphite and diamond (d) giant metallic, including copper", "describe, interpret and predict the effect of different types of structure and bonding on the physical properties of substances, including melting point, boiling point, electrical conductivity and solubility", "deduce the type of structure and bonding present in a substance from given information Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('5','5.1','Enthalpy change,','["understand that chemical reactions are accompanied by enthalpy changes and these changes can be exothermic ( Δ H is negative) or endothermic ( Δ H is positive)", "construct and interpret a reaction pathway diagram, in terms of the enthalpy change of the reaction and of the activation energy", "define and use the terms: (a) standard conditions (this syllabus assumes that these are 298 K and 101 kPa) shown by ⦵ . (b) enthalpy change with particular reference to: reaction, Δ H r , formation, Δ H f , combustion, Δ H c , neutralisation, Δ H neut", "understand that energy transfers occur during chemical reactions because of the breaking and making of chemical bonds", "use bond energies ( Δ H positive, i.e. bond breaking) to calculate enthalpy change of reaction, Δ H r", "understand that some bond energies are exact and some bond energies are averages", "calculate enthalpy changes from appropriate experimental results, including the use of the relationships q = mc Δ T and Δ H = - mc Δ T / n"]'::jsonb,0),
    ('5','5.2','Hess''s law','["apply Hess''s law to construct simple energy cycles", "carry out calculations using cycles and relevant energy terms, including: (a) determining enthalpy changes that cannot be found by direct experiment (b) use of bond energy data"]'::jsonb,1),
    ('6','6.1','Redox processes: electron transfer and changes in oxidation number (oxidation state)','["calculate oxidation numbers of elements in compounds and ions", "use changes in oxidation numbers to help balance chemical equations", "explain and use the terms redox, oxidation, reduction and disproportionation in terms of electron transfer and changes in oxidation number", "explain and use the terms oxidising agent and reducing agent", "use a Roman numeral to indicate the magnitude of the oxidation number of an element Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('7','7.1','Chemical equilibria: reversible reactions, dynamic equilibrium','["(a) understand what is meant by a reversible reaction (b) understand what is meant by dynamic equilibrium in terms of the rate of forward and reverse reactions being equal and the concentration of reactants and products remaining constant (c) understand the need for a closed system in order to establish dynamic equilibrium", "define Le Chatelier''s principle as: if a change is made to a system at dynamic equilibrium, the position of equilibrium moves to minimise this change", "use Le Chatelier''s principle to deduce qualitatively (from appropriate information) the effects of changes in temperature, concentration, pressure or presence of a catalyst on a system at equilibrium", "deduce expressions for equilibrium constants in terms of concentrations, K c", "use the terms mole fraction and partial pressure", "deduce expressions for equilibrium constants in terms of partial pressures, K p (use of the relationship between K p and K c is not required)", "use the K c and K p expressions to carry out calculations (such calculations will not require the solving of quadratic equations)", "calculate the quantities present at equilibrium, given appropriate data", "state whether changes in temperature, concentration or pressure or the presence of a catalyst affect the value of the equilibrium constant for a reaction", "describe and explain the conditions used in the Haber process and the Contact process, as examples of the importance of an understanding of dynamic equilibrium in the chemical industry and the application of Le Chatelier''s principle"]'::jsonb,0),
    ('7','7.2','Brønsted-Lowry theory of acids and bases','["state the names and formulas of the common acids, limited to hydrochloric acid, HC l , sulfuric acid, H 2 SO 4 , nitric acid, HNO 3 , ethanoic acid, CH 3 COOH", "state the names and formulas of the common alkalis, limited to  sodium hydroxide, NaOH, potassium hydroxide, KOH, ammonia, NH 3", "describe the Brønsted-Lowry theory of acids and bases", "describe strong acids and strong bases as fully dissociated in aqueous solution and weak acids and weak bases as partially dissociated in aqueous solution", "appreciate that water has pH of 7, acid solutions pH of below 7 and alkaline solutions pH of above 7", "explain qualitatively the differences in behaviour between strong and weak acids including the reaction with a reactive metal and difference in pH values by use of a pH meter, universal indicator or conductivity", "understand that neutralisation reactions occur when H + (aq) and OH - (aq) form H 2 O(l)", "understand that salts are formed in neutralisation reactions", "sketch the pH titration curves of titrations using combinations of strong and weak acids with strong and weak alkalis", "select suitable indicators for acid-alkali titrations, given appropriate data (p K a values will not be used) Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('8','8.1','Rate of reaction','["explain and use the term rate of reaction, frequency of collisions, effective collisions and non-effective collisions", "explain qualitatively, in terms of frequency of effective collisions, the effect of concentration and pressure changes on the rate of a reaction", "use experimental data to calculate the rate of a reaction"]'::jsonb,0),
    ('8','8.2','Effect of temperature on reaction rates and the concept of activation energy','["define activation energy, E A , as the minimum energy required for a collision to be effective", "sketch and use the Boltzmann distribution to explain the significance of activation energy", "explain qualitatively, in terms both of the Boltzmann distribution and of frequency of effective collisions, the effect of temperature change on the rate of a reaction"]'::jsonb,1),
    ('8','8.3','Homogeneous and heterogeneous catalysts','["explain and use the terms catalyst and catalysis: (a) explain that, in the presence of a catalyst, a reaction has a different mechanism, i.e. one of lower activation energy (b) explain this catalytic effect in terms of the Boltzmann distribution (c) construct and interpret a reaction pathway diagram, for a reaction in the presence and absence of an effective catalyst Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page Inorganic chemistry"]'::jsonb,2),
    ('9','9.1','Periodicity of physical properties of the elements in Period 3','["describe qualitatively (and indicate the periodicity in) the variations in atomic radius, ionic radius, melting point and electrical conductivity of the elements", "explain the variation in melting point and electrical conductivity in terms of the structure and bonding of the elements"]'::jsonb,0),
    ('9','9.2','Periodicity of chemical properties of the elements in Period 3','["describe, and write equations for, the reactions of the elements with oxygen (to give Na 2 O, MgO, A l 2 O 3 , P 4 O 10 , SO 2 ), chlorine (to give NaC l , MgC l 2 , A l C l 3 , SiC l 4 , PC l 5 ) and water (Na and Mg only)", "state and explain the variation in the oxidation number of the oxides (Na 2 O, MgO, A l 2 O 3 , P 4 O 10 , SO 2 and SO 3 only) and chlorides (NaC l , MgC l 2 , A l C l 3 , SiC l 4 , PC l 5 only) in terms of their outer shell (valence shell) electrons", "describe, and write equations for, the reactions, if any, of the oxides Na 2 O, MgO, A l 2 O 3 , SiO 2 , P 4 O 10 , SO 2 and SO 3 with water including the likely pHs of the solutions obtained", "describe, explain, and write equations for, the acid / base behaviour of the oxides Na 2 O, MgO, A l 2 O 3 , P 4 O 10 , SO 2 and SO 3 and the hydroxides NaOH, Mg(OH) 2 and A l (OH) 3 including, where relevant, amphoteric behaviour in reactions with acids and bases (sodium hydroxide only)", "describe, explain, and write equations for, the reactions of the chlorides NaC l , MgC l 2 , A l C l 3 , SiC l 4 , PC l 5 with water including the likely pHs of the solutions obtained", "explain the variations and trends in 9.2.2, 9.2.3, 9.2.4 and 9.2.5 in terms of bonding and electronegativity", "suggest the types of chemical bonding present in the chlorides and oxides from observations of their chemical and physical properties"]'::jsonb,1),
    ('9','9.3','Chemical periodicity of other elements','["predict the characteristic properties of an element in a given group by using knowledge of chemical periodicity", "deduce the nature, possible position in the Periodic Table and identity of unknown elements from given information about physical and chemical properties Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('10','10.1','Similarities and trends in the properties of the Group 2 metals, magnesium to barium, and their compounds','["describe, and write equations for, the reactions of the elements with oxygen, water and dilute hydrochloric and sulfuric acids", "describe, and write equations for, the reactions of the oxides, hydroxides and carbonates with water and dilute hydrochloric and sulfuric acids", "describe, and write equations for, the thermal decomposition of the nitrates and carbonates, to include the trend in thermal stabilities", "describe, and make predictions from, the trends in physical and chemical properties of the elements involved in the reactions in 10.1.1 and the compounds involved in 10.1.2, 10.1.3 and 10.1.5", "state the variation in the solubilities of the hydroxides and sulfates"]'::jsonb,0),
    ('11','11.1','Physical properties of the Group 17 elements','["describe the colours and the trend in volatility of chlorine, bromine and iodine", "describe and explain the trend in the bond strength of the halogen molecules", "interpret the volatility of the elements in terms of instantaneous dipole-induced dipole forces"]'::jsonb,0),
    ('11','11.2','The chemical properties of the halogen elements and the hydrogen halides','["describe the relative reactivity of the elements as oxidising agents", "describe the reactions of the elements with hydrogen and explain their relative reactivity in these reactions", "describe the relative thermal stabilities of the hydrogen halides and explain these in terms of bond strengths Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('11','11.3','Some reactions of the halide ions','["describe the relative reactivity of halide ions as reducing agents", "describe and explain the reactions of halide ions with: (a) aqueous silver ions followed by aqueous ammonia (the formation and formula of the [Ag(NH 3 ) 2 ] + complex is not required) (b) concentrated sulfuric acid, to include balanced chemical equations"]'::jsonb,2),
    ('11','11.4','The reactions of chlorine','["describe and interpret, in terms of changes in oxidation number, the reaction of chlorine with cold and with hot aqueous sodium hydroxide and recognise these as disproportionation reactions", "explain, including by use of an equation, the use of chlorine in water purification to include the production of the active species HOC l and C l O ­- which kill bacteria"]'::jsonb,3),
    ('12','12.1','Nitrogen and sulfur','["explain the lack of reactivity of nitrogen, with reference to triple bond strength and lack of polarity", "describe and explain: (a) the basicity of ammonia, using the Brønsted-Lowry theory (b) the structure of the ammonium ion and its formation by an acid-base reaction (c) the displacement of ammonia from ammonium salts by an acid-base reaction", "state and explain the natural and man-made occurrences of oxides of nitrogen and their catalytic removal from the exhaust gases of internal combustion engines", "understand that atmospheric oxides of nitrogen (NO and NO 2 ) can react with unburned hydrocarbons to form peroxyacetyl nitrate, PAN, which is a component of photochemical smog", "describe the role of NO and NO 2 in the formation of acid rain both directly and in their catalytic role in the oxidation of atmospheric sulfur dioxide Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page Organic chemistry"]'::jsonb,0),
    ('13','13.1','Formulas, functional groups and the naming of organic compounds','["define the term hydrocarbon as a compound made up of C and H atoms only", "understand that alkanes are simple hydrocarbons with no functional group", "understand that the compounds in the table on pages 29 and 30 contain a functional group which dictates their physical and chemical properties", "interpret and use the general, structural, displayed and skeletal formulas of the classes of compound stated in the table on pages 29 and 30", "understand and use systematic nomenclature of simple aliphatic organic molecules with functional groups detailed in the table on pages 29 and 30, up to six carbon atoms (six plus six for esters, straight chains only for esters and nitriles)", "deduce the molecular and/or empirical formula of a compound, given its structural, displayed or skeletal formula"]'::jsonb,0),
    ('13','13.2','Characteristic organic reactions','["interpret and use the following terminology associated with types of organic compounds and reactions: (a) homologous series (b) saturated and unsaturated (c) homolytic and heterolytic fission (d) free radical, initiation, propagation, termination (e) nucleophile, electrophile, nucleophilic, electrophilic (f) addition, substitution, elimination, hydrolysis, condensation (g) oxidation and reduction (in equations for organic redox reactions, the symbol [O] can be used to represent one atom of oxygen from an oxidising agent and the symbol [H] to represent one atom of hydrogen from a reducing agent)", "understand and use the following terminology associated with types of organic mechanisms: (a) free-radical substitution (b) electrophilic addition (c) nucleophilic substitution (d) nucleophilic addition (in organic reaction mechanisms, the use of curly arrows to represent movement of electron pairs is expected; the arrow should begin at a bond or a lone pair of electrons) Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('13','13.3','Shapes of organic molecules; σ and π bonds','["describe organic molecules as either straight-chained, branched or cyclic", "describe and explain the shape of, and bond angles in, molecules containing sp, sp 2 and sp 3 hybridised atoms", "describe the arrangement of σ and π bonds in molecules containing sp, sp 2 and sp 3 hybridised atoms", "understand and use the term planar when describing the arrangement of atoms in organic molecules, for example ethene"]'::jsonb,2),
    ('13','13.4','Isomerism: structural isomerism and stereoisomerism','["describe structural isomerism and its division into chain, positional and functional group isomerism", "describe stereoisomerism and its division into geometrical (cis/trans) and optical isomerism (use of E/Z nomenclature is acceptable but is not required)", "describe geometrical (cis/trans) isomerism in alkenes, and explain its origin in terms of restricted rotation due to the presence of π bonds", "explain what is meant by a chiral centre and that such a centre gives rise to two optical isomers (enantiomers) (Candidates should appreciate that compounds can contain more than one chiral centre, but knowledge of meso compounds, or nomenclature such as diastereoisomers is required.)", "identify chiral centres and geometrical (cis/trans) isomerism in a molecule of given structural formula including cyclic compounds", "deduce the possible isomers for an organic molecule of known molecular formula Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('14','14.1','Alkanes','["recall the reactions (reagents and conditions) by which alkanes can be produced: (a) addition of hydrogen to an alkene in a hydrogenation reaction, H 2 (g) and Pt/Ni catalyst and heat (b) cracking of a longer chain alkane, heat with A l 2 O 3", "describe: (a) the complete and incomplete combustion of alkanes (b) the free-radical substitution of alkanes by C l 2 or Br 2 in the presence of ultraviolet light, as exemplified by the reactions of ethane", "describe the mechanism of free-radical substitution with reference to the initiation, propagation and termination steps", "suggest how cracking can be used to obtain more useful alkanes and alkenes of lower M r from heavier crude oil fractions", "understand the general unreactivity of alkanes, including towards polar reagents in terms of the strength of the C-H bonds and their relative lack of polarity", "recognise the environmental consequences of carbon monoxide, oxides of nitrogen and unburnt hydrocarbons arising from the combustion of alkanes in the internal combustion engine and of their catalytic removal"]'::jsonb,0),
    ('14','14.2','Alkenes','["recall the reactions (including reagents and conditions) by which alkenes can be produced: (a) elimination of HX from a halogenoalkane by ethanolic NaOH and heat (b) dehydration of an alcohol, by using a heated catalyst (e.g. A l 2 O 3 ) or a concentrated acid (e.g. concentrated H 2 SO 4 ) (c) cracking of a longer chain alkane", "describe the following reactions of alkenes: (a) the electrophilic addition of (i) hydrogen in a hydrogenation reaction, H 2 (g) and Pt/Ni catalyst and heat (ii) steam, H 2 O(g) and H 3 PO 4 catalyst (iii) a hydrogen halide, HX(g), at room temperature (iv)\t a halogen, X 2 (b) \tthe oxidation by cold dilute acidified KMnO 4 to form the diol (c) the oxidation by hot concentrated acidified KMnO 4 leading to the rupture of the carbon-carbon double bond and the identities of the subsequent products to determine the position of alkene linkages in larger molecules (d) addition polymerisation exemplified by the reactions of ethene and propene Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('15','15.1','Halogenoalkanes','["recall the reactions (reagents and conditions) by which halogenoalkanes can be produced: (a) the free-radical substitution of alkanes by C l 2 or Br 2 in the presence of ultraviolet light, as exemplified by the reactions of ethane (b) electrophilic addition of an alkene with a halogen, X 2 , or hydrogen halide, HX(g), at room temperature (c) substitution of an alcohol, e.g. by reaction with HX(g); or with KC l and concentrated H 2 SO 4 or concentrated H 3 PO 4 ; or with PC l 3 and heat; or with PC l 5 ; or with SOC l 2", "classify halogenoalkanes into primary, secondary and tertiary", "describe the following nucleophilic substitution reactions: (a)  the reaction with NaOH(aq) and heat to produce an alcohol (b)  the reaction with KCN in ethanol and heat to produce a nitrile (c)  the reaction with NH 3 in ethanol heated under pressure to produce an amine (d)  the reaction with aqueous silver nitrate in ethanol as a method of identifying the halogen present as exemplified by bromoethane", "describe the elimination reaction with NaOH in ethanol and heat to produce an alkene as exemplified by bromoethane", "describe the S N 1 and S N 2 mechanisms of nucleophilic substitution in halogenoalkanes including the inductive effects of alkyl groups", "recall that primary halogenoalkanes tend to react via the S N 2 mechanism; tertiary halogenoalkanes via the S N 1 mechanism; and secondary halogenoalkanes by a mixture of the two, depending on structure", "describe and explain the different reactivities of halogenoalkanes (with particular reference to the relative strengths of the C-X bonds as exemplified by the reactions of halogenoalkanes with aqueous silver nitrates) Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('16','16.1','Alcohols','["recall the reactions (reagents and conditions) by which alcohols can be produced: (a) electrophilic addition of steam to an alkene, H 2 O(g) and H 3 PO 4 catalyst (b) reaction of alkenes with cold dilute acidified potassium manganate( VII ) to form a diol (c) substitution of a halogenoalkane using NaOH(aq) and heat (d) reduction of an aldehyde or ketone using NaBH 4 or LiA l H 4 (e) reduction of a carboxylic acid using LiA l H 4 (f) hydrolysis of an ester using dilute acid or dilute alkali and heat", "describe: (a) the reaction with oxygen (combustion) (b) substitution to form halogenoalkanes, e.g. by reaction with HX(g); or with KC l and concentrated H 2 SO 4 or concentrated H 3 PO 4 ; or with PC l 3 and heat; or with PC l 5 ; or with SOC l 2 (c) \t the reaction with Na(s) (d) \toxidation with acidified K 2 Cr 2 O 7 or acidified KMnO 4 to: (i) carbonyl compounds by distillation (ii) carboxylic acids by refluxing (primary alcohols give aldehydes which can be further oxidised to carboxylic acids, secondary alcohols give ketones, tertiary alcohols cannot be oxidised) (e) dehydration to an alkene, by using a heated catalyst, e.g. A l 2 O 3 or a concentrated acid (f) formation of esters by reaction with carboxylic acids and concentrated H 2 SO 4 as catalyst as exemplified by ethanol", "(a) \t classify alcohols as primary, secondary and tertiary alcohols, to include examples with more than one alcohol group (b) state characteristic distinguishing reactions, e.g. mild oxidation with acidified K 2 Cr 2 O 7 , colour change from orange to green", "deduce the presence of a CH 3 CH(OH)- group in an alcohol, CH 3 CH(OH)-R, from its reaction with alkaline I 2 (aq) to form a yellow precipitate of tri-iodomethane and an ion, RCO 2 -", "explain the acidity of alcohols compared with water Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('17','17.1','Aldehydes and ketones','["recall the reactions (reagents and conditions) by which aldehydes and ketones can be produced: (a) the oxidation of primary alcohols using acidified K 2 Cr 2 O 7 or acidified KMnO 4 and distillation to produce aldehydes (b) the oxidation of secondary alcohols using acidified K 2 Cr 2 O 7 or acidified KMnO 4 and distillation to produce ketones", "describe: (a) the reduction of aldehydes and ketones using NaBH 4 or LiA l H 4 to produce alcohols (b) the reaction of aldehydes and ketones with HCN, KCN as catalyst, and heat to produce hydroxynitriles as exemplified by ethanal and propanone", "describe the mechanism of the nucleophilic addition reactions of hydrogen cyanide with aldehydes and ketones in 17.1.2(b)", "describe the use of 2,4-dinitrophenylhydrazine (2,4-DNPH reagent) to detect the presence of carbonyl compounds", "deduce the nature (aldehyde or ketone) of an unknown carbonyl compound from the results of simple tests (Fehling''s and Tollens'' reagents; ease of oxidation)", "deduce the presence of a CH 3 CO - group in an aldehyde or ketone, CH 3 CO-R, from its reaction with alkaline I 2 (aq) to form a yellow precipitate of tri-iodomethane and an ion, RCO 2 -"]'::jsonb,0),
    ('18','18.1','Carboxylic acids','["recall the reactions by which carboxylic acids can be produced: (a) oxidation of primary alcohols and aldehydes with acidified K 2 Cr 2 O 7 or acidified KMnO 4 and refluxing (b) hydrolysis of nitriles with dilute acid or dilute alkali followed by acidification (c) hydrolysis of esters with dilute acid or dilute alkali  and heat followed by acidification", "describe: (a) the redox reaction with reactive metals to produce a salt and H 2 (g) (b) the neutralisation reaction with alkalis to produce a salt and H 2 O(l ) (c) the acid-base reaction with carbonates to produce a salt and H 2 O(l) and CO 2 (g) (d) esterification with alcohols with concentrated H 2 SO 4 as catalyst (e) reduction by LiA l H 4 to form a primary alcohol Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('18','18.2','Esters','["recall the reaction (reagents and conditions) by which esters can be produced: (a) the condensation reaction between an alcohol and a carboxylic acid with concentrated H₂SO₄ as catalyst", "describe the hydrolysis of esters by dilute acid and by dilute alkali and heat"]'::jsonb,1),
    ('19','19.1','Primary amines','["recall the reactions by which amines can be produced: (a) reaction of a halogenoalkane with NH₃ in ethanol heated under pressure Classification of amines will not be tested at AS Level."]'::jsonb,0),
    ('19','19.2','Nitriles and hydroxynitriles','["recall the reactions by which nitriles can be produced: (a) reaction of a halogenoalkane with KCN in ethanol and heat", "recall the reactions by which hydroxynitriles can be produced: (a) the reaction of aldehydes and ketones with HCN, KCN as catalyst, and heat", "describe the hydrolysis of nitriles with dilute acid or dilute alkali followed by acidification to produce a carboxylic acid"]'::jsonb,1),
    ('20','20.1','Addition polymerisation','["describe addition polymerisation as exemplified by poly(ethene) and poly(chloroethene), PVC", "deduce the repeat unit of an addition polymer obtained from a given monomer", "identify the monomer(s) present in a given section of an addition polymer molecule", "recognise the difficulty of the disposal of poly(alkene)s, i.e. non-biodegradability and harmful combustion products Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('21','21.1','Organic synthesis','["for an organic molecule containing several functional groups: (a) identify organic functional groups using the reactions in the syllabus (b) predict properties and reactions", "devise multi-step synthetic routes for preparing organic molecules using the reactions in the syllabus", "analyse a given synthetic route in terms of type of reaction and reagents used for each step of it, and possible by-products Analysis"]'::jsonb,0),
    ('22','22.1','Infrared spectroscopy','["analyse an infrared spectrum of a simple molecule to identify functional groups (see the Data section for the functional groups required)"]'::jsonb,0),
    ('22','22.2','Mass spectrometry','["analyse mass spectra in terms of m / e values and isotopic abundances (knowledge of the working of the mass spectrometer is not required)", "calculate the relative atomic mass of an element given the relative abundances of its isotopes, or its mass spectrum", "deduce the molecular mass of an organic molecule from the molecular ion peak in a mass spectrum", "suggest the identity of molecules formed by simple fragmentation in a given mass spectrum", "deduce the number of carbon atoms, n , in a compound using the [M + 1] + peak and the formula n = 100 × abundance of [M + 1] + ion 1.1 × abundance of M + ion", "deduce the presence of bromine and chlorine atoms in a compound using the [M + 2] + peak Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Chemistry AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Chemistry' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Chemistry A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2025-2027','9701','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2025-2027', cambridge_code='9701', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'23','Chemical energetics',0),
    (v_org,v_tpl,'24','Electrochemistry',1),
    (v_org,v_tpl,'25','Equilibria',2),
    (v_org,v_tpl,'26','Reaction kinetics',3),
    (v_org,v_tpl,'27','Group 2',4),
    (v_org,v_tpl,'28','Chemistry of transition elements',5),
    (v_org,v_tpl,'29','An introduction to A Level organic chemistry homologous series name of functional group structural formula of functional group displayed formula skeletal formula name',6),
    (v_org,v_tpl,'30','Hydrocarbons',7),
    (v_org,v_tpl,'31','Halogen compounds',8),
    (v_org,v_tpl,'32','Hydroxy compounds',9),
    (v_org,v_tpl,'33','Carboxylic acids and derivatives',10),
    (v_org,v_tpl,'34','Nitrogen compounds',11),
    (v_org,v_tpl,'35','Polymerisation',12),
    (v_org,v_tpl,'36','Organic synthesis',13),
    (v_org,v_tpl,'37','Analytical techniques',14);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('23','23.1','Lattice energy and Born-Haber cycles','["define and use the terms: (a) enthalpy change of atomisation, Δ H at (b) lattice energy, Δ H latt (the change from gas phase ions to solid lattice)", "(a) define and use the term first electron affinity, EA (b) explain the factors affecting the electron affinities of elements (c) describe and explain the trends in the electron affinities of the Group 16 and Group 17 elements", "construct and use Born-Haber cycles for ionic solids (limited to +1 and +2 cations, -1 and -2 anions)", "carry out calculations involving Born-Haber cycles", "explain, in qualitative terms, the effect of ionic charge and of ionic radius on the numerical magnitude of a lattice energy"]'::jsonb,0),
    ('23','23.2','Enthalpies of solution and hydration','["define and use the term enthalpy change with reference to hydration, Δ H hyd , and solution, Δ H sol", "construct and use an energy cycle involving enthalpy change of solution, lattice energy and enthalpy change of hydration", "carry out calculations involving the energy cycles in 23.2.2", "explain, in qualitative terms, the effect of ionic charge and of ionic radius on the numerical magnitude of an enthalpy change of hydration Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('23','23.3','Entropy change, Δ S','["define the term entropy, S , as the number of possible arrangements of the particles and their energy in a given system", "predict and explain the sign of the entropy changes that occur: (a) during a change in state, e.g. melting, boiling and dissolving (and their reverse) (b) during a temperature change (c) during a reaction in which there is a change in the number of gaseous molecules", "calculate the entropy change for a reaction, Δ S , given the standard entropies, S ⦵ , of the reactants and products, Δ S ⦵ = Σ S ⦵ (products) - Σ S ⦵ (reactants) (use of Δ S ⦵ = Δ S surr + Δ S sys is not required)"]'::jsonb,2),
    ('23','23.4','Gibbs free energy change, Δ G','["state and use the Gibbs equation Δ G ⦵ = Δ H ⦵ - T Δ S ⦵", "perform calculations using the equation Δ G ⦵ = Δ H ⦵ - T Δ S ⦵", "state whether a reaction or process will be feasible by using the sign of Δ G", "predict the effect of temperature change on the feasibility of a reaction, given standard enthalpy and entropy changes"]'::jsonb,3),
    ('24','24.1','Electrolysis','["predict the identities of substances liberated during electrolysis from the state of electrolyte (molten or aqueous), position in the redox series (electrode potential) and concentration", "state and apply the relationship F = Le between the Faraday constant, F , the Avogadro constant, L , and the charge on the electron, e", "calculate: (a) the quantity of charge passed during electrolysis, using Q = I t (b) the mass and/or volume of substance liberated during electrolysis", "describe the determination of a value of the Avogadro constant by an electrolytic method ⦵ ⦵ Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('24','24.2','Standard electrode potentials E','["define the terms: (a) standard electrode (reduction) potential (b) standard cell potential", "describe the standard hydrogen electrode", "describe methods used to measure the standard electrode potentials of: (a) metals or non-metals in contact with their ions in aqueous solution (b) ions of the same element in different oxidation states", "calculate a standard cell potential by combining two standard electrode potentials", "use standard cell potentials to: (a) deduce the polarity of each electrode and hence explain/deduce the direction of electron flow in the external circuit of a simple cell (b) predict the feasibility of a reaction", "deduce from E ⦵ values the relative reactivity of elements, compounds and ions as oxidising agents or as reducing agents", "construct redox equations using the relevant half-equations", "predict qualitatively how the value of an electrode potential, E , varies with the concentrations of the aqueous ions", "use the Nernst equation, e.g. E = E ⦵ + (0.059/ z ) log [oxidised species] [reduced species] , to predict quantitatively how the value of an electrode potential varies with the concentrations of the aqueous ions; examples include Cu 2+ (aq) + 2e - ⇌ Cu(s), Fe 3+ (aq) + e - ⇌ Fe 2+ (aq)", "understand and use the equation Δ G ⦵ = - nE ⦵ cell F Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('25','25.1','Acids and bases','["understand and use the terms conjugate acid and conjugate base", "define conjugate acid-base pairs, identifying such pairs in reactions", "define mathematically the terms pH, K a , p K a and K w and use them in calculations ( K b and the equation K w = K a × K b will not be tested)", "calculate [H + (aq)] and pH values for: (a) strong acids (b) strong alkalis (c) weak acids", "(a) define a buffer solution (b) explain how a buffer solution can be made (c) explain how buffer solutions control pH; use chemical equations in these explanations (d) describe and explain the uses of buffer solutions, including the role of HCO 3 - in controlling pH in blood", "calculate the pH of buffer solutions, given appropriate data", "understand and use the term solubility product, K sp", "write an expression for K sp", "calculate K sp from concentrations and vice versa", "(a) understand and use the common ion effect to explain the different solubility of a compound in a solution containing a common ion (b) perform calculations using K sp values and concentration of a common ion"]'::jsonb,0),
    ('25','25.2','Partition coefficients','["state what is meant by the term partition coefficient, K pc", "calculate and use a partition coefficient for a system in which the solute is in the same physical state in the two solvents", "understand the factors affecting the numerical value of a partition coefficient in terms of the polarities of the solute and the solvents used Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('26','26.1','Simple rate equations, orders of reaction and rate constants','["explain and use the terms rate equation, order of reaction, overall order of reaction, rate constant, half-life, rate-determining step and intermediate", "(a) understand and use rate equations of the form rate = k [A] m [B] n (for which m and n are 0, 1 or 2) (b) deduce the order of a reaction from concentration-time graphs or from experimental data relating to the initial rates method and half-life method (c) interpret experimental data in graphical form, including concentration-time and rate-concentration graphs (d) calculate an initial rate using concentration data (e) construct a rate equation", "(a) show understanding that the half-life of a first-order reaction is independent of concentration (b) use the half-life of a first-order reaction in calculations", "calculate the numerical value of a rate constant, for example by: (a) using the initial rates and the rate equation (b) using the half-life, t ½ , and the equation k = 0.693 / t ½", "for a multi-step reaction: (a) suggest a reaction mechanism that is consistent with the rate equation and the equation for the overall reaction (b) predict the order that would result from a given reaction mechanism and rate-determining step (c) deduce a rate equation using a given reaction mechanism and rate-determining step for a given reaction (d) identify an intermediate or catalyst from a given reaction mechanism (e) identify the rate determining step from a rate equation and a given reaction mechanism", "describe qualitatively the effect of temperature change on the rate constant and hence the rate of a reaction"]'::jsonb,0),
    ('26','26.2','Homogeneous and heterogeneous catalysts','["explain that catalysts can be homogeneous or heterogeneous", "describe the mode of action of a heterogeneous catalyst to include adsorption of reactants, bond weakening and desorption of products, for example: (a) iron in the Haber process (b) palladium, platinum and rhodium in the catalytic removal of oxides of nitrogen from the exhaust gases of car engines", "describe the mode of action of a homogeneous catalyst by being used in one step and reformed in a later step, for example: (a) atmospheric oxides of nitrogen in the oxidation of atmospheric sulfur dioxide (b) Fe 2+ or Fe 3+ in the I - /S 2 O 8 2- reaction Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page Inorganic chemistry"]'::jsonb,1),
    ('27','27.1','Similarities and trends in the properties of the Group 2 metals, magnesium to barium, and their compounds','["describe and explain qualitatively the trend in the thermal stability of the nitrates and carbonates including the effect of ionic radius on the polarisation of the large anion", "describe and explain qualitatively the variation in solubility and of enthalpy change of solution, Δ H ⦵ sol , of the hydroxides and sulfates in terms of relative magnitudes of the enthalpy change of hydration and the lattice energy"]'::jsonb,0),
    ('28','28.1','General physical and chemical properties of the first row of transition elements, titanium to copper','["define a transition element as a d-block element which forms one or more stable ions with incomplete d orbitals", "sketch the shape of a 3d xy orbital and 3d z² orbital", "understand that transition elements have the following properties: (a) they have variable oxidation states (b) they behave as catalysts (c) they form complex ions (d) they form coloured compounds", "explain why transition elements have variable oxidation states in terms of the similarity in energy of the 3d and the 4s sub-shells", "explain why transition elements behave as catalysts in terms of having more than one stable oxidation state, and vacant d orbitals that are energetically accessible and can form dative bonds with ligands", "explain why transition elements form complex ions in terms of vacant d orbitals that are energetically accessible Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('28','28.2','General characteristic chemical properties of the first set of transition elements, titanium to copper','["describe and explain the reactions of transition elements with ligands to form complexes, including the complexes of copper( II ) and cobalt( II ) ions with water and ammonia molecules and hydroxide and chloride ions", "define the term ligand as a species that contains a lone pair of electrons that forms a dative covalent bond to a central metal atom / ion", "understand and use the terms: (a) monodentate ligand including as examples H 2 O, NH 3 , C l - and CN - (b) bidentate ligand including as examples 1,2-diaminoethane, en , H 2 NCH 2 CH 2 NH 2 and the ethanedioate ion, C 2 O 4 2- (c) polydentate ligand including as an example EDTA 4-", "define the term complex as a molecule or ion formed by a central metal atom / ion surrounded by one or more ligands", "describe the geometry (shape and bond angles) of transition element complexes which are linear, square planar, tetrahedral or octahedral", "(a) state what is meant by coordination number (b) predict the formula and charge of a complex ion, given the metal ion, its charge or oxidation state, the ligand and its coordination number or geometry", "explain qualitatively that ligand exchange can occur, including the complexes of copper( II ) ions and cobalt( II ) ions with water and ammonia molecules and hydroxide and chloride ions", "predict, using E ⦵ values, the feasibility of redox reactions involving transition elements and their ions", "describe the reactions of, and perform calculations involving: (a) MnO 4 - / C 2 O 4 2- in acid solution given suitable data (b) MnO 4 - / Fe 2+ in acid solution given suitable data (c) Cu 2+ / I - given suitable data 10\t perform calculations involving other redox systems given suitable data"]'::jsonb,1),
    ('28','28.3','Colour of complexes','["define and use the terms degenerate and non-degenerate d orbitals", "describe the splitting of degenerate d orbitals into two non-degenerate sets of d orbitals of higher energy, and use of Δ E in: (a) octahedral complexes, two higher and three lower d orbitals (b) tetrahedral complexes, three higher and two lower d orbitals", "explain why transition elements form coloured compounds in terms of the frequency of light absorbed as an electron is promoted between two non-degenerate d orbitals", "describe, in qualitative terms, the effects of different ligands on Δ E , frequency of light absorbed, and hence the complementary colour that is observed", "use the complexes of copper( II ) ions and cobalt( II ) ions with water and ammonia molecules and hydroxide and chloride ions as examples of ligand exchange affecting the colour observed Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('28','28.4','Stereoisomerism in transition element complexes','["describe the types of stereoisomerism shown by complexes, including those associated with bidentate ligands: (a) geometrical (cis/trans) isomerism, e.g. square planar such as [Pt(NH₃)₂C l ₂] and octahedral such as [Co(NH 3 ) 4 (H 2 O) 2 ] 2+ and [Ni(H 2 NCH 2 CH 2 NH 2 ) 2 (H 2 O) 2 ] 2+ (b) optical isomerism, e.g. [Ni(H 2 NCH 2 CH 2 NH 2 ) 3 ] 2+ and [Ni(H 2 NCH 2 CH 2 NH 2 ) 2 (H 2 O) 2 ] 2+", "deduce the overall polarity of complexes such as those described in 28.4.1(a) and 28.4.1(b)"]'::jsonb,3),
    ('28','28.5','Stability constants, K stab','["define the stability constant, K stab , of a complex as the equilibrium constant for the formation of the complex ion in a solvent (from its constituent ions or molecules)", "write an expression for a K stab of a complex ([H₂O] should not be included)", "use K stab expressions to perform calculations", "describe and explain ligand exchanges in terms of K stab values and understand that a large K stab is due to the formation of a stable complex ion Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page Organic chemistry"]'::jsonb,4),
    ('29','29.1','Formulas, functional groups and the naming of organic compounds','["understand that the compounds in the table on page 47 contain a functional group which dictates their physical and chemical properties", "interpret and use the general, structural, displayed and skeletal formulas of the classes of compound stated in the table on page 47", "understand and use systematic nomenclature of simple aliphatic organic molecules (including cyclic compounds containing a single ring of up to six carbon atoms) with functional groups detailed in the table on page 47, up to six carbon atoms (six plus six for esters and amides, straight chains only for esters and nitriles)", "understand and use systematic nomenclature of simple aromatic molecules with one benzene ring and one or more simple substituents, for example 3-nitrobenzoic acid or 2,4,6-tribromophenol"]'::jsonb,0),
    ('29','29.2','Characteristic organic reactions','["understand and use the following terminology associated with types of organic mechanisms: (a) electrophilic substitution (b) addition-elimination"]'::jsonb,1),
    ('29','29.3','Shapes of aromatic organic molecules; σ and π bonds','["describe and explain the shape of benzene and other aromatic molecules, including sp² hybridisation, in terms of σ bonds and a delocalised π system"]'::jsonb,2),
    ('29','29.4','Isomerism: optical','["understand that enantiomers have identical physical and chemical properties apart from their ability to rotate plane polarised light and their potential biological activity", "understand and use the terms optically active and racemic mixture", "describe the effect on plane polarised light of the two optical isomers of a single substance", "explain the relevance of chirality to the synthetic preparation of drug molecules including: (a) the potential different biological activity of the two enantiomers (b) the need to separate a racemic mixture into two pure enantiomers (c) the use of chiral catalysts to produce a single pure optical isomer (Candidates should appreciate that compounds can contain more than one chiral centre, but knowledge of meso compounds and nomenclature such as diastereoisomers is required.) Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('30','30.1','Arenes','["describe the chemistry of arenes as exemplified by the following reactions of benzene and methylbenzene: (a) substitution reactions with C l ₂ and with Br₂ in the presence of a catalyst, A l C l ₃ or A l Br₃, to form halogenoarenes (aryl halides) (b) nitration with a mixture of concentrated HNO₃ and concentrated H₂SO₄ at a temperature between 25 °C and 60 °C (c) Friedel-Crafts alkylation by CH₃C l and A l C l ₃ and heat (d) Friedel-Crafts acylation by CH₃COC l and A l C l ₃ and heat (e) complete oxidation of the side-chain using hot alkaline KMnO₄ and then dilute acid to give a benzoic acid (f) hydrogenation of the benzene ring using H₂ and Pt/Ni catalyst and heat to form a cyclohexane ring", "describe the mechanism of electrophilic substitution in arenes: (a) as exemplified by the formation of nitrobenzene and bromobenzene (b) with regards to the effect of delocalisation (aromatic stabilisation) of electrons in arenes to explain the predomination of substitution over addition", "predict whether halogenation will occur in the side-chain or in the aromatic ring in arenes depending on reaction conditions", "describe that in the electrophilic substitution of arenes, different substituents direct to different ring positions (limited to the directing effects of -NH₂, -OH, -R, -NO₂, -COOH and -COR)"]'::jsonb,0),
    ('31','31.1','Halogen compounds','["recall the reactions by which halogenoarenes can be produced: substitution of an arene with C l ₂ or Br₂ in the presence of a catalyst, A l C l ₃ or A l Br₃ to form a halogenoarene, exemplified by benzene to form chlorobenzene and methylbenzene to form 2-chloromethylbenzene and 4-chloromethylbenzene", "explain the difference in reactivity between a halogenoalkane and a halogenoarene as exemplified by chloroethane and chlorobenzene Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('32','32.1','Alcohols','["describe the reaction with acyl chlorides to form esters using ethyl ethanoate"]'::jsonb,0),
    ('32','32.2','Phenol','["recall the reactions (reagents and conditions) by which phenol can be produced: (a) reaction of phenylamine with HNO₂ or NaNO₂ and dilute acid below 10 °C to produce the diazonium salt; further warming of the diazonium salt with H₂O to give phenol", "recall the chemistry of phenol, as exemplified by the following reactions: (a) with bases, for example NaOH(aq) to produce sodium phenoxide (b) with Na(s) to produce sodium phenoxide and H 2 (g) (c) in NaOH(aq) with diazonium salts, to give azo compounds (d) nitration of the aromatic ring with dilute HNO₃(aq) at room temperature to give a mixture of 2-nitrophenol and 4-nitrophenol (e) bromination of the aromatic ring with Br₂(aq) to form 2,4,6-tribromophenol", "explain the acidity of phenol", "describe and explain the relative acidities of water, phenol and ethanol", "explain why the reagents and conditions for the nitration and bromination of phenol are different from those for benzene", "recall that the hydroxyl group of a phenol directs to the 2-, 4- and 6-positions", "apply knowledge of the reactions of phenol to those of other phenolic compounds, e.g. naphthol"]'::jsonb,1),
    ('33','33.1','Carboxylic acids','["recall the reaction by which benzoic acid can be produced: (a) reaction of an alkylbenzene with hot alkaline KMnO₄ and then dilute acid, exemplified by methylbenzene", "describe the reaction of carboxylic acids with PC l ₃ and heat, PC l ₅ or SOC l ₂ to form acyl chlorides", "recognise that some carboxylic acids can be further oxidised: (a) the oxidation of methanoic acid, HCOOH, with Fehling''s reagent or Tollens'' reagent or acidified KMnO₄ or acidified K₂Cr₂O₇ to carbon dioxide and water (b) the oxidation of ethanedioic acid, HOOCCOOH, with warm acidified KMnO₄ to carbon dioxide", "describe and explain the relative acidities of carboxylic acids, phenols and alcohols", "describe and explain the relative acidities of chlorine-substituted carboxylic acids Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('33','33.2','Esters','["recall the reaction by which esters can be produced: (a) reaction of alcohols with acyl chlorides using the formation of ethyl ethanoate and phenyl benzoate as examples"]'::jsonb,1),
    ('33','33.3','Acyl chlorides','["recall the reactions (reagents and conditions) by which acyl chlorides can be produced: (a) reaction of carboxylic acids with PC l ₃ and heat, PC l ₅ or SOC l ₂", "describe the following reactions of acyl chlorides: (a) hydrolysis on addition of water at room temperature to give the carboxylic acid and HC l (b) reaction with an alcohol at room temperature to produce an ester and HC l (c) reaction with phenol at room temperature to produce an ester and HC l (d) reaction with ammonia at room temperature to produce an amide and HC l (e) reaction with a primary or secondary amine at room temperature to produce an amide and HC l", "describe the addition-elimination mechanism of acyl chlorides in reactions in 33.3.2(a)-(e)", "explain the relative ease of hydrolysis of acyl chlorides, alkyl chlorides and halogenoarenes (aryl chlorides)"]'::jsonb,2),
    ('34','34.1','Primary and secondary amines','["recall the reactions (reagents and conditions) by which primary and secondary amines are produced: (a) reaction of halogenoalkanes with NH₃ in ethanol heated under pressure (b) reaction of halogenoalkanes with primary amines in ethanol, heated in a sealed tube / under pressure (c) the reduction of amides with LiA l H₄ (d) the reduction of nitriles with LiA l H₄ or H₂ / Ni", "describe the condensation reaction of ammonia or an amine with an acyl chloride at room temperature to give an amide", "describe and explain the basicity of aqueous solutions of amines Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('34','34.2','Phenylamine and azo compounds','["describe the preparation of phenylamine via the nitration of benzene to form nitrobenzene followed by reduction with hot Sn/concentrated HC l followed by NaOH(aq)", "describe: (a) the reaction of phenylamine with Br₂(aq) at room temperature (b) the reaction of phenylamine with HNO₂ or NaNO₂ and dilute acid below 10 °C to produce the diazonium salt; further warming of the diazonium salt with H₂O to give phenol", "describe and explain the relative basicities of aqueous ammonia, ethylamine and phenylamine", "recall the following about azo compounds: (a) describe the coupling of benzenediazonium chloride with phenol in NaOH(aq) to form an azo compound (b) identify the azo group (c) state that azo compounds are often used as dyes (d) that other azo dyes can be formed via a similar route"]'::jsonb,1),
    ('34','34.3','Amides','["recall the reactions (reagents and conditions) by which amides are produced: (a) the reaction between ammonia and an acyl chloride at room temperature (b) the reaction between a primary amine and an acyl chloride at room temperature", "describe the reactions of amides: (a) hydrolysis with aqueous alkali or aqueous acid (b) the reduction of the CO group in amides with LiA l H₄ to form an amine", "state and explain why amides are much weaker bases than amines"]'::jsonb,2),
    ('34','34.4','Amino acids','["describe the acid / base properties of amino acids and the formation of zwitterions, to include the isoelectric point", "describe the formation of amide (peptide) bonds between amino acids to give di- and tripeptides", "interpret and predict the results of electrophoresis on mixtures of amino acids and dipeptides at varying pHs (the assembling of the apparatus will not be tested) Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('35','35.1','Condensation polymerisation','["describe the formation of polyesters: (a) the reaction between a diol and a dicarboxylic acid or dioyl chloride (b) the reaction of a hydroxycarboxylic acid", "describe the formation of polyamides: (a) the reaction between a diamine and a dicarboxylic acid or dioyl chloride (b) the reaction of an aminocarboxylic acid (c) \t the reaction between amino acids", "deduce the repeat unit of a condensation polymer obtained from a given monomer or pair of monomers", "identify the monomer(s) present in a given section of a condensation polymer molecule"]'::jsonb,0),
    ('35','35.2','Predicting the type of polymerisation','["predict the type of polymerisation reaction for a given monomer or pair of monomers", "deduce the type of polymerisation reaction which produces a given section of a polymer molecule"]'::jsonb,1),
    ('35','35.3','Degradable polymers','["recognise that poly(alkenes) are chemically inert and can therefore be difficult to biodegrade", "recognise that some polymers can be degraded by the action of light", "recognise that polyesters and polyamides are biodegradable by acidic and alkaline hydrolysis"]'::jsonb,2),
    ('36','36.1','Organic synthesis','["for an organic molecule containing several functional groups: (a) identify organic functional groups using the reactions in the syllabus (b) predict properties and reactions", "devise multi-step synthetic routes for preparing organic molecules using the reactions in the syllabus", "analyse a given synthetic route in terms of type of reaction and reagents used for each step of it, and possible by-products Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page Analysis"]'::jsonb,0),
    ('37','37.1','Thin-layer chromatography','["describe and understand the terms (a) stationary phase, for example aluminium oxide (on a solid support) (b) \tmobile phase; a polar or non-polar solvent (c) R f value (d) \tsolvent front and baseline", "interpret R f values", "explain the differences in R f values in terms of interaction with the stationary phase and of relative solubility in the mobile phase"]'::jsonb,0),
    ('37','37.2','Gas / liquid chromatography','["describe and understand the terms (a) stationary phase; a high boiling point non-polar liquid (on a solid support) (b) mobile phase; an unreactive gas (c) retention time", "interpret gas / liquid chromatograms in terms of the percentage composition of a mixture", "explain retention times in terms of interaction with the stationary phase"]'::jsonb,1),
    ('37','37.3','Carbon-13 NMR spectroscopy','["analyse and interpret a carbon-13 NMR spectrum of a simple molecule to deduce: (a) the different environments of the carbon atoms present (b) the possible structures for the molecule", "predict or explain the number of peaks in a carbon-13 NMR spectrum for a given molecule Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('37','37.4','Proton ( 1 H) NMR spectroscopy','["analyse and interpret a proton ( 1 H) NMR spectrum of a simple molecule to deduce: (a) the different environments of proton present using chemical shift values (b) the relative numbers of each type of proton present from relative peak areas (c) the number of equivalent protons on the carbon atom adjacent to the one to which the given proton is attached from the splitting pattern, using the n + 1 rule (limited to singlet, doublet, triplet, quartet and multiplet) (d) the possible structures for the molecule", "predict the chemical shifts and splitting patterns of the protons in a given molecule", "describe the use of tetramethylsilane, TMS, as the standard for chemical shift measurements", "state the need for deuterated solvents, e.g. CDC l ₃, when obtaining a proton NMR spectrum", "describe the identification of O-H and N-H protons by proton exchange using D₂O Cambridge International AS & A Level Chemistry 9701 syllabus for 2025, 2026 and 2027.", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Chemistry A2';
END $$;
