-- Economics (9708) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Economics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Economics AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','9708','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='9708', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Basic economic ideas and resource allocation',0),
    (v_org,v_tpl,'2','The price system and the microeconomy',1),
    (v_org,v_tpl,'3','Government microeconomy intervention',2),
    (v_org,v_tpl,'4','The Macroeconomy',3),
    (v_org,v_tpl,'5','Government macroeconomic intervention',4),
    (v_org,v_tpl,'6','International economic issues',5);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Scarcity, choice and opportunity cost','["fundamental economic problem of scarcity", "need to make choices at all levels (individuals, firms, governments)", "nature and definition of opportunity cost, arising from choices", "basic questions of resource allocation • what to produce • how to produce • for whom to produce"]'::jsonb,0),
    ('1','1.2','Economic methodology','["economics as a social science", "positive and normative statements (the distinction between facts and value judgements)", "meaning of the term ceteris paribus", "importance of the time period (short run, long run, very long run) Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 16 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('1','1.3','Factors of production','["nature and definition of factors of production: land, labour, capital and enterprise", "difference between human capital and physical capital", "rewards to the factors of production", "division of labour and specialisation", "role of the entrepreneur in contemporary economies: risk and organisation of the other factors of production"]'::jsonb,2),
    ('1','1.4','Resource allocation in different economic systems','["decision-making in market, planned and mixed economies", "resource allocation in these economic systems"]'::jsonb,3),
    ('1','1.5','Production possibility curves','["nature and meaning of a production possibility curve (PPC)", "shape of the PPC: constant and increasing opportunity costs", "causes and consequences of shifts in a PPC", "significance of a position within a PPC"]'::jsonb,4),
    ('1','1.6','Classification of goods and services','["nature and definition of free goods and private goods (economic goods)", "nature and definition of public goods", "nature and definition of merit goods: under-consumption as a result of imperfect information in the market", "nature and definition of demerit goods: over-consumption as a result of imperfect information in the market Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 17 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,5),
    ('2','2.1','Demand and supply curves','["effective demand", "individual and market demand and supply", "determinants of demand", "determinants of supply", "causes of a shift in the demand curve (D)", "causes of a shift in the supply curve (S)", "distinction between the shift in the demand or supply curve and the movement along these curves"]'::jsonb,0),
    ('2','2.2','Price elasticity, income elasticity and cross elasticity of demand','["definition of price elasticity, income elasticity and cross elasticity of demand (PED, YED, XED)", "formulae for and calculation of price elasticity, income elasticity and cross elasticity of demand", "significance of relative percentage changes, the size and sign of the coefficient of: • price elasticity of demand • income elasticity of demand • cross elasticity of demand", "descriptions of elasticity values: perfectly elastic, (highly) elastic, unitary elasticity, (highly) inelastic, perfectly inelastic", "variation in price elasticity of demand along the length of a straight-line demand curve", "factors affecting: • price elasticity of demand • income elasticity of demand • cross elasticity of demand", "relationship between price elasticity of demand and total expenditure on a product", "implications for decision-making of price elasticity, income elasticity and cross elasticity of demand Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 18 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('2','2.3','Price elasticity of supply','["definition of price elasticity of supply (PES)", "formula for and calculation of price elasticity of supply", "significance of relative percentage changes, the size and sign of the coefficient of price elasticity of supply", "factors affecting price elasticity of supply", "implications for speed and ease with which firms react to changed market conditions"]'::jsonb,2),
    ('2','2.4','The interaction of demand and supply','["definition of market equilibrium and disequilibrium", "effects of shifts in demand and supply curves on equilibrium price and quantity", "relationships between different markets: • joint demand (complements) • alternative demand (substitutes) • derived demand • joint supply", "functions of price in resource allocation; rationing, signalling (transmission of preferences) and incentivising"]'::jsonb,3),
    ('2','2.5','Consumer and producer surplus','["meaning and significance of consumer surplus", "meaning and significance of producer surplus", "causes of changes in consumer and producer surplus", "significance of price elasticity of demand and of supply in determining the extent of these changes"]'::jsonb,4),
    ('3','3.1','Reasons for government intervention in markets','["addressing the non-provision of public goods", "addressing the over-consumption of demerit goods and the under-consumption of merit goods", "controlling prices in markets Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 19 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('3','3.2','Methods and effects of government intervention in markets','["impact and incidence of specific indirect taxes", "impact and incidence of subsidies", "direct provision of goods and services", "maximum and minimum prices", "buffer stock schemes", "provision of information"]'::jsonb,1),
    ('3','3.3','Addressing income and wealth inequality','["difference between income as a flow concept and wealth as a stock concept", "measuring income and wealth inequality: • Gini coefficient (calculation not required)", "economic reasons for inequality of income and wealth", "policies to redistribute income and wealth: • minimum wage • transfer payments • progressive income taxes, inheritance and capital taxes • state provision of essential goods and services"]'::jsonb,2),
    ('4','4.1','National income statistics','["meaning of national income", "measurement of national income: • Gross Domestic Product (GDP) • Gross National Income (GNI) • Net National Income (NNI)", "adjustment of measures from market prices to basic prices", "adjustment of measures from gross values to net values Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 20 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('4','4.2','Introduction to the circular flow of income','["circular flow of income in a closed economy and an open economy: the flow of income between households, firms and government and the international economy", "injections and leakages (multiplier not required)", "equilibrium and disequilibrium (marginal and average propensities not required)"]'::jsonb,1),
    ('4','4.3','Aggregate Demand and Aggregate Supply analysis','["definition of Aggregate Demand (AD)", "components of AD and their meanings: AD = C + I + G + (X - M)", "determinants of AD (detailed knowledge of the components of AD is not required)", "shape of the AD curve (downward sloping)", "causes of a shift in the AD curve", "definition of Aggregate Supply (AS)", "determinants of AS", "shape of the AS curve in the short run (SRAS, upward sloping line or sweeping curve) and the long run (LRAS, either a vertical line or in three sections - highly elastic, upward sloping, vertical)", "causes of a shift in the AS curve in the short run (SRAS) and in the long run (LRAS)", "distinction between a movement along and a shift in AD and AS", "establishment of equilibrium in the AD/AS model and the determination of the level of real output, the price level and employment", "effects of shifts in the AD curve and the AS curve on the level of real output, the price level and employment"]'::jsonb,2),
    ('4','4.4','Economic growt h','["meaning of economic growth", "measurement of economic growth", "distinction between growth in nominal GDP and real GDP", "causes of economic growth", "consequences of economic growth"]'::jsonb,3),
    ('4','4.5','Unemployment','["meaning of unemployment", "measures of unemployment, with reference to possible difficulties in measurement", "causes and types of unemployment: frictional, structural, cyclical, seasonal and technological", "consequences of unemployment Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 21 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,4),
    ('4','4.6','Price stability','["definition of inflation, deflation and disinflation", "measurement of changes in the price level: • consumer price index (CPI) • possible difficulties in measurement", "distinction between money values (nominal) and real data", "causes of inflation: cost-push and demand-pull inflation", "consequences of inflation"]'::jsonb,5),
    ('5','5.1','Government macroeconomic policy objectives','["use of government policy to achieve macroeconomic objectives: price stability, low unemployment, economic growth (policy conflicts and trade-offs are not required)"]'::jsonb,0),
    ('5','5.2','Fiscal policy','["meaning of government budget", "distinction between a government budget deficit and a government budget surplus", "meaning and significance of the national debt", "taxation: • types of taxes: direct/indirect, progressive/regressive/proportional • rates of tax: marginal and average rates of taxation (mrt, art) • reasons for taxation", "government spending: • types of spending: capital (investment) and current • reasons for government spending", "distinction between expansionary and contractionary fiscal policy", "AD/AS analysis of the impact of expansionary and contractionary fiscal policy on the equilibrium level of national income and the level of real output, the price level and employment Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 22 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('5','5.3','Monetary policy','["definition of monetary policy", "tools of monetary policy: interest rates, money supply and credit regulations", "distinction between expansionary and contractionary monetary policy", "AD/AS analysis of the impact of expansionary and contractionary monetary policy on the equilibrium national income and the level of real output, the price level and employment"]'::jsonb,2),
    ('5','5.4','Supply-side policy','["meaning of supply-side policy, in terms of its effect on LRAS curves", "objectives of supply-side policy: increasing productivity and productive capacity", "tools of supply-side policy, for example training, infrastructure development, support for technological improvement", "AD/AS analysis of the impact of supply-side policy on the equilibrium national income and the level of real output, the price level and employment"]'::jsonb,3),
    ('6','6.1','The reasons for international trade','["distinction between absolute and comparative advantage", "benefits of specialisation and free trade (trade liberalisation), including the trading possibility curve", "exports, imports and the terms of trade: • measurement of the terms of trade • causes of changes in the terms of trade • impact of changes in the terms of trade", "limitations of the theories of absolute and comparative advantage"]'::jsonb,0),
    ('6','6.2','Protectionism','["meaning of protectionism in the context of international trade", "different tools of protection and their impact: • tariffs • import quotas • export subsidies • embargoes • excessive administrative burdens (''red tape'')", "arguments for and against protectionism Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 23 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('6','6.3','Current account of the balance of payments','["components of the current account of the balance of payments: • current account: trade in goods, trade in services, primary income and secondary income • definition of balance and imbalances (deficit and surplus) in the current account of the balance of payments", "calculation of: • balance of trade in goods • balance of trade in services • balance of trade in goods and services • current account balance (CAB)", "causes of imbalances in the current account of the balance of payments", "consequences of imbalances in the current account of the balance of payments for the domestic and external economy"]'::jsonb,2),
    ('6','6.4','Exchange rates','["definition of exchange rate", "determination of a floating exchange rate", "distinction between depreciation and appreciation of a floating exchange rate", "causes of changes in a floating exchange rate: demand and supply of the currency", "AD/AS analysis of the impact of exchange rate changes on the domestic economy''s equilibrium national income and the level of real output, the price level and employment"]'::jsonb,3),
    ('6','6.5','Policies to correct imbalances in the current account of the balance of payments','["government policy objective of stability of the current account", "effect of fiscal, monetary, supply-side and protectionist policies on the current account Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 24 www.cambridgeinternational.org/alevel Back to contents page A Level content"]'::jsonb,4)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Economics AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Economics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Economics A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2028','9708','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2028', cambridge_code='9708', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'7','The price system and the microeconomy',0),
    (v_org,v_tpl,'8','Government microeconomic intervention',1),
    (v_org,v_tpl,'9','The macroeconomy',2),
    (v_org,v_tpl,'10','Government macroeconomic intervention',3),
    (v_org,v_tpl,'11','International economic issues',4);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('7','7.1','Utility','["definition and calculation of total utility and marginal utility", "diminishing marginal utility", "equi-marginal principle", "derivation of an individual demand curve", "limitations of marginal utility theory and its assumptions of rational behaviour"]'::jsonb,0),
    ('7','7.2','Indifference curves and budget lines','["meaning of an indifference curve and a budget line", "causes of a shift in the budget line", "income, substitution and price effects for normal, inferior and Giffen goods", "limitations of the model of indifference curves"]'::jsonb,1),
    ('7','7.3','Efficiency and market failure','["definitions of productive efficiency and allocative efficiency", "conditions for productive efficiency and allocative efficiency", "Pareto optimality", "definition of dynamic efficiency", "definition of market failure", "reasons for market failure"]'::jsonb,2),
    ('7','7.4','Private costs and benefits, externalities and social costs and benefits','["definition and calculation of social costs (SC) as the sum of private costs (PC) and external costs (EC), including marginal social costs (MSC), marginal private costs (MPC) and marginal external costs (MEC)", "definition and calculation of social benefits (SB) as the sum of private benefits (PB) and external benefits (EB), including marginal social benefits (MSB), marginal private benefits (MPB) and marginal external benefits (MEB)", "definition of positive externality and negative externality", "positive and negative externalities of both consumption and production", "deadweight welfare losses arising from positive and negative externalities", "asymmetric information and moral hazard", "use of costs and benefits in analysing decisions (knowledge of net present value is not required) Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 25 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('7','7.5','Types of cost, revenue and profit, short-run and long-run production','["short-run production function: • fixed and variable factors of production • definition and calculation of total product, average product and marginal product • law of diminishing returns (law of variable proportions)", "short-run cost function: • definition and calculation of fixed costs (FC) and variable costs (VC) • definition and calculation of total, average and marginal costs (TC, AC, MC), including average total  cost (ATC), total and average fixed costs (TFC, AFC) and total and average variable costs (TVC, AVC) • explanation of shape of short-run average cost and marginal cost curves", "long-run production function: • no fixed factors of production • returns to scale", "long-run cost function: • explanation of shape of long-run average cost curve • concept of minimum efficient scale", "relationship between economies of scale and decreasing average costs", "internal and external economies of scale", "internal and external diseconomies of scale", "definition and calculation of revenue: total, average and marginal revenue (TR, AR, MR)", "definition of normal, subnormal and supernormal profit", "calculation of supernormal and subnormal profit"]'::jsonb,4),
    ('7','7.6','Different market structures','["perfect competition and imperfect competition: monopoly, monopolistic competition, oligopoly, natural monopoly", "structure of the listed markets as explained by number of buyers and sellers, product differentiation, degree of freedom of entry and availability of information", "barriers to entry and exit: • legal barriers • market barriers • cost barriers • physical barriers Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 26 www.cambridgeinternational.org/alevel Back to contents page", "performance of firms in different market structures: • revenues and revenue curves • output in the short run and the long run • profits in the short run and the long run • shutdown price in the short run and the long run • derivation of a firm''s supply curve in a perfectly competitive market • efficiency and X-inefficiency in the short run and the long run • contestable markets: features and implications • price competition and non-price competition • collusion and the Prisoner''s Dilemma in oligopolistic markets, including a two-player pay-off matrix", "definition and calculation of the concentration ratio"]'::jsonb,5),
    ('7','7.7','Growth and survival of firms','["reasons for different sizes of firms", "internal growth of firms: organic growth and diversification", "external growth of firms - integration (mergers and takeovers): • methods of integration: - horizontal - vertical (forwards and backwards) - conglomerate • reasons for integration • consequences of integration", "cartels: • conditions for an effective cartel • consequences of a cartel", "principal-agent problem arising from differing objectives of shareholders/owners and managers Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 27 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,6),
    ('7','7.8','Differing objectives and policies of firms','["traditional profit-maximising objective of firms", "an understanding of other objectives of firms: • survival • profit satisficing • sales maximisation • revenue maximisation", "price discrimination - first, second and third degree: • conditions for effective price discrimination • consequences of price discrimination", "other pricing policies: • limit pricing • predatory pricing • price leadership", "relationship between price elasticity of demand and a firm''s revenue: • in a normal downward sloping demand curve • in a kinked demand curve"]'::jsonb,7),
    ('8','8.1','Government policies to achieve efficient resource allocation and correct market failure','["application and effectiveness of measures to tackle different forms of market failure: • specific and ad valorem indirect taxes • subsidies • price controls • production quotas • prohibitions and licences • regulation and deregulation • direct provision • pollution permits • property rights • nationalisation and privatisation • provision of information • behavioural insights and ''nudge'' theory Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 28 www.cambridgeinternational.org/alevel Back to contents page", "government failure in microeconomic intervention: • definition of government failure • causes of government failure • consequences of government failure"]'::jsonb,0),
    ('8','8.2','Equity and redistribution of income and wealth','["difference between equity and equality", "difference between equity and efficiency", "distinction between absolute poverty and relative poverty", "the poverty trap", "policies towards equity and equality, for example: • negative income tax • universal benefits and means-tested benefits • universal basic income"]'::jsonb,1),
    ('8','8.3','Labour market forces and government intervention','["demand for labour as a derived demand", "factors affecting demand for labour in a firm or an occupation", "causes of shifts in and movement along the demand curve for labour in a firm or an occupation", "marginal revenue product (MRP) theory: • definition and calculation of marginal revenue product • derivation of an individual firm''s demand for labour using marginal revenue product", "factors affecting the supply of labour to a firm or to an occupation: • wage and non-wage factors", "causes of shifts in and movement along the supply curve of labour to a firm or an occupation", "wage determination in perfect markets: • equilibrium wage rate and employment in a labour market", "wage determination in imperfect markets: • influence of trade unions on wage determination and employment in a labour market • influence of government on wage determination and employment in a labour market using a national minimum wage • influence of monopsony employers on wage determination and employment in a labour market", "determination of wage differentials by labour market forces", "transfer earnings and economic rent: • definition of transfer earnings • definition of economic rent • factors affecting transfer earnings and economic rent in an occupation Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 29 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('9','9.1','The circular flow of income','["the multiplier process: • definition of the multiplier • formulae for and calculation of multiplier in a closed and open economy, with and without a government sector • calculation of: - average and marginal propensities to save (aps and mps) - average and marginal propensities to consume (apc and mpc) - average and marginal propensities to import (apm and mpm) - average and marginal rates of tax (art and mrt) • national income determination using AD and income approach with the multiplier process • calculation of effect of changing AD on national income using the multiplier", "components of Aggregate Demand (AD) and their determinants: • consumption function: autonomous and induced consumer expenditure • savings function: autonomous and induced savings • autonomous and induced investment; the accelerator • government spending • net exports (exports minus imports)", "full employment level of national income and equilibrium level of national income: • inflationary and deflationary gaps Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 30 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('9','9.2','Economic growth and sustainability','["actual growth versus potential growth in national output", "positive and negative output gaps", "business (trade) cycle: • phases of the cycle • causes of the cycle • role of automatic stabilisers", "policies to promote economic growth and their effectiveness", "inclusive economic growth: • definition of inclusive economic growth • impact of economic growth on equity and equality • policies to promote inclusive growth", "sustainable economic growth: • definition of sustainable economic growth • using and conserving resources • impact of economic growth on the environment and climate change • policies to mitigate  the impact of economic growth on the environment and climate change"]'::jsonb,1),
    ('9','9.3','Employment/unemployment','["definition of full employment", "equilibrium and disequilibrium unemployment (including hysteresis)", "voluntary and involuntary unemployment", "natural rate of unemployment: • definition • determinants • policy implications", "patterns and trends in (un)employment", "mobility of labour: • forms of labour mobility: geographical and occupational • factors affecting labour mobility", "policies to reduce unemployment and their effectiveness Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 31 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('10','10.1','Government macroeconomic policy objectives','["objectives in terms of inflation, balance of payments, unemployment, growth, development, sustainability and redistribution of income and wealth"]'::jsonb,0),
    ('10','10.2','Links between macroeconomic problems and their interrelatedness','["relationship between the internal value of money and the external value of money", "relationship between the balance of payments and inflation", "relationship between growth and inflation", "relationship between growth and the balance of payments", "relationship between inflation and unemployment: • traditional Phillips curve • expectations-augmented Phillips curve (short- and long-run Phillips curve) Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 32 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('10','10.3','Effectiveness of policy options to meet all macroeconomic objectives','["effectiveness of different policies in relation to different macroeconomic objectives: • fiscal policy including Laffer curve analysis • monetary policy • supply-side policy including market-based and interventionist policies • exchange rate policy • international trade policy", "problems and conflicts arising from the outcome of these policies", "existence of government failure in macroeconomic policies"]'::jsonb,2),
    ('11','11.1','Policies to correct disequilibrium in the balance of payments','["components of the balance of payments accounts: current account, financial account and capital account", "effect of fiscal, monetary, supply-side, protectionist and exchange rate policies on the balance of payments", "difference between expenditure-switching and expenditure-reducing policies"]'::jsonb,0),
    ('11','11.2','Exchange rates','["measurement of exchange rates: • distinction between nominal and real exchange rates • trade-weighted exchange rates", "determination of exchange rates under fixed and managed systems", "distinction between revaluation and devaluation of a fixed exchange rate", "changes in the exchange rate under different exchange rate systems", "the effects of changing exchange rates on the external economy using Marshall-Lerner and J curve analysis Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 33 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('11','11.3','Economic development','["classification of economies in terms of their level of development", "classification of economies in terms of their level of national income", "indicators of living standards and economic development: • monetary indicators including real per capita national income statistics (GDP, GNI, NNI) and purchasing power parity • issues of comparison using monetary indicators • non-monetary indicators • composite indicators: - Human Development Index (HDI) - Measure of Economic Welfare (MEW) - Multidimensional Poverty Index (MPI) • the Kuznets curve", "comparison of economic growth rates and living standards: • over time • between countries"]'::jsonb,2),
    ('11','11.4','Characteristics of countries at different levels of development','["population growth and structure: • measurement and causes of changes in birth rate, death rate, infant mortality and net migration • optimum population • level of urbanisation", "income distribution: • calculation of Gini coefficient and Lorenz curve analysis", "economic structure: • employment composition: primary, secondary and tertiary sectors • pattern of trade at different levels of development Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. Subject content 34 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('11','11.5','Relationship between countries at different levels of development','["international aid: • forms of aid • reasons for giving aid • effects of aid • importance of aid", "trade and investment", "role of multinational companies (MNCs): • definition of MNC • activities of MNCs • consequences of MNCs", "Foreign Direct Investment (FDI): • definition of FDI • consequences of FDI", "external debt: • causes of debt • consequences of debt", "role of the International Monetary Fund (IMF)", "role of the World Bank"]'::jsonb,4),
    ('11','11.6','Globalisation','["meaning of globalisation and its causes and consequences", "distinction between a free trade area, a customs union, a monetary union and full economic union", "trade creation and trade diversion Cambridge International AS & A Level Economics 9708 syllabus for 2026, 2027 and 2028. 35 www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,5)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Economics A2';
END $$;
