-- Further Mathematics (9231) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Further Mathematics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Further Mathematics AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2027','9231','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2027', cambridge_code='9231', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Further Pure Mathematics 1',0),
    (v_org,v_tpl,'3','Further Mechanics',1),
    (v_org,v_tpl,'4','Further Probability & Statistics',2);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Roots of polynomial equations','["recall and use the relations between the roots and coefficients of polynomial equations", "use a substitution to obtain an equation whose roots are related in a simple way to those of the original equation"]'::jsonb,0),
    ('1','1.2','Rational functions and graphs','["sketch graphs of simple rational functions, including the determination of oblique asymptotes, in cases where the degree of the numerator and the denominator are at most 2", "understand and use relationships between the graphs of y = f( x ) , y 2 = f( x ) , y x 1 f = ^ h , y x f = ^ h and y x f = ^ h ."]'::jsonb,1),
    ('1','1.3','Summation of series','["use the standard results for r / , r 2 / , r 3 / to find related sums", "use the method of differences to obtain the sum of a finite series", "recognise, by direct consideration of a sum to n terms, when a series is convergent, and find the sum to infinity in such cases Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 1 Further Pure Mathematics 1"]'::jsonb,2),
    ('1','1.4','Matrices','["carry out operations of matrix addition, subtraction and multiplication, and recognise the terms zero matrix and identity (or unit) matrix", "recall the meaning of the terms ''singular'' and ''non-singular'' as applied to square matrices and, for 2 2 # and 3 3 # matrices, evaluate determinants and find inverses of non-singular matrices", "understand and use the result, for non-singular matrices, ( AB ) -1 = B -1 A -1", "understand the use of 2 2 # matrices to represent certain geometric transformations in the x-y plane, in particular - understand the relationship between the transformations represented by A and A -1 - recognise that the matrix product AB represents the transformation that results from the transformation represented by B followed by the transformation represented by A - recall how the area scale factor of a transformation is related to the determinant of the corresponding matrix - find the matrix that represents a given transformation or sequence of transformations", "understand the meaning of ''invariant'' as applied to points and lines in the context of transformations represented by matrices, and solve simple problems involving invariant points and invariant lines. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 1 Further Pure Mathematics 1"]'::jsonb,3),
    ('1','1.5','Polar coordinates','["understand the relations between Cartesian and polar coordinates, and convert equations of curves from Cartesian to polar form and vice versa", "sketch simple polar curves, for 0 2 < G r i or 1 G − r r i or a subset of either of these intervals", "recall the formula r d 2 1 2 i y for the area of a sector, and use this formula in simple cases."]'::jsonb,4),
    ('1','1.6','Vectors','["use the equation of a plane in any of the forms ax + by + cz = d or r.n = p or r = a + λ b + μ c and convert equations of planes from one form to another as necessary in solving problems", "recall that the vector product a b # of two vectors can be expressed either as sin a b n i t , where n t is a unit vector, or in component form as a b a b a b a b i j 2 3 3 2 3 1 1 3 − − + ` ` j j a b a b k 1 2 2 1 − + ` j", "use equations of lines and planes, together with scalar and vector products where appropriate, to solve problems concerning distances, angles and intersections, including - determining whether a line lies in a plane, is parallel to a plane or intersects a plane, and finding the point of intersection of a line and a plane when it exists - finding the foot of the perpendicular from a point to a plane - finding the angle between a line and a plane, and the angle between two planes - finding an equation for the line of intersection of two planes - calculating the shortest distance between two skew lines - finding an equation for the common perpendicular to two skew lines. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 1 Further Pure Mathematics 1"]'::jsonb,5),
    ('1','1.7','Proof by induction','["use the method of mathematical induction to establish a given result", "recognise situations where conjecture based on a limited trial followed by inductive proof is a useful strategy, and carry this out in simple cases. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 2"]'::jsonb,6),
    ('3','3.1','Motion of a projectile','["model the motion of a projectile as a particle moving with constant acceleration and understand any limitations of the model", "use horizontal and vertical equations of motion to solve problems on the motion of projectiles, including finding the magnitude and direction of the velocity at a given time or position, the range on a horizontal plane and the greatest height reached", "derive and use the Cartesian equation of the trajectory of a projectile, including problems in which the initial speed and/or angle of projection may be unknown."]'::jsonb,0),
    ('3','3.2','Equilibrium of a rigid body','["calculate the moment of a force about a point", "use the result that the effect of gravity on a rigid body is equivalent to a single force acting at the centre of mass of the body, and identify the position of the centre of mass of a uniform body using considerations of symmetry", "use given information about the position of the centre of mass of a triangular lamina and other simple shapes", "determine the position of the centre of mass of a composite body by considering an equivalent system of particles", "use the principle that if a rigid body is in equilibrium under the action of coplanar forces then the vector sum of the forces is zero and the sum of the moments of the forces about any point is zero, and the converse of this", "solve problems involving the equilibrium of a single rigid body under the action of coplanar forces, including those involving toppling or sliding. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 3 Further Mechanics"]'::jsonb,1),
    ('3','3.3','Circular motion','["understand the concept of angular speed for a particle moving in a circle, and use the relation v r ~ =", "understand that the acceleration of a particle moving in a circle with constant speed is directed towards the centre of the circle, and use the formulae r 2 ~ and r v 2 .", "solve problems which can be modelled by the motion of a particle moving in a horizontal circle with constant speed", "solve problems which can be modelled by the motion of a particle in a vertical circle without loss of energy."]'::jsonb,2),
    ('3','3.4','Hooke''s law','["use Hooke''s law as a model relating the force in an elastic string or spring to the extension or compression, and understand the term modulus of elasticity", "use the formula for the elastic potential energy stored in a string or spring", "solve problems involving forces due to elastic strings or springs, including those where considerations of work and energy are needed."]'::jsonb,3),
    ('3','3.5','Linear motion under a variable force','["solve problems which can be modelled as the linear motion of a particle under the action of a variable force, by setting up and solving an appropriate differential equation. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 3 Further Mechanics"]'::jsonb,4),
    ('3','3.6','Momentum','["recall Newton''s experimental law and the definition of the coefficient of restitution, the property e 0 1 G G , and the meaning of the terms ''perfectly elastic'' ( e = 1) and ''inelastic'' ( e = 0)", "use conservation of linear momentum and/or Newton''s experimental law to solve problems that may be modelled as the direct or oblique impact of two smooth spheres, or the direct or oblique impact of a smooth sphere with a fixed surface. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 4"]'::jsonb,5),
    ('4','4.1','Continuous random variables','["use a probability density function which may be defined piecewise", "use the general result X x x x E g f g d = _ ^ ^ ^ h i h h y where f( x ) is the probability density function of the continuous random variable X and g( X ) is a function of X", "understand and use the relationship between the probability density function (PDF) and the cumulative distribution function (CDF), and use either to evaluate probabilities or percentiles", "use cumulative distribution functions (CDFs) of related variables in simple cases."]'::jsonb,0),
    ('4','4.2','Inference using normal and t -distributions','["formulate hypotheses and apply a hypothesis test concerning the population mean using a small sample drawn from a normal population of unknown variance, using a t -test", "calculate a pooled estimate of a population variance from two samples", "formulate hypotheses concerning the difference of population means, and apply, as appropriate - a 2-sample t -test - a paired sample t -test - a test using a normal distribution", "determine a confidence interval for a population mean, based on a small sample from a normal population with unknown variance, using a t -distribution", "determine a confidence interval for a difference of population means, using a t -distribution or a normal distribution, as appropriate. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 4 Further Probability & Statistics"]'::jsonb,1),
    ('4','4.3','','["fit a theoretical distribution, as prescribed by a given hypothesis, to given data", "use a χ 2 -test, with the appropriate number of degrees of freedom, to carry out the corresponding goodness of fit analysis", "use a χ 2 -test, with the appropriate number of degrees of freedom, for independence in a contingency table."]'::jsonb,2),
    ('4','4.4','Non-parametric tests','["understand the idea of a non-parametric test and appreciate situations in which such a test might be useful", "understand the basis of the sign test, the Wilcoxon signed-rank test and the Wilcoxon rank-sum test", "use a single-sample sign test and a single- sample Wilcoxon signed-rank test to test a hypothesis concerning a population median", "use a paired-sample sign test, a Wilcoxon matched-pairs signed-rank test and a Wilcoxon rank-sum test, as appropriate, to test for identity of populations."]'::jsonb,3),
    ('4','4.5','Probability generating functions','["understand the concept of a probability generating function (PGF) and construct and use the PGF for given distributions", "use formulae for the mean and variance of a discrete random variable in terms of its PGF, and use these formulae to calculate the mean and variance of a given probability distribution", "use the result that the PGF of the sum of independent random variables is the product of the PGFs of those random variables. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page"]'::jsonb,4)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Further Mathematics AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Further Mathematics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Further Mathematics A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2027','9231','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2027', cambridge_code='9231', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'2','Further Pure Mathematics 2',0);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('2','2.1','Hyperbolic functions','["understand the definitions of the hyperbolic functions sinh x , cosh x , tanh x , sech x , cosech x , coth x in terms of the exponential function", "sketch the graphs of hyperbolic functions", "prove and use identities involving hyperbolic functions", "understand and use the definitions of the inverse hyperbolic functions and derive and use the logarithmic forms"]'::jsonb,0),
    ('2','2.2','Matrices','["formulate a problem involving the solution of 3 linear simultaneous equations in 3 unknowns as a problem involving the solution of a matrix equation, or vice versa", "understand the cases that may arise concerning the consistency or inconsistency of 3 linear simultaneous equations, relate them to the singularity or otherwise of the corresponding matrix, solve consistent systems, and interpret geometrically in terms of lines and planes", "understand the terms ''characteristic equation'', ''eigenvalue'' and ''eigenvector'', as applied to square matrices", "find eigenvalues and eigenvectors of 2 × 2 and 3 × 3 matrices", "express a square matrix in the form QDQ -1 , where D is a diagonal matrix of eigenvalues and Q is a matrix whose columns are eigenvectors, and use this expression", "use the fact that a square matrix satisfies its own characteristic equation. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 2 Further Pure Mathematics 2"]'::jsonb,1),
    ('2','2.3','Differentiation','["differentiate hyperbolic functions and differentiate sin -1 x , cos -1 x , sinh -1 x , cosh -1 x and tanh -1 x", "obtain an expression for x y d d 2 2 in cases where the relation between x and y is defined implicitly or parametrically", "derive and use the first few terms of a Maclaurin''s series for a function."]'::jsonb,2),
    ('2','2.4','Integration','["integrate hyperbolic functions and recognise integrals of functions of the form a x 1 2 2 − , x a 1 2 2 + and x a 1 2 2 − , and integrate associated functions using trigonometric or hyperbolic substitutions as appropriate", "derive and use reduction formulae for the evaluation of definite integrals", "understand how the area under a curve may be approximated by areas of rectangles, and use rectangles to estimate or set bounds for the area under a curve or to derive inequalities or limits concerning sums Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 2 Further Pure Mathematics 2"]'::jsonb,3),
    ('2','2.4','Integration continued','["use integration to find - arc lengths for curves with equations in Cartesian coordinates, including the use of a parameter, or in polar coordinates - surface areas of revolution about one of the axes for curves with equations in Cartesian coordinates, including the use of a parameter."]'::jsonb,4),
    ('2','2.5','Complex numbers','["understand de Moivre''s theorem, for a positive or negative integer exponent, in terms of the geometrical effect of multiplication and division of complex numbers", "prove de Moivre''s theorem for a positive integer exponent", "use de Moivre''s theorem for a positive or negative rational exponent - to express trigonometrical ratios of multiple angles in terms of powers of trigonometrical ratios of the fundamental angle - to express powers of sin i and cos i in terms of multiple angles - in the summation of series - in finding and using the n th roots of unity."]'::jsonb,5),
    ('2','2.6','Differential equations','["find an integrating factor for a first order linear differential equation, and use an integrating factor to find the general solution", "recall the meaning of the terms ''complementary function'' and ''particular integral'' in the context of linear differential equations, and recall that the general solution is the sum of the complementary function and a particular integral Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 2 Further Pure Mathematics 2"]'::jsonb,6),
    ('2','2.6','Differential equations continued','["find the complementary function for a first or second order linear differential equation with constant coefficients", "recall the form of, and find, a particular integral for a first or second order linear differential equation in the cases where a polynomial or a e bx or a cos px + b sin px is a suitable form, and in other simple cases find the appropriate coefficient(s) given a suitable form of particular integral", "use a given substitution to reduce a differential equation to a first or second order linear equation with constant coefficients or to a first order equation with separable variables", "use initial conditions to find a particular solution to a differential equation, and interpret a solution in terms of a problem modelled by a differential equation. Cambridge International AS & A Level Further Mathematics 9231 syllabus for 2026 and 2027. Back to contents page 3"]'::jsonb,7)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Further Mathematics A2';
END $$;
