-- Mathematics (9709) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Mathematics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Mathematics AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2027','9709','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2027', cambridge_code='9709', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Pure Mathematics 1',0),
    (v_org,v_tpl,'2','Pure Mathematics 2',1),
    (v_org,v_tpl,'4','Mechanics',2),
    (v_org,v_tpl,'5','Probability & Statistics 1',3);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Quadratics','["carry out the process of completing the square for a quadratic polynomial ax 2 + bx + c and use a completed square form", "find the discriminant of a quadratic polynomial ax 2 + bx + c and use the discriminant", "solve quadratic equations, and quadratic inequalities, in one unknown", "solve by substitution a pair of simultaneous equations of which one is linear and one is quadratic", "recognise and solve equations in x which are quadratic in some function of x ."]'::jsonb,0),
    ('1','1.2','Functions','["understand the terms function, domain, range, one-one function, inverse function and composition of functions", "identify the range of a given function in simple cases, and find the composition of two given functions", "determine whether or not a given function is one-one, and find the inverse of a one-one function in simple cases", "illustrate in graphical terms the relation between a one-one function and its inverse", "understand and use the transformations of the graph of y = f( x ) given by y = f( x ) + a , y = f( x + a ) , y = a f( x ) , y = f( ax ) and simple combinations of these. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 1 Pure Mathematics 1"]'::jsonb,1),
    ('1','1.3','Coordinate geometry','["find the equation of a straight line given sufficient information", "interpret and use any of the forms y = mx + c , y - y 1 = m ( x - x 1 ) , ax + by + c = 0 in solving problems", "understand that the equation ( x - a ) 2 + ( y - b ) 2 = r 2 represents the circle with centre ( a , b ) and radius r", "use algebraic methods to solve problems involving lines and circles", "understand the relationship between a graph and its associated algebraic equation, and use the relationship between points of intersection of graphs and solutions of equations."]'::jsonb,2),
    ('1','1.4','Circular measure','["understand the definition of a radian, and use the relationship between radians and degrees", "use the formulae s r A r 2 1 and 2 i i = = in solving problems concerning the arc length and sector area of a circle. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 1 Pure Mathematics 1"]'::jsonb,3),
    ('1','1.5','Trigonometry','["sketch and use graphs of the sine, cosine and tangent functions (for angles of any size, and using either degrees or radians)", "use the exact values of the sine, cosine and tangent of 30 °, 45 °, 60 °, and related angles", "use the notations sin -1 x , cos­ -1 x , tan -1 x to denote the principal values of the inverse trigonometric relations", "use the identities cos sin tan / i i i and sin cos 1 2 2 / i i +", "find all the solutions of simple trigonometrical equations lying in a specified interval (general forms of solution are not included)."]'::jsonb,4),
    ('1','1.6','Series','["use the expansion of ( a + b ) n , where n is a positive integer", "recognise arithmetic and geometric progressions", "use the formulae for the n th term and for the sum of the first n terms to solve problems involving arithmetic or geometric progressions", "use the condition for the convergence of a geometric progression, and the formula for the sum to infinity of a convergent geometric progression. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 1 Pure Mathematics 1"]'::jsonb,5),
    ('1','1.7','Differentiation','["understand the gradient of a curve at a point as the limit of the gradients of a suitable sequence of chords, and use the notations f ′( x ) , f ″( x ) , x y d d , and x y d d 2 2 for first and second derivatives", "use the derivative of xn (for any rational n ), together with constant multiples, sums and differences of functions, and of composite functions using the chain rule", "apply differentiation to gradients, tangents and normals, increasing and decreasing functions and rates of change", "locate stationary points and determine their nature, and use information about stationary points in sketching graphs."]'::jsonb,6),
    ('1','1.8','Integration','["understand integration as the reverse process of differentiation, and integrate ( ax + b ) n (for any rational n except -1), together with constant multiples, sums and differences", "solve problems involving the evaluation of a constant of integration", "evaluate definite integrals", "use definite integration to find - the area of a region bounded by a curve and lines parallel to the axes, or between a curve and a line or between two curves - a volume of revolution about one of the axes. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 2"]'::jsonb,7),
    ('2','2.1','Algebra','["understand the meaning of | x |, sketch the graph of y = | ax + b | and use relations such as | a | = | b | ⇔ a 2 = b 2 and | x - a | < b ⇔ a - b < x < a + b when solving equations and inequalities", "divide a polynomial, of degree not exceeding 4, by a linear or quadratic polynomial, and identify the quotient and remainder (which may be zero)", "use the factor theorem and the remainder theorem."]'::jsonb,0),
    ('2','2.2','Logarithmic and exponential functions','["understand the relationship between logarithms and indices, and use the laws of logarithms (excluding change of base)", "understand the definition and properties of e x and ln x , including their relationship as inverse functions and their graphs", "use logarithms to solve equations and inequalities in which the unknown appears in indices", "use logarithms to transform a given relationship to linear form, and hence determine unknown constants by considering the gradient and/or intercept. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 2 Pure Mathematics 2"]'::jsonb,1),
    ('2','2.3','Trigonometry','["understand the relationship of the secant, cosecant and cotangent functions to cosine, sine and tangent, and use properties and graphs of all six trigonometric functions for angles of any magnitude", "use trigonometrical identities for the simplification and exact evaluation of expressions, and in the course of solving equations, and select an identity or identities appropriate to the context, showing familiarity in particular with the use of - sec tan 1 2 2 / i i + and cosec cot 1 2 2 / i i + - the expansions of sin( A ± B ) , cos( A ± B ) and tan( A ± B ) - the formulae for sin 2 A , cos 2 A and tan 2 A - the expression of sin cos a b i i + in the forms sin R ! i a ^ h and cos R ! i a ^ h ."]'::jsonb,2),
    ('2','2.4','Differentiation','["use the derivatives of e x , ln x , sin x , cos x , tan x , together with constant multiples, sums, differences and composites", "differentiate products and quotients", "find and use the first derivative of a function which is defined parametrically or implicitly. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page"]'::jsonb,3),
    ('2','2.5','Integration','["extend the idea of ''reverse differentiation'' to include the integration of e ax + b , ax b 1 + , sin( ax + b ) , cos( ax + b ) and sec 2 ( ax + b )", "use trigonometrical relationships in carrying out integration", "understand and use the trapezium rule to estimate the value of a definite integral. 2 Pure Mathematics 2"]'::jsonb,4),
    ('2','2.6','Numerical solution of equations','["locate approximately a root of an equation, by means of graphical considerations and/or searching for a sign change", "understand the idea of, and use the notation for, a sequence of approximations which converges to a root of an equation", "understand how a given simple iterative formula of the form x n + 1 = F( x n ) relates to the equation being solved, and use a given iteration, or an iteration based on a given rearrangement of an equation, to determine a root to a prescribed degree of accuracy. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 3"]'::jsonb,5),
    ('4','4.1','Forces and equilibrium','["identify the forces acting in a given situation", "understand the vector nature of force, and find and use components and resultants", "use the principle that, when a particle is in equilibrium, the vector sum of the forces acting is zero, or equivalently, that the sum of the components in any direction is zero", "understand that a contact force between two surfaces can be represented by two components, the normal component and the frictional component", "use the model of a ''smooth'' contact, and understand the limitations of this model", "understand the concepts of limiting friction and limiting equilibrium, recall the definition of coefficient of friction, and use the relationship F R n = or F R G n , as appropriate", "use Newton''s third law. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 4 Mechanics"]'::jsonb,0),
    ('4','4.2','Kinematics of motion in a straight line','["understand the concepts of distance and speed as scalar quantities, and of displacement, velocity and acceleration as vector quantities", "sketch and interpret displacement-time graphs and velocity-time graphs, and in particular appreciate that - the area under a velocity-time graph represents displacement, - the gradient of a displacement-time graph represents velocity, - the gradient of a velocity-time graph represents acceleration", "use differentiation and integration with respect to time to solve simple problems concerning displacement, velocity and acceleration", "use appropriate formulae for motion with constant acceleration in a straight line."]'::jsonb,1),
    ('4','4.3','Momentum','["use the definition of linear momentum and show understanding of its vector nature", "use conservation of linear momentum to solve problems that may be modelled as the direct impact of two bodies. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 4 Mechanics"]'::jsonb,2),
    ('4','4.4','Newton''s laws of motion','["apply Newton''s laws of motion to the linear motion of a particle of constant mass moving under the action of constant forces, which may include friction, tension in an inextensible string and thrust in a connecting rod", "use the relationship between mass and weight", "solve simple problems which may be modelled as the motion of a particle moving vertically or on an inclined plane with constant acceleration", "solve simple problems which may be modelled as the motion of connected particles."]'::jsonb,3),
    ('4','4.5','Energy, work and power','["understand the concept of the work done by a force, and calculate the work done by a constant force when its point of application undergoes a displacement not necessarily parallel to the force", "understand the concepts of gravitational potential energy and kinetic energy, and use appropriate formulae", "understand and use the relationship between the change in energy of a system and the work done by the external forces, and use in appropriate cases the principle of conservation of energy", "use the definition of power as the rate at which a force does work, and use the relationship between power, force and velocity for a force acting in the direction of motion", "solve problems involving, for example, the instantaneous acceleration of a car moving on a hill against a resistance. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 5"]'::jsonb,4),
    ('5','5.1','Representation of data','["select a suitable way of presenting raw statistical data, and discuss advantages and/ or disadvantages that particular representations may have", "draw and interpret stem-and-leaf diagrams, box-and-whisker plots, histograms and cumulative frequency graphs", "understand and use different measures of central tendency (mean, median, mode) and variation (range, interquartile range, standard deviation)", "use a cumulative frequency graph", "calculate and use the mean and standard deviation of a set of data (including grouped data) either from the data itself or from given totals x / and x 2 / , or coded totals x a − ^ h / and x a 2 − ^ h / , and use such totals in solving problems which may involve up to two data sets."]'::jsonb,0),
    ('5','5.2','Permutations and combinations','["understand the terms permutation and combination, and solve simple problems involving selections", "solve problems about arrangements of objects in a line, including those involving - repetition (e.g. the number of ways of arranging the letters of the word ''NEEDLESS'') - restriction (e.g. the number of ways several people can stand in a line if two particular people must, or must not, stand next to each other). Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 5 Probability & Statistics 1"]'::jsonb,1),
    ('5','5.3','Probability','["evaluate probabilities in simple cases by means of enumeration of equiprobable elementary events, or by calculation using permutations or combinations", "use addition and multiplication of probabilities, as appropriate, in simple cases", "understand the meaning of exclusive and independent events, including determination of whether events A and B are independent by comparing the values of A B P + ^ h and A B P P # ^ ^ h h", "calculate and use conditional probabilities in simple cases."]'::jsonb,2),
    ('5','5.4','Discrete random variables','["draw up a probability distribution table relating to a given situation involving a discrete random variable X , and calculate E( X ) and Var( X )", "use formulae for probabilities for the binomial and geometric distributions, and recognise practical situations where these distributions are suitable models", "use formulae for the expectation and variance of the binomial distribution and for the expectation of the geometric distribution. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 5 Probability & Statistics 1"]'::jsonb,3),
    ('5','5.5','The normal distribution','["understand the use of a normal distribution to model a continuous random variable, and use normal distribution tables", "solve problems concerning a variable X , where , X N 2 + n v _ i , including - finding the value of P 1 X x > _ i , or a related probability, given the values of x 1 , n , v . - finding a relationship between x 1 , n and v given the value of P 1 X x > _ i or a related probability", "recall conditions under which the normal distribution can be used as an approximation to the binomial distribution, and use this approximation, with a continuity correction, in solving problems. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 6"]'::jsonb,4)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Mathematics AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Mathematics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Mathematics A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2026-2027','9709','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2026-2027', cambridge_code='9709', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'3','Pure Mathematics 3',0),
    (v_org,v_tpl,'6','Probability & Statistics 2',1);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('3','3.1','Algebra','["understand the meaning of | x |, sketch the graph of y = | ax + b | and use relations such as | a | = | b | ⇔ a 2 = b 2 and | x - a | < b ⇔ a - b < x < a + b when solving equations and inequalities", "divide a polynomial, of degree not exceeding 4, by a linear or quadratic polynomial, and identify the quotient and remainder (which may be zero)", "use the factor theorem and the remainder theorem", "recall an appropriate form for expressing rational functions in partial fractions, and carry out the decomposition, in cases where the denominator is no more complicated than - ( ax + b )( cx + d )( ex + f ) - ( ax + b )( cx + d ) 2 - ( ax + b )( cx 2 + d )", "use the expansion of (1 + x ) n , where n is a rational number and x 1 1 . Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 3 Pure Mathematics 3"]'::jsonb,0),
    ('3','3.2','Logarithmic and exponential functions','["understand the relationship between logarithms and indices, and use the laws of logarithms (excluding change of base)", "understand the definition and properties of e x and ln x , including their relationship as inverse functions and their graphs", "use logarithms to solve equations and inequalities in which the unknown appears in indices", "use logarithms to transform a given relationship to linear form, and hence determine unknown constants by considering the gradient and/or intercept."]'::jsonb,1),
    ('3','3.3','Trigonometry','["understand the relationship of the secant, cosecant and cotangent functions to cosine, sine and tangent, and use properties and graphs of all six trigonometric functions for angles of any magnitude", "use trigonometrical identities for the simplification and exact evaluation of expressions, and in the course of solving equations, and select an identity or identities appropriate to the context, showing familiarity in particular with the use of - sec tan 1 2 2 / i i + and cosec cot 1 2 2 / i i + - the expansions of sin( A ± B ) , cos( A ± B ) and tan( A ± B ) - the formulae for sin 2 A , cos 2 A and tan 2 A - the expression of sin cos a b i i + in the forms sin R ! a i ^ h and cos R ! a i ^ h . Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 3 Pure Mathematics 3"]'::jsonb,2),
    ('3','3.4','Differentiation','["use the derivatives of e x , ln x , sin x , cos x , tan x , tan -1 x , together with constant multiples, sums, differences and composites", "differentiate products and quotients", "find and use the first derivative of a function which is defined parametrically or implicitly."]'::jsonb,3),
    ('3','3.5','Integration','["extend the idea of ''reverse differentiation'' to include the integration of e ax + b , ax b 1 + , sin( ax + b ) , cos( ax + b ) , sec 2 ( ax + b ) and x a 1 2 2 +", "use trigonometrical relationships in carrying out integration", "integrate rational functions by means of decomposition into partial fractions", "recognise an integrand of the form x k x f f l ^ ^ h h , and integrate such functions", "recognise when an integrand can usefully be regarded as a product, and use integration by parts", "use a given substitution to simplify and evaluate either a definite or an indefinite integral. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 3 Pure Mathematics 3"]'::jsonb,4),
    ('3','3.6','Numerical solution of equations','["locate approximately a root of an equation, by means of graphical considerations and/or searching for a sign change", "understand the idea of, and use the notation for, a sequence of approximations which converges to a root of an equation", "understand how a given simple iterative formula of the form x n + 1 = F( x n ) relates to the equation being solved, and use a given iteration, or an iteration based on a given rearrangement of an equation, to determine a root to a prescribed degree of accuracy."]'::jsonb,5),
    ('3','3.7','Vectors','["use standard notations for vectors, i.e. x y f p , x i + y j , x y z f p , x i + y j + z k , AB , a", "carry out addition and subtraction of vectors and multiplication of a vector by a scalar, and interpret these operations in geometrical terms", "calculate the magnitude of a vector, and use unit vectors, displacement vectors and position vectors", "understand the significance of all the symbols used when the equation of a straight line is expressed in the form r = a + t b , and find the equation of a line, given sufficient information", "determine whether two lines are parallel, intersect or are skew, and find the point of intersection of two lines when it exists", "use formulae to calculate the scalar product of two vectors, and use scalar products in problems involving lines and points. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 3 Pure Mathematics 3"]'::jsonb,6),
    ('3','3.8','Differential equations','["formulate a simple statement involving a rate of change as a differential equation", "find by integration a general form of solution for a first order differential equation in which the variables are separable", "use an initial condition to find a particular solution", "interpret the solution of a differential equation in the context of a problem being modelled by the equation."]'::jsonb,7),
    ('3','3.9','Complex numbers','["understand the idea of a complex number, recall the meaning of the terms real part, imaginary part, modulus, argument, conjugate, and use the fact that two complex numbers are equal if and only if both real and imaginary parts are equal", "carry out operations of addition, subtraction, multiplication and division of two complex numbers expressed in Cartesian form x + i y", "use the result that, for a polynomial equation with real coefficients, any non-real roots occur in conjugate pairs", "represent complex numbers geometrically by means of an Argand diagram", "carry out operations of multiplication and division of two complex numbers expressed in polar form cos sin r r i e i / i i + i ^ h", "find the two square roots of a complex number", "understand in simple terms the geometrical effects of conjugating a complex number and of adding, subtracting, multiplying and dividing two complex numbers", "illustrate simple equations and inequalities involving complex numbers by means of loci in an Argand diagram Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 4"]'::jsonb,8),
    ('6','6.1','The Poisson distribution','["use formulae to calculate probabilities for the distribution Po m ^ h", "use the fact that if X Po + m ^ h then the mean and variance of X are each equal to m", "understand the relevance of the Poisson distribution to the distribution of random events, and use the Poisson distribution as a model", "use the Poisson distribution as an approximation to the binomial distribution where appropriate", "use the normal distribution, with continuity correction, as an approximation to the Poisson distribution where appropriate."]'::jsonb,0),
    ('6','6.2','Linear combinations of random variables','["use, when solving problems, the results that - E( aX + b ) = aE ( X ) + b and Var( aX + b ) = a 2 Var( X ) - E( aX + bY ) = a E( X ) + b E( Y ) - Var(a X + b Y ) = a 2 Var( X ) + b 2 Var( Y ) for independent X and Y - if X has a normal distribution then so does aX + b - if X and Y have independent normal distributions then aX + bY has a normal distribution - if X and Y have independent Poisson distributions then X + Y has a Poisson distribution. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 6 Probability & Statistics 2"]'::jsonb,1),
    ('6','6.3','Continuous random variables','["understand the concept of a continuous random variable, and recall and use properties of a probability density function", "use a probability density function to solve problems involving probabilities, and to calculate the mean and variance of a distribution."]'::jsonb,2),
    ('6','6.4','Sampling and estimation','["understand the distinction between a sample and a population, and appreciate the necessity for randomness in choosing samples", "explain in simple terms why a given sampling method may be unsatisfactory", "recognise that a sample mean can be regarded as a random variable, and use the facts that E X = n _ i and that Var X n 2 = v _ i", "use the fact that X _ i has a normal distribution if X has a normal distribution", "use the Central Limit Theorem where appropriate", "calculate unbiased estimates of the population mean and variance from a sample, using either raw or summarised data", "determine and interpret a confidence interval for a population mean in cases where the population is normally distributed with known variance or where a large sample is used", "determine, from a large sample, an approximate confidence interval for a population proportion. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page 6 Probability & Statistics 2"]'::jsonb,3),
    ('6','6.5','Hypothesis tests','["understand the nature of a hypothesis test, the difference between one-tailed and two-tailed tests, and the terms null hypothesis, alternative hypothesis, significance level, rejection region (or critical region), acceptance region and test statistic", "formulate hypotheses and carry out a hypothesis test in the context of a single observation from a population which has a binomial or Poisson distribution, using - direct evaluation of probabilities - a normal approximation to the binomial or the Poisson distribution, where appropriate", "formulate hypotheses and carry out a hypothesis test concerning the population mean in cases where the population is normally distributed with known variance or where a large sample is used", "understand the terms Type I error and Type II error in relation to hypothesis tests", "calculate the probabilities of making Type I and Type II errors in specific situations involving tests based on a normal distribution or direct evaluation of binomial or Poisson probabilities. Cambridge International AS & A Level Mathematics 9709 syllabus for 2026 and 2027. Back to contents page"]'::jsonb,4)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Mathematics A2';
END $$;
