-- Physics (9702) - Cambridge AS & A Level outline with objectives.
-- Generated from the official syllabus PDF. Safe to re-run (replaces).

DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='AS' AND name='Physics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Physics AS not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2025-2027','9702','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2025-2027', cambridge_code='9702', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'1','Physical quantities and units',0),
    (v_org,v_tpl,'2','Kinematics',1),
    (v_org,v_tpl,'3','Dynamics',2),
    (v_org,v_tpl,'4','Forces, density and pressure',3),
    (v_org,v_tpl,'5','Work, energy and power',4),
    (v_org,v_tpl,'6','Deformation of solids',5),
    (v_org,v_tpl,'7','Waves',6),
    (v_org,v_tpl,'8','Superposition',7),
    (v_org,v_tpl,'9','Electricity',8),
    (v_org,v_tpl,'10','D.C. circuits',9),
    (v_org,v_tpl,'11','Particle physics',10);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('1','1.1','Physical quantities','["understand that all physical quantities consist of a numerical magnitude and a unit", "make reasonable estimates of physical quantities included within the syllabus"]'::jsonb,0),
    ('1','1.2','SI units','["recall the following SI base quantities and their units: mass (kg), length (m), time (s), current (A), temperature (K)", "express derived units as products or quotients of the SI base units and use the derived units for quantities listed in this syllabus as appropriate", "use SI base units to check the homogeneity of physical equations", "recall and use the following prefixes and their symbols to indicate decimal submultiples or multiples of both base and derived units: pico (p), nano (n), micro ( μ ), milli (m), centi (c), deci (d), kilo (k), mega (M), giga (G), tera (T)"]'::jsonb,1),
    ('1','1.3','Errors and uncertainties','["understand and explain the effects of systematic errors (including zero errors) and random errors in measurements", "understand the distinction between precision and accuracy", "assess the uncertainty in a derived quantity by simple addition of absolute or percentage uncertainties"]'::jsonb,2),
    ('1','1.4','Scalars and vectors','["understand the difference between scalar and vector quantities and give examples of scalar and vector quantities included in the syllabus", "add and subtract coplanar vectors", "represent a vector as two perpendicular components Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('2','2.1','Equations of motion','["define and use distance, displacement, speed, velocity and acceleration", "use graphical methods to represent distance, displacement, speed, velocity and acceleration", "determine displacement from the area under a velocity-time graph", "determine velocity using the gradient of a displacement-time graph", "determine acceleration using the gradient of a velocity-time graph", "derive, from the definitions of velocity and acceleration, equations that represent uniformly accelerated motion in a straight line", "solve problems using equations that represent uniformly accelerated motion in a straight line, including the motion of bodies falling in a uniform gravitational field without air resistance", "describe an experiment to determine the acceleration of free fall using a falling object", "describe and explain motion due to a uniform velocity in one direction and a uniform acceleration in a perpendicular direction"]'::jsonb,0),
    ('3','3.1','Momentum and Newton''s laws of motion','["understand that mass is the property of an object that resists change in motion", "recall F = ma and solve problems using it, understanding that acceleration and resultant force are always in the same direction", "define and use linear momentum as the product of mass and velocity", "define and use force as rate of change of momentum", "state and apply each of Newton''s laws of motion", "describe and use the concept of weight as the effect of a gravitational field on a mass and recall that the weight of an object is equal to the product of its mass and the acceleration of free fall Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('3','3.2','Non-uniform motion','["show a qualitative understanding of frictional forces and viscous/drag forces including air resistance (no treatment of the coefficients of friction and viscosity is required, and a simple model of drag force increasing as speed increases is sufficient)", "describe and explain qualitatively the motion of objects in a uniform gravitational field with air resistance", "understand that objects moving against a resistive force may reach a terminal (constant) velocity"]'::jsonb,1),
    ('3','3.3','Linear momentum and its conservation','["state the principle of conservation of momentum", "apply the principle of conservation of momentum to solve simple problems, including elastic and inelastic interactions between objects in both one and two dimensions (knowledge of the concept of coefficient of restitution is not required)", "recall that, for an elastic collision, total kinetic energy is conserved and the relative speed of approach is equal to the relative speed of separation", "understand that, while momentum of a system is always conserved in interactions between objects, some change in kinetic energy may take place"]'::jsonb,2),
    ('4','4.1','Turning effects of forces','["understand that the weight of an object may be taken as acting at a single point known as its centre of gravity", "define and apply the moment of a force", "understand that a couple is a pair of forces that acts to produce rotation only", "define and apply the torque of a couple"]'::jsonb,0),
    ('4','4.2','Equilibrium of forces','["state and apply the principle of moments", "understand that, when there is no resultant force and no resultant torque, a system is in equilibrium", "use a vector triangle to represent coplanar forces in equilibrium Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('4','4.3','Density and pressure','["define and use density", "define and use pressure", "derive, from the definitions of pressure and density, the equation for hydrostatic pressure ∆ p = ρ g ∆ h", "use the equation ∆ p = ρ g ∆ h", "understand that the upthrust acting on an object in a fluid is due to a difference in hydrostatic pressure", "calculate the upthrust acting on an object in a fluid using the equation F = ρ gV (Archimedes'' principle)"]'::jsonb,2),
    ('5','5.1','Energy conservation','["understand the concept of work, and recall and use work done = force × displacement in the direction of the force", "recall and apply the principle of conservation of energy", "recall and understand that the efficiency of a system is the ratio of useful energy output from the system to the total energy input", "use the concept of efficiency to solve problems", "define power as work done per unit time", "solve problems using P = W / t", "derive P = Fv and use it to solve problems"]'::jsonb,0),
    ('5','5.2','Gravitational potential energy and kinetic energy','["derive, using W = Fs , the formula ∆ E P = mg ∆ h for gravitational potential energy changes in a uniform gravitational field", "recall and use the formula ∆ E P = mg ∆ h for gravitational potential energy changes in a uniform gravitational field", "derive, using the equations of motion, the formula for kinetic energy E K = 2 1 mv 2", "recall and use E K = 2 1 mv 2 Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('6','6.1','Stress and strain','["understand that deformation is caused by tensile or compressive forces (forces and deformations will be assumed to be in one dimension only)", "understand and use the terms load, extension, compression and limit of proportionality", "recall and use Hooke''s law", "recall and use the formula for the spring constant k = F / x", "define and use the terms stress, strain and the Young modulus", "describe an experiment to determine the Young modulus of a metal in the form of a wire"]'::jsonb,0),
    ('6','6.2','Elastic and plastic behaviour','["understand and use the terms elastic deformation, plastic deformation and elastic limit", "understand that the area under the force-extension graph represents the work done", "determine the elastic potential energy of a material deformed within its limit of proportionality from the area under the force-extension graph", "recall and use E P = 2 1 Fx = 2 1 kx 2 for a material deformed within its limit of proportionality"]'::jsonb,1),
    ('7','7.1','Progressive waves','["describe what is meant by wave motion as illustrated by vibration in ropes, springs and ripple tanks", "understand and use the terms displacement, amplitude, phase difference, period, frequency, wavelength and speed", "understand the use of the time-base and y -gain of a cathode-ray oscilloscope (CRO) to determine frequency and amplitude", "derive, using the definitions of speed, frequency and wavelength, the wave equation v = f λ", "recall and use v = f λ", "understand that energy is transferred by a progressive wave", "recall and use intensity = power/area and intensity ∝ ( amplitude ) 2 for a progressive wave Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('7','7.2','Transverse and longitudinal waves','["compare transverse and longitudinal waves", "analyse and interpret graphical representations of transverse and longitudinal waves"]'::jsonb,1),
    ('7','7.3','Doppler effect for sound waves','["understand that when a source of sound waves moves relative to a stationary observer, the observed frequency is different from the source frequency (understanding of the Doppler effect for a stationary source and a moving observer is not required)", "use the expression f ο = f s v / ( v ± v s ) for the observed frequency when a source of sound waves moves relative to a stationary observer"]'::jsonb,2),
    ('7','7.4','Electromagnetic spectrum','["state that all electromagnetic waves are transverse waves that travel with the same speed c in free space", "recall the approximate range of wavelengths in free space of the principal regions of the electromagnetic spectrum from radio waves to γ -rays", "recall that wavelengths in the range 400-700 nm in free space are visible to the human eye"]'::jsonb,3),
    ('7','7.5','Polarisation','["understand that polarisation is a phenomenon associated with transverse waves", "recall and use Malus''s law ( I = I 0 cos 2 θ ) to calculate the intensity of a plane-polarised electromagnetic wave after transmission through a polarising filter or a series of polarising filters (calculation of the effect of a polarising filter on the intensity of an unpolarised wave is not required) Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,4),
    ('8','8.1','Stationary waves','["explain and use the principle of superposition", "show an understanding of experiments that demonstrate stationary waves using microwaves, stretched strings and air columns (it will be assumed that end corrections are negligible; knowledge of the concept of end corrections is not required)", "explain the formation of a stationary wave using a graphical method, and identify nodes and antinodes", "understand how wavelength may be determined from the positions of nodes or antinodes of a stationary wave"]'::jsonb,0),
    ('8','8.2','Diffraction','["explain the meaning of the term diffraction", "show an understanding of experiments that demonstrate diffraction including the qualitative effect of the gap width relative to the wavelength of the wave; for example diffraction of water waves in a ripple tank"]'::jsonb,1),
    ('8','8.3','Interference','["understand the terms interference and coherence", "show an understanding of experiments that demonstrate two-source interference using water waves in a ripple tank, sound, light and microwaves", "understand the conditions required if two-source interference fringes are to be observed", "recall and use λ = ax / D for double-slit interference using light"]'::jsonb,2),
    ('8','8.4','The diffraction grating','["recall and use d sin θ = n λ", "describe the use of a diffraction grating to determine the wavelength of light (the structure and use of the spectrometer are not included) Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('9','9.1','Electric current','["understand that an electric current is a flow of charge carriers", "understand that the charge on charge carriers is quantised", "recall and use Q = I t", "use, for a current-carrying conductor, the expression I = Anvq , where n is the number density of charge carriers"]'::jsonb,0),
    ('9','9.2','Potential difference and power','["define the potential difference across a component as the energy transferred per unit charge", "recall and use V = W / Q", "recall and use P = V I , P = I 2 R and P = V 2 / R"]'::jsonb,1),
    ('9','9.3','Resistance and resistivity','["define resistance", "recall and use V = I R", "sketch the I - V characteristics of a metallic conductor at constant temperature, a semiconductor diode and a filament lamp", "explain that the resistance of a filament lamp increases as current increases because its temperature increases", "state Ohm''s law", "recall and use R = ρ L / A", "understand that the resistance of a light-dependent resistor (LDR) decreases as the light intensity increases", "understand that the resistance of a thermistor decreases as the temperature increases (it will be assumed that thermistors have a negative temperature coefficient) Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('10','10.1','Practical circuits','["recall and use the circuit symbols shown in section 6 of this syllabus", "draw and interpret circuit diagrams containing the circuit symbols shown in section 6 of this syllabus", "define and use the electromotive force (e.m.f.) of a source as energy transferred per unit charge in driving charge around a complete circuit", "distinguish between e.m.f. and potential difference (p.d.) in terms of energy considerations", "understand the effects of the internal resistance of a source of e.m.f. on the terminal potential difference"]'::jsonb,0),
    ('10','10.2','Kirchhoff''s laws','["recall Kirchhoff''s first law and understand that it is a consequence of conservation of charge", "recall Kirchhoff''s second law and understand that it is a consequence of conservation of energy", "derive, using Kirchhoff''s laws, a formula for the combined resistance of two or more resistors in series", "use the formula for the combined resistance of two or more resistors in series", "derive, using Kirchhoff''s laws, a formula for the combined resistance of two or more resistors in parallel", "use the formula for the combined resistance of two or more resistors in parallel", "use Kirchhoff''s laws to solve simple circuit problems"]'::jsonb,1),
    ('10','10.3','Potential dividers','["understand the principle of a potential divider circuit", "recall and use the principle of the potentiometer as a means of comparing potential differences", "understand the use of a galvanometer in null methods", "explain the use of thermistors and light-dependent resistors in potential dividers to provide a potential difference that is dependent on temperature and light intensity Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('11','11.1','Atoms, nuclei and radiation','["infer from the results of the α -particle scattering experiment the existence and small size of the nucleus", "describe a simple model for the nuclear atom to include protons, neutrons and orbital electrons", "distinguish between nucleon number and proton number", "understand that isotopes are forms of the same element with different numbers of neutrons in their nuclei", "understand and use the notation A Z X for the representation of nuclides", "understand that nucleon number and charge are conserved in nuclear processes", "describe the composition, mass and charge of α -, β - and γ -radiations (both β - (electrons) and β + (positrons) are included)", "understand that an antiparticle has the same mass but opposite charge to the corresponding particle, and that a positron is the antiparticle of an electron", "state that (electron) antineutrinos are produced during β - decay and (electron) neutrinos are produced during β + decay", "understand that α -particles have discrete energies but that β -particles have a continuous range of energies because (anti)neutrinos are emitted in β -decay", "represent α - and β -decay by a radioactive decay equation of the form U Th 92 238 90 234 2 4 \" + α", "use the unified atomic mass unit (u) as a unit of mass"]'::jsonb,0),
    ('11','11.2','Fundamental particles','["understand that a quark is a fundamental particle and that there are six flavours (types) of quark: up, down, strange, charm, top and bottom", "recall and use the charge of each flavour of quark and understand that its respective antiquark has the opposite charge (no knowledge of any other properties of quarks is required)", "recall that protons and neutrons are not fundamental particles and describe protons and neutrons in terms of their quark composition", "understand that a hadron may be either a baryon (consisting of three quarks) or a meson (consisting of one quark and one antiquark)", "describe the changes to quark composition that take place during β - and β + decay", "recall that electrons and neutrinos are fundamental particles called leptons Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Physics AS';
END $$;


DO $$
DECLARE v_org uuid; v_subject uuid; v_tpl uuid;
BEGIN
  SELECT id, org_id INTO v_subject, v_org FROM public.subjects
    WHERE program='A2' AND name='Physics' AND deleted_at IS NULL LIMIT 1;
  IF v_subject IS NULL THEN RAISE NOTICE 'Physics A2 not found - skipped'; RETURN; END IF;
  SELECT id INTO v_tpl FROM public.syllabus_templates
    WHERE org_id=v_org AND subject_id=v_subject AND status='active' AND deleted_at IS NULL
    ORDER BY created_at DESC LIMIT 1;
  IF v_tpl IS NULL THEN
    INSERT INTO public.syllabus_templates(org_id,subject_id,academic_year,cambridge_code,status)
      VALUES(v_org,v_subject,'2025-2027','9702','active') RETURNING id INTO v_tpl;
  ELSE
    UPDATE public.syllabus_templates SET academic_year='2025-2027', cambridge_code='9702', updated_at=now() WHERE id=v_tpl;
    UPDATE public.syllabus_subtopics SET deleted_at=now()
      WHERE topic_id IN (SELECT id FROM public.syllabus_topics WHERE template_id=v_tpl AND deleted_at IS NULL);
    UPDATE public.syllabus_topics SET deleted_at=now() WHERE template_id=v_tpl AND deleted_at IS NULL;
  END IF;
  INSERT INTO public.syllabus_topics(org_id,template_id,code,name,sort) VALUES
    (v_org,v_tpl,'12','Motion in a circle',0),
    (v_org,v_tpl,'13','Gravitational fields',1),
    (v_org,v_tpl,'14','Temperature',2),
    (v_org,v_tpl,'15','Ideal gases',3),
    (v_org,v_tpl,'16','Thermodynamics',4),
    (v_org,v_tpl,'17','Oscillations',5),
    (v_org,v_tpl,'18','Electric fields',6),
    (v_org,v_tpl,'19','Capacitance',7),
    (v_org,v_tpl,'20','Magnetic fields',8),
    (v_org,v_tpl,'21','Alternating currents',9),
    (v_org,v_tpl,'22','Quantum physics',10),
    (v_org,v_tpl,'23','Nuclear physics',11),
    (v_org,v_tpl,'24','Medical physics',12),
    (v_org,v_tpl,'25','Astronomy and cosmology',13);
  INSERT INTO public.syllabus_subtopics(org_id,topic_id,code,name,objectives,sort)
  SELECT v_org, t.id, x.scode, x.sname, x.objectives, x.sort FROM (VALUES
    ('12','12.1','Kinematics of uniform circular motion','["define the radian and express angular displacement in radians", "understand and use the concept of angular speed", "recall and use ω = 2 π / T and v = r ω"]'::jsonb,0),
    ('12','12.2','Centripetal acceleration','["understand that a force of constant magnitude that is always perpendicular to the direction of motion causes centripetal acceleration", "understand that centripetal acceleration causes circular motion with a constant angular speed", "recall and use a = r ω 2 and a = v 2 / r", "recall and use F = mr ω 2 and F = mv 2 / r"]'::jsonb,1),
    ('13','13.1','Gravitational field','["understand that a gravitational field is an example of a field of force and define gravitational field as force per unit mass", "represent a gravitational field by means of field lines"]'::jsonb,0),
    ('13','13.2','Gravitational force between point masses','["understand that, for a point outside a uniform sphere, the mass of the sphere may be considered to be a point mass at its centre", "recall and use Newton''s law of gravitation F = Gm 1 m 2 / r 2 for the force between two point masses", "analyse circular orbits in gravitational fields by relating the gravitational force to the centripetal acceleration it causes", "understand that a satellite in a geostationary orbit remains at the same point above the Earth''s surface, with an orbital period of 24 hours, orbiting from west to east, directly above the Equator Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('13','13.3','Gravitational field of a point mass','["derive, from Newton''s law of gravitation and the definition of gravitational field, the equation g = GM / r 2 for the gravitational field strength due to a point mass", "recall and use g = GM / r 2", "understand why g is approximately constant for small changes in height near the Earth''s surface"]'::jsonb,2),
    ('13','13.4','Gravitational potential','["define gravitational potential at a point as the work done per unit mass in bringing a small test mass from infinity to the point", "use ϕ = - GM / r for the gravitational potential in the field due to a point mass", "understand how the concept of gravitational potential leads to the gravitational potential energy of two point masses and use E P = - GMm / r"]'::jsonb,3),
    ('14','14.1','Thermal equilibrium','["understand that (thermal) energy is transferred from a region of higher temperature to a region of lower temperature", "understand that regions of equal temperature are in thermal equilibrium"]'::jsonb,0),
    ('14','14.2','Temperature scales','["understand that a physical property that varies with temperature may be used for the measurement of temperature and state examples of such properties, including the density of a liquid, volume of a gas at constant pressure, resistance of a metal, e.m.f. of a thermocouple", "understand that the scale of thermodynamic temperature does not depend on the property of any particular substance", "convert temperatures between kelvin and degrees Celsius and recall that T / K = θ / °C + 273.15", "understand that the lowest possible temperature is zero kelvin on the thermodynamic temperature scale and that this is known as absolute zero Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('14','14.3','Specific heat capacity and specific latent heat','["define and use specific heat capacity", "define and use specific latent heat and distinguish between specific latent heat of fusion and specific latent heat of vaporisation"]'::jsonb,2),
    ('15','15.1','The mole','["understand that amount of substance is an SI base quantity with the base unit mol", "use molar quantities where one mole of any substance is the amount containing a number of particles of that substance equal to the Avogadro constant N A"]'::jsonb,0),
    ('15','15.2','Equation of state','["understand that a gas obeying pV ∝ T , where T is the thermodynamic temperature, is known as an ideal gas", "recall and use the equation of state for an ideal gas expressed as pV = nRT , where n = amount of substance (number of moles) and as pV = NkT , where N = number of molecules", "recall that the Boltzmann constant k is given by k = R / N A"]'::jsonb,1),
    ('15','15.3','Kinetic theory of gases','["state the basic assumptions of the kinetic theory of gases", "explain how molecular movement causes the pressure exerted by a gas and derive and use the relationship pV = 3 1 Nm < c 2 >, where < c 2 > is the mean-square speed (a simple model considering one-dimensional collisions and then extending to three dimensions using 3 1 < c 2 > = < c x 2 > is sufficient)", "understand that the root-mean-square speed c r.m.s. is given by c < > 2", "compare pV = 3 1 Nm < c 2 > with pV = NkT to deduce that the average translational kinetic energy of a molecule is 2 3 kT , and recall and use this expression Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2),
    ('16','16.1','Internal energy','["understand that internal energy is determined by the state of the system and that it can be expressed as the sum of a random distribution of kinetic and potential energies associated with the molecules of a system", "relate a rise in temperature of an object to an increase in its internal energy"]'::jsonb,0),
    ('16','16.2','The first law of thermodynamics','["recall and use W = p ∆ V for the work done when the volume of a gas changes at constant pressure and understand the difference between the work done by the gas and the work done on the gas", "recall and use the first law of thermodynamics ∆ U = q + W expressed in terms of the increase in internal energy, the heating of the system (energy transferred to the system by heating) and the work done on the system"]'::jsonb,1),
    ('17','17.1','Simple harmonic oscillations','["understand and use the terms displacement, amplitude, period, frequency, angular frequency and phase difference in the context of oscillations, and express the period in terms of both frequency and angular frequency", "understand that simple harmonic motion occurs when acceleration is proportional to displacement from a fixed point and in the opposite direction", "use a = - ω 2 x and recall and use, as a solution to this equation, x = x 0 sin ω t", "use the equations v = v 0 cos ω t and v = ± ω ( ) x x 0 2 2 −", "analyse and interpret graphical representations of the variations of displacement, velocity and acceleration for simple harmonic motion Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('17','17.2','Energy in simple harmonic motion','["describe the interchange between kinetic and potential energy during simple harmonic motion", "recall and use E = 2 1 m ω 2 x 0 2 for the total energy of a system undergoing simple harmonic motion"]'::jsonb,1),
    ('17','17.3','Damped and forced oscillations, resonance','["understand that a resistive force acting on an oscillating system causes damping", "understand and use the terms light, critical and heavy damping and sketch displacement-time graphs illustrating these types of damping", "understand that resonance involves a maximum amplitude of oscillations and that this occurs when an oscillating system is forced to oscillate at its natural frequency"]'::jsonb,2),
    ('18','18.1','Electric fields and field lines','["understand that an electric field is an example of a field of force and define electric field as force per unit positive charge", "recall and use F = qE for the force on a charge in an electric field", "represent an electric field by means of field lines"]'::jsonb,0),
    ('18','18.2','Uniform electric fields','["recall and use E = ∆ V / ∆ d to calculate the field strength of the uniform field between charged parallel plates", "describe the effect of a uniform electric field on the motion of charged particles Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('18','18.3','Electric force between point charges','["understand that, for a point outside a spherical conductor, the charge on the sphere may be considered to be a point charge at its centre", "recall and use Coulomb''s law F = Q 1 Q 2 / (4 π ε 0 r 2 ) for the force between two point charges in free space"]'::jsonb,2),
    ('18','18.4','Electric field of a point charge','["recall and use E = Q / (4 π ε 0 r 2 ) for the electric field strength due to a point charge in free space"]'::jsonb,3),
    ('18','18.5','Electric potential','["define electric potential at a point as the work done per unit positive charge in bringing a small test charge from infinity to the point", "recall and use the fact that the electric field at a point is equal to the negative of potential gradient at that point", "use V = Q / (4 π ε 0 r ) for the electric potential in the field due to a point charge", "understand how the concept of electric potential leads to the electric potential energy of two point charges and use E P = Qq / (4 π ε 0 r )"]'::jsonb,4),
    ('19','19.1','Capacitors and capacitance','["define capacitance, as applied to both isolated spherical conductors and to parallel plate capacitors", "recall and use C = Q / V", "derive, using C = Q / V , formulae for the combined capacitance of capacitors in series and in parallel", "use the capacitance formulae for capacitors in series and in parallel Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('19','19.2','Energy stored in a capacitor','["determine the electric potential energy stored in a capacitor from the area under the potential-charge graph", "recall and use W = 2 1 QV = 2 1 CV 2"]'::jsonb,1),
    ('19','19.3','Discharging a capacitor','["analyse graphs of the variation with time of potential difference, charge and current for a capacitor discharging through a resistor", "recall and use τ = RC for the time constant for a capacitor discharging through a resistor", "use equations of the form x = x 0 e -( t / RC ) where x could represent current, charge or potential difference for a capacitor discharging through a resistor"]'::jsonb,2),
    ('20','20.1','Concept of a magnetic field','["understand that a magnetic field is an example of a field of force produced either by moving charges or by permanent magnets", "represent a magnetic field by field lines"]'::jsonb,0),
    ('20','20.2','Force on a current-carrying conductor','["understand that a force might act on a current-carrying conductor placed in a magnetic field", "recall and use the equation F = B I L sin θ , with directions as interpreted by Fleming''s left-hand rule", "define magnetic flux density as the force acting per unit current per unit length on a wire placed at right- angles to the magnetic field Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('20','20.3','Force on a moving charge','["determine the direction of the force on a charge moving in a magnetic field", "recall and use F = BQv sin θ", "understand the origin of the Hall voltage and derive and use the expression V H = B I / ( ntq ), where t = thickness", "understand the use of a Hall probe to measure magnetic flux density", "describe the motion of a charged particle moving in a uniform magnetic field perpendicular to the direction of motion of the particle", "explain how electric and magnetic fields can be used in velocity selection"]'::jsonb,2),
    ('20','20.4','Magnetic fields due to currents','["sketch magnetic field patterns due to the currents in a long straight wire, a flat circular coil and a long solenoid", "understand that the magnetic field due to the current in a solenoid is increased by a ferrous core", "explain the origin of the forces between current-carrying conductors and determine the direction of the forces"]'::jsonb,3),
    ('20','20.5','Electromagnetic induction','["define magnetic flux as the product of the magnetic flux density and the cross-sectional area perpendicular to the direction of the magnetic flux density", "recall and use Φ = BA", "understand and use the concept of magnetic flux linkage", "understand and explain experiments that demonstrate: • that a changing magnetic flux can induce an e.m.f. in a circuit • that the induced e.m.f. is in such a direction as to oppose the change producing it • the factors affecting the magnitude of the induced e.m.f.", "recall and use Faraday''s and Lenz''s laws of electromagnetic induction Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,4),
    ('21','21.1','Characteristics of alternating currents','["understand and use the terms period, frequency and peak value as applied to an alternating current or voltage", "use equations of the form x = x 0 sin ω t representing a sinusoidally alternating current or voltage", "recall and use the fact that the mean power in a resistive load is half the maximum power for a sinusoidal alternating current", "distinguish between root-mean-square (r.m.s.) and peak values and recall and use I r.m.s. = I 0 /", "and V r.m.s. = V 0 /", "for a sinusoidal alternating current"]'::jsonb,0),
    ('21','21.2','Rectification and smoothing','["distinguish graphically between half-wave and full-wave rectification", "explain the use of a single diode for the half-wave rectification of an alternating current", "explain the use of four diodes (bridge rectifier) for the full-wave rectification of an alternating current", "analyse the effect of a single capacitor in smoothing, including the effect of the values of capacitance and the load resistance"]'::jsonb,1),
    ('22','22.1','Energy and momentum of a photon','["understand that electromagnetic radiation has a particulate nature", "understand that a photon is a quantum of electromagnetic energy", "recall and use E = hf", "use the electronvolt (eV) as a unit of energy", "understand that a photon has momentum and that the momentum is given by p = E / c Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,0),
    ('22','22.2','Photoelectric effect','["understand that photoelectrons may be emitted from a metal surface when it is illuminated by electromagnetic radiation", "understand and use the terms threshold frequency and threshold wavelength", "explain photoelectric emission in terms of photon energy and work function energy", "recall and use hf = Φ + 2 1 mv max 2", "explain why the maximum kinetic energy of photoelectrons is independent of intensity, whereas the photoelectric current is proportional to intensity"]'::jsonb,1),
    ('22','22.3','Wave-particle duality','["understand that the photoelectric effect provides evidence for a particulate nature of electromagnetic radiation while phenomena such as interference and diffraction provide evidence for a wave nature", "describe and interpret qualitatively the evidence provided by electron diffraction for the wave nature of particles", "understand the de Broglie wavelength as the wavelength associated with a moving particle", "recall and use λ = h / p"]'::jsonb,2),
    ('22','22.4','Energy levels in atoms and line spectra','["understand that there are discrete electron energy levels in isolated atoms (e.g. atomic hydrogen)", "understand the appearance and formation of emission and absorption line spectra", "recall and use hf = E 1 - E 2 Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,3),
    ('23','23.1','Mass defect and nuclear binding energy','["understand the equivalence between energy and mass as represented by E = mc 2 and recall and use this equation", "represent simple nuclear reactions by nuclear equations of the form N He O H 7 14 2 4 8 17 1 1 \" + +", "define and use the terms mass defect and binding energy", "sketch the variation of binding energy per nucleon with nucleon number", "explain what is meant by nuclear fusion and nuclear fission", "explain the relevance of binding energy per nucleon to nuclear reactions, including nuclear fusion and nuclear fission", "calculate the energy released in nuclear reactions using E = c 2 ∆ m"]'::jsonb,0),
    ('23','23.2','Radioactive decay','["understand that fluctuations in count rate provide evidence for the random nature of radioactive decay", "understand that radioactive decay is both spontaneous and random", "define activity and decay constant, and recall and use A = λ N", "define half-life", "use λ = 0.693 / t 2 1", "understand the exponential nature of radioactive decay, and sketch and use the relationship x = x 0 e - λ t , where x could represent activity, number of undecayed nuclei or received count rate Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('24','24.1','Production and use of ultrasound','["understand that a piezo-electric crystal changes shape when a p.d. is applied across it and that the crystal generates an e.m.f. when its shape changes", "understand how ultrasound waves are generated and detected by a piezoelectric transducer", "understand how the reflection of pulses of ultrasound at boundaries between tissues can be used to obtain diagnostic information about internal structures", "define the specific acoustic impedance of a medium as Z = ρ c , where c is the speed of sound in the medium", "use I R / I 0 = ( Z 1 - Z 2 ) 2 / ( Z 1 + Z 2 ) 2 for the intensity reflection coefficient of a boundary between two media", "recall and use I = I 0 e - μ x for the attenuation of ultrasound in matter"]'::jsonb,0),
    ('24','24.2','Production and use of X-rays','["explain that X-rays are produced by electron bombardment of a metal target and calculate the minimum wavelength of X-rays produced from the accelerating p.d.", "understand the use of X-rays in imaging internal body structures, including an understanding of the term contrast in X-ray imaging", "recall and use I = I 0 e - μ x for the attenuation of X-rays in matter", "understand that computed tomography (CT) scanning produces a 3D image of an internal structure by first combining multiple X-ray images taken in the same section from different angles to obtain a 2D image of the section, then repeating this process along an axis and combining 2D images of multiple sections Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('24','24.3','PET scanning','["understand that a tracer is a substance containing radioactive nuclei that can be introduced into the body and is then absorbed by the tissue being studied", "recall that a tracer that decays by β + decay is used in positron emission tomography (PET scanning)", "understand that annihilation occurs when a particle interacts with its antiparticle and that mass-energy and momentum are conserved in the process", "explain that, in PET scanning, positrons emitted by the decay of the tracer annihilate when they interact with electrons in the tissue, producing a pair of gamma-ray photons travelling in opposite directions", "calculate the energy of the gamma-ray photons emitted during the annihilation of an electron-positron pair", "understand that the gamma-ray photons from an annihilation event travel outside the body and can be detected, and an image of the tracer concentration in the tissue can be created by processing the arrival times of the gamma-ray photons"]'::jsonb,2),
    ('25','25.1','Standard candles','["understand the term luminosity as the total power of radiation emitted by a star", "recall and use the inverse square law for radiant flux intensity F in terms of the luminosity L of the source F = L / (4 π d 2 )", "understand that an object of known luminosity is called a standard candle", "understand the use of standard candles to determine distances to galaxies"]'::jsonb,0),
    ('25','25.2','Stellar radii','["recall and use Wien''s displacement law λ max ∝ 1 / T to estimate the peak surface temperature of a star", "use the Stefan-Boltzmann law L = 4 π σ r 2 T 4", "use Wien''s displacement law and the Stefan-Boltzmann law to estimate the radius of a star Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027. Subject content", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,1),
    ('25','25.3','Hubble''s law and the Big Bang theory','["understand that the lines in the emission and absorption spectra from distant objects show an increase in wavelength from their known values", "use ∆ λ / λ . ∆ f / f . v / c for the redshift of electromagnetic radiation from a source moving relative to an observer", "explain why redshift leads to the idea that the Universe is expanding", "recall and use Hubble''s law v . H 0 d and explain how this leads to the Big Bang theory (candidates will only be required to use SI units) Cambridge International AS & A Level Physics 9702 syllabus for 2025, 2026 and 2027.", "www.cambridgeinternational.org/alevel Back to contents page"]'::jsonb,2)
  ) AS x(tcode, scode, sname, objectives, sort)
  JOIN public.syllabus_topics t ON t.template_id=v_tpl AND t.code=x.tcode AND t.deleted_at IS NULL;
  RAISE NOTICE 'Loaded Physics A2';
END $$;
